// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/fields.py, scapy/layers/*.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — each field's rendering class, nested-packet fields,
//   unset-is-None fields, overloaded fields and display names, read
//   off scapy's classes for the layers wiry shares

//! How scapy prints each field. Generated by `dev/gen_render_tables.py`;
//! regenerate rather than edit.

use crate::render::Repr;

pub fn repr_of(layer: &str, field: &str) -> Repr {
    match layer {
        "AH" => match field {
            "spi" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ARP" => match field {
            "hwtype" => Repr::Hex,
            "ptype" => Repr::Hex,
            "hwsrc" => Repr::Bytes,
            "psrc" => Repr::Bytes,
            "hwdst" => Repr::Bytes,
            "pdst" => Repr::Bytes,
            _ => Repr::Auto,
        },
        "BOOTP" => match field {
            "xid" => Repr::Hex,
            "chaddr" => Repr::Bytes,
            "sname" => Repr::Bytes,
            "file" => Repr::Bytes,
            _ => Repr::Auto,
        },
        "CookedLinux" => match field {
            "lladdrtype" => Repr::Hex,
            "src" => Repr::Bytes,
            "proto" => Repr::Hex,
            _ => Repr::Auto,
        },
        "CookedLinuxV2" => match field {
            "proto" => Repr::Hex,
            "lladdrtype" => Repr::Hex,
            "src" => Repr::Bytes,
            _ => Repr::Auto,
        },
        "DHCP6" => match field {
            "trid" => Repr::Hex,
            _ => Repr::Auto,
        },
        "Dot1Q" => match field {
            "type" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ESP" => match field {
            "spi" => Repr::Hex,
            _ => Repr::Auto,
        },
        "Ether" => match field {
            "type" => Repr::Hex,
            _ => Repr::Auto,
        },
        "GRE" => match field {
            "proto" => Repr::Hex,
            "chksum" => Repr::Hex,
            "offset" => Repr::Hex,
            "key" => Repr::Hex,
            _ => Repr::Auto,
        },
        "HSRP" => match field {
            "auth" => Repr::Bytes,
            _ => Repr::Auto,
        },
        "ICMP" => match field {
            "chksum" => Repr::Hex,
            "id" => Repr::Hex,
            "seq" => Repr::Hex,
            "unused" => Repr::Bytes,
            "extpad" => Repr::Bytes,
            _ => Repr::Auto,
        },
        "ICMPv6MLDone" => match field {
            "cksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6MLQuery" => match field {
            "cksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6MLReport" => match field {
            "cksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6MLReport2" => match field {
            "cksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6ND_NA" => match field {
            "cksum" => Repr::Hex,
            "res" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6ND_NS" => match field {
            "cksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6ND_RA" => match field {
            "cksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6ND_RS" => match field {
            "cksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6ND_Redirect" => match field {
            "cksum" => Repr::Hex,
            "res" => Repr::Hex,
            _ => Repr::Auto,
        },
        "IP" => match field {
            "tos" => Repr::Hex,
            "chksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "LLC" => match field {
            "dsap" => Repr::Hex,
            "ssap" => Repr::Hex,
            _ => Repr::Auto,
        },
        "NetflowHeaderV5" => match field {
            "unixSecs" => Repr::Utc,
            "unixNanoSeconds" => Repr::Utc,
            _ => Repr::Auto,
        },
        "NetflowHeaderV9" => match field {
            "unixSecs" => Repr::Utc,
            _ => Repr::Auto,
        },
        "PPPoE" => match field {
            "sessionid" => Repr::Hex,
            _ => Repr::Auto,
        },
        "PPPoED" => match field {
            "sessionid" => Repr::Hex,
            _ => Repr::Auto,
        },
        "Padding" => match field {
            "load" => Repr::Bytes,
            _ => Repr::Auto,
        },
        "Radius" => match field {
            "authenticator" => Repr::Bytes,
            _ => Repr::Auto,
        },
        "Raw" => match field {
            "load" => Repr::Bytes,
            _ => Repr::Auto,
        },
        "SCTP" => match field {
            "tag" => Repr::Hex,
            "chksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "SMB2_Header" => match field {
            "NextCommand" => Repr::Hex,
            _ => Repr::Auto,
        },
        "SNAP" => match field {
            "OUI" => Repr::Hex,
            "code" => Repr::Hex,
            _ => Repr::Auto,
        },
        "TCP" => match field {
            "chksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "UDP" => match field {
            "chksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "VRRP" => match field {
            "chksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "VXLAN" => match field {
            "vni" => Repr::Hex,
            _ => Repr::Auto,
        },
        _ => Repr::Auto,
    }
}

/// Fields scapy shows as a nested list of packets rather than as a
/// value, which `show()` marks with a backslash line.
pub fn holds_packets(layer: &str, field: &str) -> bool {
    matches!(
        (layer, field),
        ("DNS", "an")
            | ("DNS", "ar")
            | ("DNS", "ns")
            | ("DNS", "qd")
            | ("ICMPv6MLReport2", "records")
            | ("IP", "options")
            | ("IPv6ExtHdrDestOpt", "options")
            | ("IPv6ExtHdrHopByHop", "options")
    )
}

/// Fields a layer still being built shows as `None`: their value is
/// computed when it is built.
pub fn unset_is_none(layer: &str, field: &str) -> bool {
    matches!(
        (layer, field),
        ("AH", "nh")
            | ("AH", "payloadlen")
            | ("AH", "reserved")
            | ("ARP", "hwlen")
            | ("ARP", "plen")
            | ("DHCP6", "msgtype")
            | ("DNS", "ancount")
            | ("DNS", "arcount")
            | ("DNS", "length")
            | ("DNS", "nscount")
            | ("DNS", "qdcount")
            | ("Ether", "dst")
            | ("GRE", "chksum")
            | ("GRE", "key")
            | ("GRE", "offset")
            | ("ICMP", "chksum")
            | ("ICMP", "ext")
            | ("ICMPv6MLDone", "cksum")
            | ("ICMPv6MLQuery", "cksum")
            | ("ICMPv6MLReport", "cksum")
            | ("ICMPv6MLReport2", "cksum")
            | ("ICMPv6MLReport2", "records_number")
            | ("ICMPv6ND_NA", "cksum")
            | ("ICMPv6ND_NS", "cksum")
            | ("ICMPv6ND_RA", "cksum")
            | ("ICMPv6ND_RS", "cksum")
            | ("ICMPv6ND_Redirect", "cksum")
            | ("IP", "chksum")
            | ("IP", "ihl")
            | ("IP", "len")
            | ("IPv6", "plen")
            | ("IPv6ExtHdrDestOpt", "len")
            | ("IPv6ExtHdrFragment", "id")
            | ("IPv6ExtHdrHopByHop", "len")
            | ("IPv6ExtHdrRouting", "len")
            | ("IPv6ExtHdrRouting", "segleft")
            | ("NBTSession", "LENGTH")
            | ("NetflowHeaderV5", "count")
            | ("NetflowHeaderV9", "count")
            | ("PPPoE", "len")
            | ("PPPoED", "len")
            | ("RTP", "numsync")
            | ("RadioTap", "len")
            | ("RadioTap", "present")
            | ("Radius", "len")
            | ("SCTP", "chksum")
            | ("TCP", "chksum")
            | ("TCP", "dataofs")
            | ("UDP", "chksum")
            | ("UDP", "len")
            | ("VRRP", "chksum")
            | ("VRRP", "ipcount")
    )
}

/// scapy's `overload_fields`: what stacking `child` on `parent` sets in
/// `parent`, which a layer being built shows as though it were given.
pub fn overloads(parent: &str, child: &str) -> &'static [&'static str] {
    match (parent, child) {
        ("AH", "IP") => &["nh"],
        ("AH", "IPv6") => &["nh"],
        ("BOOTP", "DHCP") => &["options"],
        ("CookedLinux", "ARP") => &["proto"],
        ("CookedLinux", "Dot1Q") => &["proto"],
        ("CookedLinux", "Ether") => &["proto"],
        ("CookedLinux", "IP") => &["proto"],
        ("CookedLinux", "IPv6") => &["proto"],
        ("CookedLinux", "LLC") => &["proto"],
        ("CookedLinux", "PPPoE") => &["proto"],
        ("CookedLinux", "PPPoED") => &["proto"],
        ("Dot11", "Dot11AssoReq") => &["subtype", "type"],
        ("Dot11", "Dot11AssoResp") => &["subtype", "type"],
        ("Dot11", "Dot11Auth") => &["subtype", "type"],
        ("Dot11", "Dot11Beacon") => &["subtype", "type"],
        ("Dot11", "Dot11ProbeReq") => &["subtype", "type"],
        ("Dot11", "Dot11ProbeResp") => &["subtype", "type"],
        ("Dot11", "LLC") => &["type"],
        ("Ether", "ARP") => &["type"],
        ("Ether", "Dot1Q") => &["type"],
        ("Ether", "Ether") => &["type"],
        ("Ether", "IP") => &["type"],
        ("Ether", "IPv6") => &["type"],
        ("Ether", "LLC") => &["type"],
        ("Ether", "PPPoE") => &["type"],
        ("Ether", "PPPoED") => &["type"],
        ("GRE", "ARP") => &["proto"],
        ("GRE", "Dot1Q") => &["proto"],
        ("GRE", "Ether") => &["proto"],
        ("GRE", "IP") => &["proto"],
        ("GRE", "IPv6") => &["proto"],
        ("GRE", "LLC") => &["proto"],
        ("IP", "AH") => &["proto"],
        ("IP", "ESP") => &["proto"],
        ("IP", "GRE") => &["frag", "proto"],
        ("IP", "ICMP") => &["frag", "proto"],
        ("IP", "IP") => &["frag", "proto"],
        ("IP", "IPv6") => &["proto"],
        ("IP", "SCTP") => &["proto"],
        ("IP", "TCP") => &["frag", "proto"],
        ("IP", "UDP") => &["frag", "proto"],
        ("IP", "VRRP") => &["proto"],
        ("IPv6", "AH") => &["nh"],
        ("IPv6", "ESP") => &["nh"],
        ("IPv6", "GRE") => &["nh"],
        ("IPv6", "ICMPv6MLDone") => &["dst", "hlim", "nh"],
        ("IPv6", "ICMPv6MLQuery") => &["dst", "hlim", "nh"],
        ("IPv6", "ICMPv6MLReport") => &["hlim", "nh"],
        ("IPv6", "ICMPv6MLReport2") => &["dst", "hlim", "nh"],
        ("IPv6", "ICMPv6ND_NA") => &["dst", "hlim", "nh"],
        ("IPv6", "ICMPv6ND_NS") => &["dst", "hlim", "nh"],
        ("IPv6", "ICMPv6ND_RA") => &["dst", "hlim", "nh"],
        ("IPv6", "ICMPv6ND_RS") => &["dst", "hlim", "nh"],
        ("IPv6", "ICMPv6ND_Redirect") => &["dst", "hlim", "nh"],
        ("IPv6", "IP") => &["nh"],
        ("IPv6", "IPv6") => &["nh"],
        ("IPv6", "IPv6ExtHdrDestOpt") => &["nh"],
        ("IPv6", "IPv6ExtHdrFragment") => &["nh"],
        ("IPv6", "IPv6ExtHdrHopByHop") => &["nh"],
        ("IPv6", "IPv6ExtHdrRouting") => &["nh"],
        ("IPv6", "SCTP") => &["nh"],
        ("IPv6", "TCP") => &["nh"],
        ("IPv6", "UDP") => &["nh"],
        ("IPv6ExtHdrDestOpt", "AH") => &["nh"],
        ("IPv6ExtHdrDestOpt", "ESP") => &["nh"],
        ("IPv6ExtHdrHopByHop", "AH") => &["nh"],
        ("IPv6ExtHdrHopByHop", "ESP") => &["nh"],
        ("IPv6ExtHdrRouting", "AH") => &["nh"],
        ("IPv6ExtHdrRouting", "ESP") => &["nh"],
        ("LLC", "SNAP") => &["ctrl", "dsap", "ssap"],
        ("LLC", "STP") => &["ctrl", "dsap", "ssap"],
        ("Loopback", "IP") => &["type"],
        ("Loopback", "IPv6") => &["type"],
        ("PPP", "IP") => &["proto"],
        ("PPP", "IPv6") => &["proto"],
        ("PPPoE", "PPP") => &["code"],
        ("SNAP", "ARP") => &["code"],
        ("SNAP", "Dot1Q") => &["code"],
        ("SNAP", "Ether") => &["code"],
        ("SNAP", "IP") => &["code"],
        ("SNAP", "IPv6") => &["code"],
        ("SNAP", "STP") => &["code"],
        ("TCP", "DNS") => &["sport"],
        ("TCP", "LDAP") => &["dport", "sport"],
        ("TCP", "NBTSession") => &["dport", "sport"],
        ("UDP", "BOOTP") => &["dport", "sport"],
        ("UDP", "DHCP6") => &["dport", "sport"],
        ("UDP", "DNS") => &["sport"],
        ("UDP", "ESP") => &["dport", "sport"],
        ("UDP", "GRE") => &["dport"],
        ("UDP", "HSRP") => &["dport", "sport"],
        ("UDP", "NTP") => &["dport", "sport"],
        ("UDP", "RIP") => &["dport", "sport"],
        ("UDP", "Radius") => &["dport", "sport"],
        ("UDP", "SNMP") => &["dport", "sport"],
        ("UDP", "TFTP") => &["dport"],
        ("UDP", "VXLAN") => &["dport", "sport"],
        ("VXLAN", "Ether") => &["NextProtocol", "flags"],
        ("VXLAN", "IP") => &["NextProtocol", "flags"],
        ("VXLAN", "IPv6") => &["NextProtocol", "flags"],
        _ => &[],
    }
}

/// scapy's `Packet.name`, which is what `show()` prints and is
/// not always the class name `summary()` prints.
pub fn display_name(layer: &str) -> &str {
    match layer {
        "CookedLinux" => "cooked linux",
        "CookedLinuxV2" => "cooked linux v2",
        "DHCP" => "DHCP options",
        "DHCP6" => "DHCPv6 Generic Message",
        "DNSQR" => "DNS Question Record",
        "DNSRR" => "DNS Resource Record",
        "Dot11" => "802.11",
        "Dot11AssoReq" => "802.11 Association Request",
        "Dot11AssoResp" => "802.11 Association Response",
        "Dot11Auth" => "802.11 Authentication",
        "Dot11Beacon" => "802.11 Beacon",
        "Dot11ProbeReq" => "802.11 Probe Request",
        "Dot11ProbeResp" => "802.11 Probe Response",
        "Dot1Q" => "802.1Q",
        "Ether" => "Ethernet",
        "ICMPv6MLDone" => "MLD - Multicast Listener Done",
        "ICMPv6MLQuery" => "MLD - Multicast Listener Query",
        "ICMPv6MLReport" => "MLD - Multicast Listener Report",
        "ICMPv6MLReport2" => "MLDv2 - Multicast Listener Report",
        "ICMPv6ND_NA" => "ICMPv6 Neighbor Discovery - Neighbor Advertisement",
        "ICMPv6ND_NS" => "ICMPv6 Neighbor Discovery - Neighbor Solicitation",
        "ICMPv6ND_RA" => "ICMPv6 Neighbor Discovery - Router Advertisement",
        "ICMPv6ND_RS" => "ICMPv6 Neighbor Discovery - Router Solicitation",
        "ICMPv6ND_Redirect" => "ICMPv6 Neighbor Discovery - Redirect",
        "IPv6ExtHdrDestOpt" => "IPv6 Extension Header - Destination Options Header",
        "IPv6ExtHdrFragment" => "IPv6 Extension Header - Fragmentation header",
        "IPv6ExtHdrHopByHop" => "IPv6 Extension Header - Hop-by-Hop Options Header",
        "IPv6ExtHdrRouting" => "IPv6 Option Header Routing",
        "NBTSession" => "NBT Session Packet",
        "NetflowHeaderV5" => "Netflow Header v5",
        "NetflowHeaderV9" => "Netflow Header V9",
        "PPP" => "PPP Link Layer",
        "PPPoE" => "PPP over Ethernet",
        "PPPoED" => "PPP over Ethernet Discovery",
        "RIP" => "RIP header",
        "Radius" => "RADIUS",
        "SMB2_Header" => "SMB2 Header",
        "STP" => "Spanning Tree Protocol",
        "TFTP" => "TFTP opcode",
        other => other,
    }
}
