// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/fields.py, scapy/layers/*.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — each field's rendering class, nested-packet fields,
//   unset-is-None fields, overloaded fields and display names, read
//   off scapy's classes for the layers wiry shares

//! How scapy prints each field. Generated by `dev/gen_render_tables.py`;
//! regenerate rather than edit.

use crate::render::Repr;

pub fn repr_of(layer: &str, field: &str) -> Repr {
    match layer {
        "AH" => match field {
            "spi" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ARP" => match field {
            "hwtype" => Repr::Hex,
            "ptype" => Repr::Hex,
            "hwsrc" => Repr::FixedBytes,
            "psrc" => Repr::FixedBytes,
            "hwdst" => Repr::FixedBytes,
            "pdst" => Repr::FixedBytes,
            _ => Repr::Auto,
        },
        "BOOTP" => match field {
            "xid" => Repr::Hex,
            "chaddr" => Repr::Chaddr,
            "sname" => Repr::FixedBytes,
            "file" => Repr::FixedBytes,
            "options" => Repr::StrEnum(&[(b"\x63\x82\x53\x63", "DHCP magic")]),
            _ => Repr::Auto,
        },
        "CookedLinux" => match field {
            "lladdrtype" => Repr::Hex,
            "src" => Repr::FixedBytes,
            "proto" => Repr::Hex,
            _ => Repr::Auto,
        },
        "CookedLinuxV2" => match field {
            "proto" => Repr::Hex,
            "lladdrtype" => Repr::Hex,
            "src" => Repr::FixedBytes,
            _ => Repr::Auto,
        },
        "DHCP6" => match field {
            "trid" => Repr::Hex,
            _ => Repr::Auto,
        },
        "Dot1Q" => match field {
            "type" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ESP" => match field {
            "spi" => Repr::Hex,
            _ => Repr::Auto,
        },
        "Ether" => match field {
            "type" => Repr::Hex,
            _ => Repr::Auto,
        },
        "GRE" => match field {
            "proto" => Repr::Hex,
            "chksum" => Repr::Hex,
            "offset" => Repr::Hex,
            "key" => Repr::Hex,
            _ => Repr::Auto,
        },
        "HSRP" => match field {
            "auth" => Repr::FixedBytes,
            _ => Repr::Auto,
        },
        "ICMP" => match field {
            "chksum" => Repr::Hex,
            "id" => Repr::Hex,
            "seq" => Repr::Hex,
            "unused" => Repr::FixedBytes,
            "extpad" => Repr::FixedBytes,
            _ => Repr::Auto,
        },
        "ICMPv6MLDone" => match field {
            "cksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6MLQuery" => match field {
            "cksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6MLReport" => match field {
            "cksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6MLReport2" => match field {
            "cksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6ND_NA" => match field {
            "cksum" => Repr::Hex,
            "res" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6ND_NS" => match field {
            "cksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6ND_RA" => match field {
            "cksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6ND_RS" => match field {
            "cksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "ICMPv6ND_Redirect" => match field {
            "cksum" => Repr::Hex,
            "res" => Repr::Hex,
            _ => Repr::Auto,
        },
        "IP" => match field {
            "tos" => Repr::Hex,
            "chksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "IPv6ExtHdrRouting" => match field {
            "addresses" => Repr::Ip6List,
            _ => Repr::Auto,
        },
        "LLC" => match field {
            "dsap" => Repr::Hex,
            "ssap" => Repr::Hex,
            _ => Repr::Auto,
        },
        "NetflowHeaderV5" => match field {
            "unixSecs" => Repr::Utc,
            "unixNanoSeconds" => Repr::Utc,
            _ => Repr::Auto,
        },
        "NetflowHeaderV9" => match field {
            "unixSecs" => Repr::Utc,
            _ => Repr::Auto,
        },
        "PPPoE" => match field {
            "sessionid" => Repr::Hex,
            _ => Repr::Auto,
        },
        "PPPoED" => match field {
            "sessionid" => Repr::Hex,
            _ => Repr::Auto,
        },
        "Padding" => match field {
            "load" => Repr::Bytes,
            _ => Repr::Auto,
        },
        "Radius" => match field {
            "authenticator" => Repr::HexBytes,
            _ => Repr::Auto,
        },
        "Raw" => match field {
            "load" => Repr::Bytes,
            _ => Repr::Auto,
        },
        "SCTP" => match field {
            "tag" => Repr::Hex,
            "chksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "SMB2_Header" => match field {
            "NextCommand" => Repr::Hex,
            _ => Repr::Auto,
        },
        "SNAP" => match field {
            "OUI" => Repr::Hex,
            "code" => Repr::Hex,
            _ => Repr::Auto,
        },
        "STP" => match field {
            "age" => Repr::Bcd,
            "maxage" => Repr::Bcd,
            "hellotime" => Repr::Bcd,
            "fwddelay" => Repr::Bcd,
            _ => Repr::Auto,
        },
        "TCP" => match field {
            "chksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "UDP" => match field {
            "chksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "VRRP" => match field {
            "chksum" => Repr::Hex,
            _ => Repr::Auto,
        },
        "VXLAN" => match field {
            "vni" => Repr::Hex,
            _ => Repr::Auto,
        },
        _ => Repr::Auto,
    }
}

/// Fields scapy shows as a nested list of packets rather than as a
/// value, which `show()` marks with a backslash line.
pub fn holds_packets(layer: &str, field: &str) -> bool {
    matches!(
        (layer, field),
        ("DNS", "an")
            | ("DNS", "ar")
            | ("DNS", "ns")
            | ("DNS", "qd")
            | ("ICMPv6MLReport2", "records")
            | ("IP", "options")
            | ("IPv6ExtHdrDestOpt", "options")
            | ("IPv6ExtHdrHopByHop", "options")
    )
}

/// Fields scapy holds as a single value. An empty one still prints,
/// where `repr()` leaves out an empty list.
pub fn scalar(layer: &str, field: &str) -> bool {
    matches!(
        (layer, field),
        ("AH", "nh")
            | ("AH", "payloadlen")
            | ("AH", "reserved")
            | ("AH", "seq")
            | ("AH", "spi")
            | ("ARP", "hwdst")
            | ("ARP", "hwlen")
            | ("ARP", "hwsrc")
            | ("ARP", "hwtype")
            | ("ARP", "op")
            | ("ARP", "pdst")
            | ("ARP", "plen")
            | ("ARP", "psrc")
            | ("ARP", "ptype")
            | ("BOOTP", "chaddr")
            | ("BOOTP", "ciaddr")
            | ("BOOTP", "file")
            | ("BOOTP", "flags")
            | ("BOOTP", "giaddr")
            | ("BOOTP", "hlen")
            | ("BOOTP", "hops")
            | ("BOOTP", "htype")
            | ("BOOTP", "op")
            | ("BOOTP", "options")
            | ("BOOTP", "secs")
            | ("BOOTP", "siaddr")
            | ("BOOTP", "sname")
            | ("BOOTP", "xid")
            | ("BOOTP", "yiaddr")
            | ("CookedLinux", "lladdrlen")
            | ("CookedLinux", "lladdrtype")
            | ("CookedLinux", "pkttype")
            | ("CookedLinux", "proto")
            | ("CookedLinux", "src")
            | ("CookedLinuxV2", "ifindex")
            | ("CookedLinuxV2", "lladdrlen")
            | ("CookedLinuxV2", "lladdrtype")
            | ("CookedLinuxV2", "pkttype")
            | ("CookedLinuxV2", "proto")
            | ("CookedLinuxV2", "reserved")
            | ("CookedLinuxV2", "src")
            | ("DHCP6", "msgtype")
            | ("DHCP6", "trid")
            | ("DNS", "aa")
            | ("DNS", "ad")
            | ("DNS", "ancount")
            | ("DNS", "arcount")
            | ("DNS", "cd")
            | ("DNS", "id")
            | ("DNS", "length")
            | ("DNS", "nscount")
            | ("DNS", "opcode")
            | ("DNS", "qdcount")
            | ("DNS", "qr")
            | ("DNS", "ra")
            | ("DNS", "rcode")
            | ("DNS", "rd")
            | ("DNS", "tc")
            | ("DNS", "z")
            | ("Dot11", "FCfield")
            | ("Dot11", "ID")
            | ("Dot11", "SC")
            | ("Dot11", "addr1")
            | ("Dot11", "addr2")
            | ("Dot11", "addr3")
            | ("Dot11", "addr4")
            | ("Dot11", "proto")
            | ("Dot11", "subtype")
            | ("Dot11", "type")
            | ("Dot11AssoReq", "cap")
            | ("Dot11AssoReq", "listen_interval")
            | ("Dot11AssoResp", "AID")
            | ("Dot11AssoResp", "cap")
            | ("Dot11AssoResp", "status")
            | ("Dot11Auth", "algo")
            | ("Dot11Auth", "seqnum")
            | ("Dot11Auth", "status")
            | ("Dot11Beacon", "beacon_interval")
            | ("Dot11Beacon", "cap")
            | ("Dot11Beacon", "timestamp")
            | ("Dot11ProbeResp", "beacon_interval")
            | ("Dot11ProbeResp", "cap")
            | ("Dot11ProbeResp", "timestamp")
            | ("Dot1Q", "dei")
            | ("Dot1Q", "prio")
            | ("Dot1Q", "type")
            | ("Dot1Q", "vlan")
            | ("ESP", "seq")
            | ("ESP", "spi")
            | ("Ether", "dst")
            | ("Ether", "src")
            | ("Ether", "type")
            | ("GRE", "chksum")
            | ("GRE", "chksum_present")
            | ("GRE", "flags")
            | ("GRE", "key")
            | ("GRE", "key_present")
            | ("GRE", "offset")
            | ("GRE", "proto")
            | ("GRE", "recursion_control")
            | ("GRE", "routing_present")
            | ("GRE", "seqnum_present")
            | ("GRE", "strict_route_source")
            | ("GRE", "version")
            | ("HSRP", "auth")
            | ("HSRP", "group")
            | ("HSRP", "hellotime")
            | ("HSRP", "holdtime")
            | ("HSRP", "opcode")
            | ("HSRP", "priority")
            | ("HSRP", "reserved")
            | ("HSRP", "state")
            | ("HSRP", "version")
            | ("HSRP", "virtualIP")
            | ("ICMP", "addr_mask")
            | ("ICMP", "chksum")
            | ("ICMP", "code")
            | ("ICMP", "ext")
            | ("ICMP", "extpad")
            | ("ICMP", "gw")
            | ("ICMP", "id")
            | ("ICMP", "length")
            | ("ICMP", "nexthopmtu")
            | ("ICMP", "ptr")
            | ("ICMP", "reserved")
            | ("ICMP", "seq")
            | ("ICMP", "ts_ori")
            | ("ICMP", "ts_rx")
            | ("ICMP", "ts_tx")
            | ("ICMP", "type")
            | ("ICMP", "unused")
            | ("ICMPv6MLDone", "cksum")
            | ("ICMPv6MLDone", "code")
            | ("ICMPv6MLDone", "mladdr")
            | ("ICMPv6MLDone", "mrd")
            | ("ICMPv6MLDone", "reserved")
            | ("ICMPv6MLDone", "type")
            | ("ICMPv6MLQuery", "cksum")
            | ("ICMPv6MLQuery", "code")
            | ("ICMPv6MLQuery", "mladdr")
            | ("ICMPv6MLQuery", "mrd")
            | ("ICMPv6MLQuery", "reserved")
            | ("ICMPv6MLQuery", "type")
            | ("ICMPv6MLReport", "cksum")
            | ("ICMPv6MLReport", "code")
            | ("ICMPv6MLReport", "mladdr")
            | ("ICMPv6MLReport", "mrd")
            | ("ICMPv6MLReport", "reserved")
            | ("ICMPv6MLReport", "type")
            | ("ICMPv6MLReport2", "cksum")
            | ("ICMPv6MLReport2", "records_number")
            | ("ICMPv6MLReport2", "res")
            | ("ICMPv6MLReport2", "reserved")
            | ("ICMPv6MLReport2", "type")
            | ("ICMPv6ND_NA", "O")
            | ("ICMPv6ND_NA", "R")
            | ("ICMPv6ND_NA", "S")
            | ("ICMPv6ND_NA", "cksum")
            | ("ICMPv6ND_NA", "code")
            | ("ICMPv6ND_NA", "res")
            | ("ICMPv6ND_NA", "tgt")
            | ("ICMPv6ND_NA", "type")
            | ("ICMPv6ND_NS", "cksum")
            | ("ICMPv6ND_NS", "code")
            | ("ICMPv6ND_NS", "res")
            | ("ICMPv6ND_NS", "tgt")
            | ("ICMPv6ND_NS", "type")
            | ("ICMPv6ND_RA", "H")
            | ("ICMPv6ND_RA", "M")
            | ("ICMPv6ND_RA", "O")
            | ("ICMPv6ND_RA", "P")
            | ("ICMPv6ND_RA", "chlim")
            | ("ICMPv6ND_RA", "cksum")
            | ("ICMPv6ND_RA", "code")
            | ("ICMPv6ND_RA", "prf")
            | ("ICMPv6ND_RA", "reachabletime")
            | ("ICMPv6ND_RA", "res")
            | ("ICMPv6ND_RA", "retranstimer")
            | ("ICMPv6ND_RA", "routerlifetime")
            | ("ICMPv6ND_RA", "type")
            | ("ICMPv6ND_RS", "cksum")
            | ("ICMPv6ND_RS", "code")
            | ("ICMPv6ND_RS", "res")
            | ("ICMPv6ND_RS", "type")
            | ("ICMPv6ND_Redirect", "cksum")
            | ("ICMPv6ND_Redirect", "code")
            | ("ICMPv6ND_Redirect", "dst")
            | ("ICMPv6ND_Redirect", "res")
            | ("ICMPv6ND_Redirect", "tgt")
            | ("ICMPv6ND_Redirect", "type")
            | ("IP", "chksum")
            | ("IP", "dst")
            | ("IP", "flags")
            | ("IP", "frag")
            | ("IP", "id")
            | ("IP", "ihl")
            | ("IP", "len")
            | ("IP", "proto")
            | ("IP", "src")
            | ("IP", "tos")
            | ("IP", "ttl")
            | ("IP", "version")
            | ("IPv6", "dst")
            | ("IPv6", "fl")
            | ("IPv6", "hlim")
            | ("IPv6", "nh")
            | ("IPv6", "plen")
            | ("IPv6", "src")
            | ("IPv6", "tc")
            | ("IPv6", "version")
            | ("IPv6ExtHdrDestOpt", "len")
            | ("IPv6ExtHdrDestOpt", "nh")
            | ("IPv6ExtHdrFragment", "id")
            | ("IPv6ExtHdrFragment", "m")
            | ("IPv6ExtHdrFragment", "nh")
            | ("IPv6ExtHdrFragment", "offset")
            | ("IPv6ExtHdrFragment", "res1")
            | ("IPv6ExtHdrFragment", "res2")
            | ("IPv6ExtHdrHopByHop", "len")
            | ("IPv6ExtHdrHopByHop", "nh")
            | ("IPv6ExtHdrRouting", "len")
            | ("IPv6ExtHdrRouting", "nh")
            | ("IPv6ExtHdrRouting", "reserved")
            | ("IPv6ExtHdrRouting", "segleft")
            | ("IPv6ExtHdrRouting", "type")
            | ("LLC", "ctrl")
            | ("LLC", "dsap")
            | ("LLC", "ssap")
            | ("Loopback", "type")
            | ("NBTSession", "LENGTH")
            | ("NBTSession", "TYPE")
            | ("NetflowHeaderV5", "count")
            | ("NetflowHeaderV5", "engineID")
            | ("NetflowHeaderV5", "engineType")
            | ("NetflowHeaderV5", "flowSequence")
            | ("NetflowHeaderV5", "samplingInterval")
            | ("NetflowHeaderV5", "sysUptime")
            | ("NetflowHeaderV5", "unixNanoSeconds")
            | ("NetflowHeaderV5", "unixSecs")
            | ("NetflowHeaderV9", "SourceID")
            | ("NetflowHeaderV9", "count")
            | ("NetflowHeaderV9", "sysUptime")
            | ("NetflowHeaderV9", "unixSecs")
            | ("PPP", "proto")
            | ("PPPoE", "code")
            | ("PPPoE", "len")
            | ("PPPoE", "sessionid")
            | ("PPPoE", "type")
            | ("PPPoE", "version")
            | ("PPPoED", "code")
            | ("PPPoED", "len")
            | ("PPPoED", "sessionid")
            | ("PPPoED", "type")
            | ("PPPoED", "version")
            | ("Padding", "load")
            | ("RIP", "cmd")
            | ("RIP", "null")
            | ("RIP", "version")
            | ("RTP", "extension")
            | ("RTP", "marker")
            | ("RTP", "numsync")
            | ("RTP", "padding")
            | ("RTP", "payload_type")
            | ("RTP", "sequence")
            | ("RTP", "sourcesync")
            | ("RTP", "timestamp")
            | ("RTP", "version")
            | ("RadioTap", "len")
            | ("RadioTap", "pad")
            | ("RadioTap", "present")
            | ("RadioTap", "version")
            | ("Radius", "authenticator")
            | ("Radius", "code")
            | ("Radius", "id")
            | ("Radius", "len")
            | ("Raw", "load")
            | ("SCTP", "chksum")
            | ("SCTP", "dport")
            | ("SCTP", "sport")
            | ("SCTP", "tag")
            | ("SMB2_Header", "Command")
            | ("SMB2_Header", "CreditCharge")
            | ("SMB2_Header", "CreditRequest")
            | ("SMB2_Header", "Flags")
            | ("SMB2_Header", "NextCommand")
            | ("SMB2_Header", "SessionId")
            | ("SMB2_Header", "Status")
            | ("SMB2_Header", "StructureSize")
            | ("SNAP", "OUI")
            | ("SNAP", "code")
            | ("STP", "age")
            | ("STP", "bpduflags")
            | ("STP", "bpdutype")
            | ("STP", "bridgeid")
            | ("STP", "bridgemac")
            | ("STP", "fwddelay")
            | ("STP", "hellotime")
            | ("STP", "maxage")
            | ("STP", "pathcost")
            | ("STP", "portid")
            | ("STP", "proto")
            | ("STP", "rootid")
            | ("STP", "rootmac")
            | ("STP", "version")
            | ("TCP", "ack")
            | ("TCP", "chksum")
            | ("TCP", "dataofs")
            | ("TCP", "dport")
            | ("TCP", "flags")
            | ("TCP", "reserved")
            | ("TCP", "seq")
            | ("TCP", "sport")
            | ("TCP", "urgptr")
            | ("TCP", "window")
            | ("TFTP", "op")
            | ("UDP", "chksum")
            | ("UDP", "dport")
            | ("UDP", "len")
            | ("UDP", "sport")
            | ("VRRP", "adv")
            | ("VRRP", "authtype")
            | ("VRRP", "chksum")
            | ("VRRP", "ipcount")
            | ("VRRP", "priority")
            | ("VRRP", "type")
            | ("VRRP", "version")
            | ("VRRP", "vrid")
            | ("VXLAN", "flags")
            | ("VXLAN", "reserved0")
            | ("VXLAN", "reserved1")
            | ("VXLAN", "vni")
    )
}

/// Fields a layer still being built shows as `None`: their value is
/// computed when it is built.
pub fn unset_is_none(layer: &str, field: &str) -> bool {
    matches!(
        (layer, field),
        ("AH", "nh")
            | ("AH", "payloadlen")
            | ("AH", "reserved")
            | ("ARP", "hwlen")
            | ("ARP", "plen")
            | ("DHCP6", "msgtype")
            | ("DNS", "ancount")
            | ("DNS", "arcount")
            | ("DNS", "length")
            | ("DNS", "nscount")
            | ("DNS", "qdcount")
            | ("Ether", "dst")
            | ("GRE", "chksum")
            | ("GRE", "key")
            | ("GRE", "offset")
            | ("ICMP", "chksum")
            | ("ICMP", "ext")
            | ("ICMPv6MLDone", "cksum")
            | ("ICMPv6MLQuery", "cksum")
            | ("ICMPv6MLReport", "cksum")
            | ("ICMPv6MLReport2", "cksum")
            | ("ICMPv6MLReport2", "records_number")
            | ("ICMPv6ND_NA", "cksum")
            | ("ICMPv6ND_NS", "cksum")
            | ("ICMPv6ND_RA", "cksum")
            | ("ICMPv6ND_RS", "cksum")
            | ("ICMPv6ND_Redirect", "cksum")
            | ("IP", "chksum")
            | ("IP", "ihl")
            | ("IP", "len")
            | ("IPv6", "plen")
            | ("IPv6ExtHdrDestOpt", "len")
            | ("IPv6ExtHdrFragment", "id")
            | ("IPv6ExtHdrHopByHop", "len")
            | ("IPv6ExtHdrRouting", "len")
            | ("IPv6ExtHdrRouting", "segleft")
            | ("NBTSession", "LENGTH")
            | ("NetflowHeaderV5", "count")
            | ("NetflowHeaderV9", "count")
            | ("PPPoE", "len")
            | ("PPPoED", "len")
            | ("RTP", "numsync")
            | ("RadioTap", "len")
            | ("RadioTap", "present")
            | ("Radius", "len")
            | ("SCTP", "chksum")
            | ("TCP", "chksum")
            | ("TCP", "dataofs")
            | ("UDP", "chksum")
            | ("UDP", "len")
            | ("VRRP", "chksum")
            | ("VRRP", "ipcount")
    )
}

/// scapy's `overload_fields`: what stacking `child` on `parent` sets in
/// `parent`, which a layer being built shows as though it were given.
pub fn overloads(parent: &str, child: &str) -> &'static [&'static str] {
    match (parent, child) {
        ("AH", "IP") => &["nh"],
        ("AH", "IPv6") => &["nh"],
        ("BOOTP", "DHCP") => &["options"],
        ("CookedLinux", "ARP") => &["proto"],
        ("CookedLinux", "Dot1Q") => &["proto"],
        ("CookedLinux", "Ether") => &["proto"],
        ("CookedLinux", "IP") => &["proto"],
        ("CookedLinux", "IPv6") => &["proto"],
        ("CookedLinux", "LLC") => &["proto"],
        ("CookedLinux", "PPPoE") => &["proto"],
        ("CookedLinux", "PPPoED") => &["proto"],
        ("CookedLinuxV2", "ARP") => &["proto"],
        ("CookedLinuxV2", "Dot1Q") => &["proto"],
        ("CookedLinuxV2", "Ether") => &["proto"],
        ("CookedLinuxV2", "IP") => &["proto"],
        ("CookedLinuxV2", "IPv6") => &["proto"],
        ("CookedLinuxV2", "LLC") => &["proto"],
        ("CookedLinuxV2", "PPPoE") => &["proto"],
        ("CookedLinuxV2", "PPPoED") => &["proto"],
        ("Dot11", "Dot11AssoReq") => &["subtype", "type"],
        ("Dot11", "Dot11AssoResp") => &["subtype", "type"],
        ("Dot11", "Dot11Auth") => &["subtype", "type"],
        ("Dot11", "Dot11Beacon") => &["subtype", "type"],
        ("Dot11", "Dot11ProbeReq") => &["subtype", "type"],
        ("Dot11", "Dot11ProbeResp") => &["subtype", "type"],
        ("Dot11", "LLC") => &["type"],
        ("Dot1Q", "ARP") => &["type"],
        ("Dot1Q", "Dot1Q") => &["type"],
        ("Dot1Q", "Ether") => &["type"],
        ("Dot1Q", "IP") => &["type"],
        ("Dot1Q", "IPv6") => &["type"],
        ("Dot1Q", "LLC") => &["type"],
        ("Dot1Q", "PPPoE") => &["type"],
        ("Dot1Q", "PPPoED") => &["type"],
        ("Ether", "ARP") => &["type"],
        ("Ether", "Dot1Q") => &["type"],
        ("Ether", "Ether") => &["type"],
        ("Ether", "IP") => &["type"],
        ("Ether", "IPv6") => &["type"],
        ("Ether", "LLC") => &["type"],
        ("Ether", "PPPoE") => &["type"],
        ("Ether", "PPPoED") => &["type"],
        ("GRE", "ARP") => &["proto"],
        ("GRE", "Dot1Q") => &["proto"],
        ("GRE", "Ether") => &["proto"],
        ("GRE", "IP") => &["proto"],
        ("GRE", "IPv6") => &["proto"],
        ("GRE", "LLC") => &["proto"],
        ("IP", "AH") => &["proto"],
        ("IP", "ESP") => &["proto"],
        ("IP", "GRE") => &["frag", "proto"],
        ("IP", "ICMP") => &["frag", "proto"],
        ("IP", "IP") => &["frag", "proto"],
        ("IP", "IPv6") => &["proto"],
        ("IP", "SCTP") => &["proto"],
        ("IP", "TCP") => &["frag", "proto"],
        ("IP", "UDP") => &["frag", "proto"],
        ("IP", "VRRP") => &["proto"],
        ("IPv6", "AH") => &["nh"],
        ("IPv6", "ESP") => &["nh"],
        ("IPv6", "GRE") => &["nh"],
        ("IPv6", "ICMPv6MLDone") => &["dst", "hlim", "nh"],
        ("IPv6", "ICMPv6MLQuery") => &["dst", "hlim", "nh"],
        ("IPv6", "ICMPv6MLReport") => &["hlim", "nh"],
        ("IPv6", "ICMPv6MLReport2") => &["dst", "hlim", "nh"],
        ("IPv6", "ICMPv6ND_NA") => &["dst", "hlim", "nh"],
        ("IPv6", "ICMPv6ND_NS") => &["dst", "hlim", "nh"],
        ("IPv6", "ICMPv6ND_RA") => &["dst", "hlim", "nh"],
        ("IPv6", "ICMPv6ND_RS") => &["dst", "hlim", "nh"],
        ("IPv6", "ICMPv6ND_Redirect") => &["dst", "hlim", "nh"],
        ("IPv6", "IP") => &["nh"],
        ("IPv6", "IPv6") => &["nh"],
        ("IPv6", "IPv6ExtHdrDestOpt") => &["nh"],
        ("IPv6", "IPv6ExtHdrFragment") => &["nh"],
        ("IPv6", "IPv6ExtHdrHopByHop") => &["nh"],
        ("IPv6", "IPv6ExtHdrRouting") => &["nh"],
        ("IPv6", "SCTP") => &["nh"],
        ("IPv6", "TCP") => &["nh"],
        ("IPv6", "UDP") => &["nh"],
        ("IPv6ExtHdrDestOpt", "AH") => &["nh"],
        ("IPv6ExtHdrDestOpt", "ESP") => &["nh"],
        ("IPv6ExtHdrDestOpt", "GRE") => &["nh"],
        ("IPv6ExtHdrDestOpt", "ICMPv6MLDone") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrDestOpt", "ICMPv6MLQuery") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrDestOpt", "ICMPv6MLReport") => &["hlim", "nh"],
        ("IPv6ExtHdrDestOpt", "ICMPv6MLReport2") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrDestOpt", "ICMPv6ND_NA") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrDestOpt", "ICMPv6ND_NS") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrDestOpt", "ICMPv6ND_RA") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrDestOpt", "ICMPv6ND_RS") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrDestOpt", "ICMPv6ND_Redirect") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrDestOpt", "IP") => &["nh"],
        ("IPv6ExtHdrDestOpt", "IPv6") => &["nh"],
        ("IPv6ExtHdrDestOpt", "IPv6ExtHdrDestOpt") => &["nh"],
        ("IPv6ExtHdrDestOpt", "IPv6ExtHdrFragment") => &["nh"],
        ("IPv6ExtHdrDestOpt", "IPv6ExtHdrHopByHop") => &["nh"],
        ("IPv6ExtHdrDestOpt", "IPv6ExtHdrRouting") => &["nh"],
        ("IPv6ExtHdrDestOpt", "SCTP") => &["nh"],
        ("IPv6ExtHdrDestOpt", "TCP") => &["nh"],
        ("IPv6ExtHdrDestOpt", "UDP") => &["nh"],
        ("IPv6ExtHdrFragment", "AH") => &["nh"],
        ("IPv6ExtHdrFragment", "ESP") => &["nh"],
        ("IPv6ExtHdrFragment", "GRE") => &["nh"],
        ("IPv6ExtHdrFragment", "ICMPv6MLDone") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrFragment", "ICMPv6MLQuery") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrFragment", "ICMPv6MLReport") => &["hlim", "nh"],
        ("IPv6ExtHdrFragment", "ICMPv6MLReport2") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrFragment", "ICMPv6ND_NA") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrFragment", "ICMPv6ND_NS") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrFragment", "ICMPv6ND_RA") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrFragment", "ICMPv6ND_RS") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrFragment", "ICMPv6ND_Redirect") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrFragment", "IP") => &["nh"],
        ("IPv6ExtHdrFragment", "IPv6") => &["nh"],
        ("IPv6ExtHdrFragment", "IPv6ExtHdrDestOpt") => &["nh"],
        ("IPv6ExtHdrFragment", "IPv6ExtHdrFragment") => &["nh"],
        ("IPv6ExtHdrFragment", "IPv6ExtHdrHopByHop") => &["nh"],
        ("IPv6ExtHdrFragment", "IPv6ExtHdrRouting") => &["nh"],
        ("IPv6ExtHdrFragment", "SCTP") => &["nh"],
        ("IPv6ExtHdrFragment", "TCP") => &["nh"],
        ("IPv6ExtHdrFragment", "UDP") => &["nh"],
        ("IPv6ExtHdrHopByHop", "AH") => &["nh"],
        ("IPv6ExtHdrHopByHop", "ESP") => &["nh"],
        ("IPv6ExtHdrHopByHop", "GRE") => &["nh"],
        ("IPv6ExtHdrHopByHop", "ICMPv6MLDone") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrHopByHop", "ICMPv6MLQuery") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrHopByHop", "ICMPv6MLReport") => &["hlim", "nh"],
        ("IPv6ExtHdrHopByHop", "ICMPv6MLReport2") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrHopByHop", "ICMPv6ND_NA") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrHopByHop", "ICMPv6ND_NS") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrHopByHop", "ICMPv6ND_RA") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrHopByHop", "ICMPv6ND_RS") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrHopByHop", "ICMPv6ND_Redirect") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrHopByHop", "IP") => &["nh"],
        ("IPv6ExtHdrHopByHop", "IPv6") => &["nh"],
        ("IPv6ExtHdrHopByHop", "IPv6ExtHdrDestOpt") => &["nh"],
        ("IPv6ExtHdrHopByHop", "IPv6ExtHdrFragment") => &["nh"],
        ("IPv6ExtHdrHopByHop", "IPv6ExtHdrHopByHop") => &["nh"],
        ("IPv6ExtHdrHopByHop", "IPv6ExtHdrRouting") => &["nh"],
        ("IPv6ExtHdrHopByHop", "SCTP") => &["nh"],
        ("IPv6ExtHdrHopByHop", "TCP") => &["nh"],
        ("IPv6ExtHdrHopByHop", "UDP") => &["nh"],
        ("IPv6ExtHdrRouting", "AH") => &["nh"],
        ("IPv6ExtHdrRouting", "ESP") => &["nh"],
        ("IPv6ExtHdrRouting", "GRE") => &["nh"],
        ("IPv6ExtHdrRouting", "ICMPv6MLDone") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrRouting", "ICMPv6MLQuery") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrRouting", "ICMPv6MLReport") => &["hlim", "nh"],
        ("IPv6ExtHdrRouting", "ICMPv6MLReport2") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrRouting", "ICMPv6ND_NA") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrRouting", "ICMPv6ND_NS") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrRouting", "ICMPv6ND_RA") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrRouting", "ICMPv6ND_RS") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrRouting", "ICMPv6ND_Redirect") => &["dst", "hlim", "nh"],
        ("IPv6ExtHdrRouting", "IP") => &["nh"],
        ("IPv6ExtHdrRouting", "IPv6") => &["nh"],
        ("IPv6ExtHdrRouting", "IPv6ExtHdrDestOpt") => &["nh"],
        ("IPv6ExtHdrRouting", "IPv6ExtHdrFragment") => &["nh"],
        ("IPv6ExtHdrRouting", "IPv6ExtHdrHopByHop") => &["nh"],
        ("IPv6ExtHdrRouting", "IPv6ExtHdrRouting") => &["nh"],
        ("IPv6ExtHdrRouting", "SCTP") => &["nh"],
        ("IPv6ExtHdrRouting", "TCP") => &["nh"],
        ("IPv6ExtHdrRouting", "UDP") => &["nh"],
        ("LLC", "SNAP") => &["ctrl", "dsap", "ssap"],
        ("LLC", "STP") => &["ctrl", "dsap", "ssap"],
        ("Loopback", "IP") => &["type"],
        ("Loopback", "IPv6") => &["type"],
        ("PPP", "IP") => &["proto"],
        ("PPP", "IPv6") => &["proto"],
        ("PPPoE", "PPP") => &["code"],
        ("PPPoED", "PPP") => &["code"],
        ("SNAP", "ARP") => &["code"],
        ("SNAP", "Dot1Q") => &["code"],
        ("SNAP", "Ether") => &["code"],
        ("SNAP", "IP") => &["code"],
        ("SNAP", "IPv6") => &["code"],
        ("SNAP", "STP") => &["code"],
        ("TCP", "DNS") => &["sport"],
        ("TCP", "LDAP") => &["dport", "sport"],
        ("TCP", "NBTSession") => &["dport", "sport"],
        ("UDP", "BOOTP") => &["dport", "sport"],
        ("UDP", "DHCP6") => &["dport", "sport"],
        ("UDP", "DNS") => &["sport"],
        ("UDP", "ESP") => &["dport", "sport"],
        ("UDP", "GRE") => &["dport"],
        ("UDP", "HSRP") => &["dport", "sport"],
        ("UDP", "NTP") => &["dport", "sport"],
        ("UDP", "RIP") => &["dport", "sport"],
        ("UDP", "Radius") => &["dport", "sport"],
        ("UDP", "SNMP") => &["dport", "sport"],
        ("UDP", "TFTP") => &["dport"],
        ("UDP", "VXLAN") => &["dport", "sport"],
        ("VXLAN", "Ether") => &["NextProtocol", "flags"],
        ("VXLAN", "IP") => &["NextProtocol", "flags"],
        ("VXLAN", "IPv6") => &["NextProtocol", "flags"],
        _ => &[],
    }
}

/// scapy's `Packet.name`, which is what `show()` prints and is
/// not always the class name `summary()` prints.
pub fn display_name(layer: &str) -> &str {
    match layer {
        "CookedLinux" => "cooked linux",
        "CookedLinuxV2" => "cooked linux v2",
        "DHCP" => "DHCP options",
        "DHCP6" => "DHCPv6 Generic Message",
        "DNSQR" => "DNS Question Record",
        "DNSRR" => "DNS Resource Record",
        "Dot11" => "802.11",
        "Dot11AssoReq" => "802.11 Association Request",
        "Dot11AssoResp" => "802.11 Association Response",
        "Dot11Auth" => "802.11 Authentication",
        "Dot11Beacon" => "802.11 Beacon",
        "Dot11ProbeReq" => "802.11 Probe Request",
        "Dot11ProbeResp" => "802.11 Probe Response",
        "Dot1Q" => "802.1Q",
        "Ether" => "Ethernet",
        "ICMPv6MLDone" => "MLD - Multicast Listener Done",
        "ICMPv6MLQuery" => "MLD - Multicast Listener Query",
        "ICMPv6MLReport" => "MLD - Multicast Listener Report",
        "ICMPv6MLReport2" => "MLDv2 - Multicast Listener Report",
        "ICMPv6ND_NA" => "ICMPv6 Neighbor Discovery - Neighbor Advertisement",
        "ICMPv6ND_NS" => "ICMPv6 Neighbor Discovery - Neighbor Solicitation",
        "ICMPv6ND_RA" => "ICMPv6 Neighbor Discovery - Router Advertisement",
        "ICMPv6ND_RS" => "ICMPv6 Neighbor Discovery - Router Solicitation",
        "ICMPv6ND_Redirect" => "ICMPv6 Neighbor Discovery - Redirect",
        "IPv6ExtHdrDestOpt" => "IPv6 Extension Header - Destination Options Header",
        "IPv6ExtHdrFragment" => "IPv6 Extension Header - Fragmentation header",
        "IPv6ExtHdrHopByHop" => "IPv6 Extension Header - Hop-by-Hop Options Header",
        "IPv6ExtHdrRouting" => "IPv6 Option Header Routing",
        "NBTSession" => "NBT Session Packet",
        "NetflowHeaderV5" => "Netflow Header v5",
        "NetflowHeaderV9" => "Netflow Header V9",
        "PPP" => "PPP Link Layer",
        "PPPoE" => "PPP over Ethernet",
        "PPPoED" => "PPP over Ethernet Discovery",
        "RIP" => "RIP header",
        "Radius" => "RADIUS",
        "SMB2_Header" => "SMB2 Header",
        "STP" => "Spanning Tree Protocol",
        "TFTP" => "TFTP opcode",
        other => other,
    }
}
