"""Generate wiry protocol layers from declarative specs.

Run:  python dev/protogen/protogen.py            # write the tree
      python dev/protogen/protogen.py --check    # fail if anything would change

One TOML file per protocol in dev/protogen/specs/ describes the field table and
the dispatch bindings. This emits crates/wiry-core/src/layers/<module>.rs, the
generated dispatch table, and the registration edits in proto.rs and
layers/mod.rs. Regions marked `protogen:hand` and `protogen:tests` inside a
generated file are read back and preserved, so hand-written hooks and test
vectors survive regeneration.

See README.md in this directory for the spec format and the reasoning.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SPECS = Path(__file__).resolve().parent / "specs"
LAYERS = ROOT / "crates" / "wiry-core" / "src" / "layers"
PROTO_RS = ROOT / "crates" / "wiry-core" / "src" / "proto.rs"
MOD_RS = LAYERS / "mod.rs"

BANNER = "Generated by dev/protogen from dev/protogen/specs/{spec}. Field layouts\n//! come from the RFC cited above; edit the spec, not this file."

KINDS = {
    "uint": "FieldDesc::uint({name}, {off}, {len}, {default})",
    "le_uint": "FieldDesc::le_uint({name}, {off}, {len}, {default})",
    "computed": "FieldDesc::computed_uint({name}, {off}, {len})",
    "ipv4": "FieldDesc::ipv4({name}, {off}, {default})",
    "ipv6": "FieldDesc::ipv6({name}, {off})",
    "mac": "FieldDesc::mac({name}, {off})",
    "flags": "FieldDesc::flags({name}, {off}, {len}, {flags})",
    "bytes": "FieldDesc::bytes({name}, {off}, {len})",
    "var_bytes": "FieldDesc::var_bytes({name}, {off})",
    "var_bytes_to_end": "FieldDesc::var_bytes_to_end({name}, {off})",
}

FIXED_BITS = {"ipv4": 32, "ipv6": 128, "mac": 48}

PARENT_KINDS = {
    "ethertype": ("by_ethertype", "u16"),
    "ipproto": ("by_ipproto", "u8"),
    "udp_port": ("by_udp_port", "u16"),
    "tcp_port": ("by_tcp_port", "u16"),
    "llc_sap": ("by_llc_sap", "u8"),
    "icmpv6_type": ("by_icmpv6_type", "u8"),
}


class SpecError(Exception):
    pass


# --------------------------------------------------------------------------
# spec loading and validation


def builtin_count() -> int:
    m = re.search(r"BUILTIN_COUNT: u16 = (\d+);", PROTO_RS.read_text())
    if not m:
        raise SpecError("BUILTIN_COUNT not found in proto.rs")
    return int(m.group(1))


def load_specs() -> list[dict]:
    out = []
    for path in sorted(SPECS.glob("*.toml")):
        with path.open("rb") as f:
            spec = tomllib.load(f)
        spec["_file"] = path.name
        spec["module"] = spec.get("module", path.stem)
        validate(spec)
        out.append(spec)
    limit = builtin_count()
    seen: dict[int, str] = {}
    names: dict[str, str] = {}
    for s in out:
        n = s["num"]
        # At or above the count, `ProtoId::is_registered` sends the id to the
        # Python-declared registry and `desc` answers Raw for it.
        if n >= limit:
            raise SpecError(
                f"{s['_file']}: ProtoId {n} is at or past BUILTIN_COUNT "
                f"({limit}); raise it in proto.rs first"
            )
        if n in seen:
            raise SpecError(f"{s['_file']}: ProtoId {n} already taken by {seen[n]}")
        seen[n] = s["_file"]
        if s["name"] in names:
            raise SpecError(f"{s['_file']}: layer name {s['name']} already taken")
        names[s["name"]] = s["_file"]
    return out


def validate_group(f: str, g: dict, nested: bool) -> None:
    """A repeating group: DEVIATIONS E1's escape from the flat table. Every
    refusal here is a layout the walk would read wrongly rather than fail on."""
    if not g.get("name"):
        raise SpecError(f"{f}: [group] needs a name")
    fields = g.get("fields") or []
    if not fields:
        raise SpecError(f"{f}: group {g['name']!r} needs at least one field")
    extent = g.get("extent", "rest")
    if extent not in ("rest", "count", "length"):
        raise SpecError(
            f"{f}: group {g['name']!r} extent must be \"count\", \"length\" or \"rest\""
        )
    if extent == "count" and ("count_off" not in g or "count_len" not in g):
        raise SpecError(f"{f}: a count-driven group needs count_off and count_len")
    if extent == "length" and ("len_off" not in g or "len_len" not in g):
        raise SpecError(f"{f}: a length-driven group needs len_off and len_len")
    fixed = g.get("elem_len")
    if (fixed is None) == (g.get("elem_base") is None):
        raise SpecError(
            f"{f}: group {g['name']!r} needs exactly one of elem_len and elem_base"
        )
    if fixed is None and not g.get("terms"):
        raise SpecError(f"{f}: a computed element length needs [[...terms]]")
    for i, fd in enumerate(fields):
        kind = fd.get("kind", "uint")
        if kind not in KINDS:
            raise SpecError(f"{f}: group field {fd.get('name')!r} has kind {kind!r}")
        if "name" not in fd or "off" not in fd:
            raise SpecError(f"{f}: a group field needs a name and an off")
        if kind in FIXED_BITS:
            fd["len"] = FIXED_BITS[kind]
        if kind.startswith("var_"):
            # It reads to the end of the element, so a field after it would be
            # inside it, and a fixed element width leaves it nothing to cover.
            if i != len(fields) - 1:
                raise SpecError(
                    f"{f}: group field {fd['name']!r} is variable-length "
                    "and must come last"
                )
            if fixed is not None:
                raise SpecError(
                    f"{f}: group field {fd['name']!r} is variable-length, so "
                    f"group {g['name']!r} needs elem_base rather than elem_len"
                )
            fd["len"] = 0
            continue
        if "len" not in fd:
            raise SpecError(f"{f}: group field {fd['name']!r} needs a bit length")
        if fixed is not None and fd["off"] + fd["len"] > fixed * 8:
            raise SpecError(
                f"{f}: group field {fd['name']!r} ends past the "
                f"{fixed}-octet element"
            )
    if nested and g.get("nested"):
        raise SpecError(
            f"{f}: group {g['name']!r} nests a group inside a nested one; "
            "the walk descends exactly one level"
        )
    if g.get("nested"):
        validate_group(f, g["nested"], True)


def validate(s: dict) -> None:
    f = s["_file"]

    def need(key):
        if not s.get(key):
            raise SpecError(f"{f}: missing required key {key!r}")

    # The provenance rule is enforced here rather than left to convention:
    # a layer with no RFC or registry citation does not generate.
    need("citation")
    for k in ("name", "id", "num"):
        need(k)
    if not re.fullmatch(r"[A-Z][A-Za-z0-9]*", s["id"]):
        raise SpecError(f"{f}: id {s['id']!r} must be a Rust-style CamelCase name")

    fields = s.get("fields") or []
    if not fields:
        raise SpecError(f"{f}: a layer needs at least one field")

    hl = s.get("header_len")
    fixed_hl = hl if isinstance(hl, int) else None
    prev_end = -1
    for i, fd in enumerate(fields):
        kind = fd.get("kind", "uint")
        if kind not in KINDS:
            raise SpecError(f"{f}: field {fd.get('name')!r} has unknown kind {kind!r}")
        if "name" not in fd or "off" not in fd:
            raise SpecError(f"{f}: field {i} needs a name and an off")
        if kind in FIXED_BITS:
            fd["len"] = FIXED_BITS[kind]
        if kind.startswith("var_"):
            if i != len(fields) - 1:
                raise SpecError(
                    f"{f}: {fd['name']!r} is variable-length and must come last"
                )
            fd["len"] = 0
        elif "len" not in fd:
            raise SpecError(f"{f}: field {fd['name']!r} needs a bit length")
        if kind == "flags":
            names = fd.get("flags")
            if not names:
                raise SpecError(f"{f}: flags field {fd['name']!r} needs flag names")
            if len(names) > fd["len"]:
                raise SpecError(
                    f"{f}: {fd['name']!r} names {len(names)} flags in {fd['len']} bits"
                )
        off, ln = fd["off"], fd["len"]
        if not fd.get("when") and not fd.get("overlaps") and off < prev_end:
            raise SpecError(
                f"{f}: {fd['name']!r} at bit {off} overlaps the field before it; "
                "give it a `when` condition or set overlaps = true if that is real"
            )
        prev_end = max(prev_end, off + ln)
        if fixed_hl is not None and not kind.startswith("var_"):
            if off + ln > fixed_hl * 8:
                raise SpecError(
                    f"{f}: {fd['name']!r} ends at bit {off + ln}, past the "
                    f"{fixed_hl}-octet header; the flat model cannot place it. "
                    "Use header_len = \"hand\" and a hand-written hook."
                )

    if isinstance(hl, str) and hl not in ("hand", "rest"):
        raise SpecError(f"{f}: header_len must be an integer, \"rest\" or \"hand\"")
    if hl is None:
        raise SpecError(f"{f}: header_len is required")

    nx = s.get("next")
    if isinstance(nx, str) and nx not in ("hand", "raw", "end"):
        raise SpecError(f"{f}: next must be \"raw\", \"end\", \"hand\" or a table")
    if isinstance(nx, dict):
        if "off" not in nx or "len" not in nx:
            raise SpecError(f"{f}: [next] needs off and len")
        for arm in nx.get("arms", []):
            if "value" not in arm or "proto" not in arm:
                raise SpecError(f"{f}: every [[next.arms]] needs a value and a proto")

    g = s.get("group")
    if g:
        validate_group(f, g, False)
        # The region has to sit inside the header, because that is the slice a
        # walk is handed; a fixed header length ends before it.
        if isinstance(hl, int):
            raise SpecError(
                f"{f}: a group needs header_len \"rest\" or \"hand\", so the "
                "elements are inside the header the walk is handed"
            )
        if not s.get("parsed_field"):
            raise SpecError(f"{f}: a group needs parsed_field, the name it answers under")
        tail = fields[-1]
        if tail.get("kind") != "var_bytes" or tail["name"] != s["parsed_field"]:
            raise SpecError(
                f"{f}: the last field must be a var_bytes named "
                f"{s['parsed_field']!r}, so the region is in the field table too"
            )
        if tail["off"] != g.get("start", 0) * 8:
            raise SpecError(
                f"{f}: group start {g.get('start', 0)} and field "
                f"{tail['name']!r} at bit {tail['off']} disagree"
            )
        # Construction lays the region down straight after `build_len` and pads
        # any gap; a template longer than the start would overlap it instead.
        build_len = s.get("build_len", s.get("min_len", 0))
        if build_len > g.get("start", 0):
            raise SpecError(
                f"{f}: build_len {build_len} runs past the group's start "
                f"{g.get('start', 0)}, so a built region would overlap the "
                "fixed header; set build_len to the start"
            )

    for p in s.get("parents", []):
        if p.get("from") not in PARENT_KINDS:
            raise SpecError(
                f"{f}: parent kind {p.get('from')!r} unknown; "
                f"one of {sorted(PARENT_KINDS)}"
            )
        if not p.get("values"):
            raise SpecError(f"{f}: parent {p['from']} needs values")
        # Only a port selector is handed the payload, so a guard anywhere else
        # would be accepted and then never consulted.
        if p.get("guard") and not p["from"].endswith("_port"):
            raise SpecError(
                f"{f}: a guard is only consulted on a port selector, not on "
                f"{p['from']}"
            )


# --------------------------------------------------------------------------
# rendering


def rs_str(v: str) -> str:
    return '"' + v.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_field(fd: dict) -> str:
    kind = fd.get("kind", "uint")
    expr = KINDS[kind].format(
        name=rs_str(fd["name"]),
        off=fd["off"],
        len=fd.get("len", 0),
        default=fd.get("default", 0),
        flags="&[" + ", ".join(rs_str(x) for x in fd.get("flags", [])) + "]",
    )
    if kind == "flags" and fd.get("default"):
        expr += f".with_default({fd['default']})"
    if fd.get("default_bytes"):
        b = ", ".join(str(x) for x in fd["default_bytes"])
        expr += f".defaulting_to(&[{b}])"
    if fd.get("when"):
        expr += f".when({fd['when']})"
    return f"    {expr},"


def hand_region(existing: str, tag: str, seed: str, where: str) -> str:
    """Hand-written code survives regeneration; that is the escape hatch. An
    empty region counts as nothing written yet, so it takes the seed.

    A half-present or duplicated pair of markers is refused rather than
    re-seeded: the region is the only copy of the code inside it, and a bad
    merge that damages one marker would otherwise delete it silently."""
    begin, end = f"// protogen:{tag} begin", f"// protogen:{tag} end"
    text = existing or ""
    nb, ne = text.count(begin), text.count(end)
    if (nb, ne) == (0, 0):
        return f"{begin}\n{seed}{end}"
    if nb != 1 or ne != 1 or text.index(end) < text.index(begin):
        raise SpecError(
            f"{where}: the protogen:{tag} markers are damaged "
            f"({nb} begin, {ne} end); repair them by hand, because the code "
            "between them is not recoverable from the spec"
        )
    m = re.search(re.escape(begin) + r"(.*?)" + re.escape(end), text, re.S)
    return m.group(0) if m.group(1).strip() else f"{begin}\n{seed}{end}"


def next_hook(s: dict) -> str:
    """The name `DESC.next` points at. The two trivial cases are shared out of
    `proto.rs` rather than redefined in sixty modules."""
    nx = s.get("next", "raw")
    if nx == "end":
        return "crate::proto::next_end"
    if nx == "raw" or nx is None:
        return "crate::proto::next_raw"
    return "next"


def render_next(s: dict) -> str:
    nx = s.get("next", "raw")
    if not isinstance(nx, dict):
        return ""
    off, ln = nx["off"], nx["len"]
    need = (off + ln + 7) // 8
    fallback = nx.get("fallback", "raw")
    fb = "Next::End" if fallback == "end" else "Next::Raw"
    arms = "\n".join(
        f"        {arm['value']} => Next::Proto(ProtoId::{arm['proto']}),"
        for arm in nx.get("arms", [])
    )
    guard = "hdr.is_empty()" if need == 1 else f"hdr.len() < {need}"
    body = (
        "fn next(hdr: &[u8]) -> Next {\n"
        f"    if {guard} {{\n        return {fb};\n    }}\n"
        f"    match crate::field::read_bits(hdr, {off}, {ln}) {{\n"
        f"{arms}\n"
        f"        _ => {fb},\n"
        "    }\n"
        "}\n"
    )
    return body


def render_bind_next(s: dict) -> str:
    nx = s.get("next")
    if not isinstance(nx, dict) or not nx.get("bind", True):
        return ""
    arms = [a for a in nx.get("arms", []) if a.get("bind", True)]
    if not arms:
        return ""
    off, ln = nx["off"], nx["len"]
    need = (off + ln + 7) // 8
    body = ["fn bind_next(hdr: &mut [u8], p: ProtoId) {", "    let v = match p {"]
    for a in arms:
        body.append(f"        ProtoId::{a['proto']} => {a['value']},")
    body.append("        _ => return,")
    body.append("    };")
    body.append(f"    if hdr.len() >= {need} {{")
    body.append(f"        crate::field::write_bits(hdr, {off}, {ln}, v);")
    body.append("    }")
    body.append("}")
    return "\n".join(body) + "\n"


def header_len_hook(s: dict) -> str:
    return "crate::proto::header_len_rest" if s["header_len"] == "rest" else "header_len"


def render_header_len(s: dict) -> str:
    hl = s["header_len"]
    if hl in ("hand", "rest"):
        return ""
    return f"fn header_len(_: &[u8]) -> usize {{\n    {hl}\n}}\n"


def opt_hook(s: dict, key: str) -> str:
    v = s.get(key)
    if v is None:
        return "None"
    return f"Some({key})" if v == "hand" else f"Some({v})"


def group_chain(g: dict) -> list[dict]:
    return [g] + (group_chain(g["nested"]) if g.get("nested") else [])


def render_extent(g: dict) -> str:
    extent = g.get("extent", "rest")
    if extent == "count":
        return (
            "Extent::Count { bit_off: "
            f"{g['count_off']}, bit_len: {g['count_len']} }}"
        )
    if extent == "length":
        return (
            "Extent::Length { bit_off: "
            f"{g['len_off']}, bit_len: {g['len_len']}, "
            f"scale: {g.get('len_scale', 1)}, covers: {g.get('len_covers', 0)} }}"
        )
    return "Extent::Rest"


def render_elem_len(g: dict) -> str:
    if g.get("elem_len") is not None:
        return f"ElemLen::Fixed({g['elem_len']})"
    terms = ", ".join(
        "LenTerm { bit_off: "
        f"{t['off']}, bit_len: {t['len']}, scale: {t.get('scale', 1)} }}"
        for t in g["terms"]
    )
    return (
        f"ElemLen::Computed {{ base: {g['elem_base']}, terms: &[{terms}], "
        f"min: {g.get('elem_min', 0)} }}"
    )


def render_group(g: dict, const: str, vis: str) -> list[str]:
    """One group, plus its nested group ahead of it so the reference resolves."""
    out: list[str] = []
    if g.get("nested"):
        out += render_group(g["nested"], f"{const}_NESTED", "static")
        out.append("")
    out.append(f"{vis} {const}_FIELDS: &[FieldDesc] = &[")
    for fd in g["fields"]:
        out.append(render_field(fd))
    out.append("];")
    out.append("")
    tail = ""
    if g.get("align", 1) != 1:
        tail += f".aligned({g['align']})"
    if g.get("nested"):
        tail += f".nesting(&{const}_NESTED)"
    if g.get("when"):
        tail += f".when({g['when']})"
    out.append(f"{vis} {const}: GroupDesc = GroupDesc::new(")
    out.append(f"    {rs_str(g['name'])},")
    out.append(f"    {const}_FIELDS,")
    out.append(f"    {render_elem_len(g)},")
    out.append(f"    {render_extent(g)},")
    out.append(f"    {g.get('start', 0)},")
    out.append(f"){tail};")
    return out


def render_provenance(s: dict) -> list[str]:
    """GPL-2.0 §2(a) attribution for a table taken from scapy. NOTICE defines
    the shape; absence of a block is a claim that the file is wiry's own work,
    so it is emitted only where the spec declares a source."""
    pr = s.get("provenance")
    if not pr:
        return []
    for k in ("source", "version", "changed"):
        if not pr.get(k):
            raise SpecError(f"{s['_file']}: [provenance] needs {k!r}")
    out = [
        "// SPDX-License-Identifier: GPL-2.0-only",
        "//",
        f"// Derived from scapy: {pr['source']}",
        f"//   {pr['version']}",
        "//   Copyright (C) Philippe Biondi and the scapy contributors",
        "//",
        "// Changed by the wiry authors:",
    ]
    changed = pr["changed"]
    for line in ([changed] if isinstance(changed, str) else changed):
        out.append(f"//   {line}")
    out.append("")
    return out


def render_layer(s: dict, existing: str) -> str:
    hl = s["header_len"]
    fixed = hl if isinstance(hl, int) else None
    min_len = s.get("min_len", fixed if fixed is not None else 0)
    build_len = s.get("build_len", fixed if fixed is not None else min_len)

    lines = render_provenance(s)
    for line in s["citation"].strip().splitlines():
        lines.append(("//! " + line).rstrip())
    lines.append("//!")
    lines.append("//! " + BANNER.format(spec=s["_file"]))
    lines.append("")
    bind = render_bind_next(s)
    hooks = [render_header_len(s), render_next(s), bind]
    # `Next` is named only by a hook this file defines; a shared one is reached
    # through its full path.
    names = ["ProtoDesc", "ProtoId"]
    if render_next(s) or s.get("next") == "hand":
        names.insert(0, "Next")

    lines.append("use crate::field::FieldDesc;")
    lines.append("use crate::proto::{" + ", ".join(names) + "};")
    if s.get("group"):
        used = ["ElemLen", "Extent", "GroupDesc"]
        if any(g.get("elem_base") is not None for g in group_chain(s["group"])):
            used.append("LenTerm")
        lines.append("use crate::repeat::{" + ", ".join(used) + "};")
    lines.append("")
    lines.append(hand_region(existing, "hand", "", s["_file"]))
    lines.append("")
    lines.append("pub static FIELDS: &[FieldDesc] = &[")
    for fd in s["fields"]:
        lines.append(render_field(fd))
    lines.append("];")
    lines.append("")
    if s.get("group"):
        lines += render_group(s["group"], "GROUP", "pub static")
        lines.append("")
    for chunk in hooks:
        if chunk:
            lines.append(chunk.rstrip())
            lines.append("")

    lines.append("pub static DESC: ProtoDesc = ProtoDesc {")
    lines.append(f"    id: ProtoId::{s['id']},")
    lines.append(f"    name: {rs_str(s['name'])},")
    lines.append("    fields: FIELDS,")
    lines.append(f"    min_len: {min_len},")
    for key, hook in (("header_len", header_len_hook(s)), ("next", next_hook(s))):
        lines.append(f"    {key}," if hook == key else f"    {key}: {hook},")
    lines.append(f"    build_len: {build_len},")
    lines.append(f"    parse_options: {opt_hook(s, 'parse_options')},")
    lines.append(f"    opt_table: {opt_hook(s, 'opt_table')},")
    lines.append(f"    set_hlen: {opt_hook(s, 'set_hlen')},")
    bn = "Some(bind_next)" if (bind or s.get("bind_next") == "hand") else "None"
    lines.append(f"    bind_next: {bn},")
    lines.append(f"    bind_next_bytes: {opt_hook(s, 'bind_next_bytes')},")
    lines.append(f"    content_len: {opt_hook(s, 'content_len')},")
    lines.append("};")
    lines.append("")
    lines.append("#[cfg(test)]")
    lines.append("mod tests {")
    lines.append("    #![allow(unused_imports)]")
    lines.append("    use super::*;")
    lines.append("    use crate::field::FieldValue;")
    lines.append("    use crate::packet::Packet;")
    lines.append("")
    lines.append(test_region(s, existing))
    lines.append("}")
    return "\n".join(lines) + "\n"


def test_region(s: dict, existing: str) -> str:
    """Seeded once from the spec's hand-built RFC vector, then owned by hand."""
    vec = s.get("vector")
    seed = ""
    if vec:
        b = ", ".join(f"0x{x:02x}" for x in vec["bytes"])
        checks = []
        for name, want in (vec.get("fields") or {}).items():
            checks.append(
                f"        assert_eq!(p.get(l, {rs_str(name)}).unwrap(), "
                f"FieldValue::Uint({want}));"
            )
        bind = (
            f"        let l = p.find_layer(ProtoId::{s['id']}).unwrap();\n"
            if checks
            else f"        assert!(p.find_layer(ProtoId::{s['id']}).is_some());\n"
        )
        seed = (
            "    /// " + vec.get("source", s["citation"].splitlines()[0]).strip() + "\n"
            "    fn vector() -> Vec<u8> {\n"
            f"        vec![{b}]\n"
            "    }\n\n"
            "    #[test]\n"
            "    fn dissects_the_rfc_vector() {\n"
            f"        let p = Packet::dissect(vector(), ProtoId::{s['id']});\n"
            + bind
            + "\n".join(checks)
            + "\n        assert_eq!(p.raw_bytes(), &vector()[..]);\n"
            "    }\n\n"
            "    #[test]\n"
            "    fn truncation_does_not_panic() {\n"
            "        for n in 0..vector().len() {\n"
            f"            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::{s['id']});\n"
            "            assert_eq!(p.raw_bytes(), &vector()[..n]);\n"
            "        }\n"
            "    }\n\n"
            "    #[test]\n"
            "    fn writes_survive_a_rebuild() {\n"
            f"        let mut p = Packet::dissect(vector(), ProtoId::{s['id']});\n"
            f"        let l = p.find_layer(ProtoId::{s['id']}).unwrap();\n"
            "        let n = p.raw_bytes().len();\n"
            f"        for f in crate::proto::active_fields(ProtoId::{s['id']}, false, p.header(l))\n"
            "            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)\n"
            "            .map(|f| f.name)\n"
            "            .collect::<Vec<_>>()\n"
            "        {\n"
            "            p.set_uint(l, f, 1);\n"
            "        }\n"
            "        assert_eq!(p.to_bytes().len(), n);\n"
            "    }\n"
        )
    return hand_region(existing, "tests", seed, s["_file"])


# --------------------------------------------------------------------------
# dispatch table


def render_dispatch(specs: list[dict]) -> str:
    by_kind: dict[str, list[tuple[dict, dict]]] = {k: [] for k in PARENT_KINDS}
    for s in specs:
        for p in s.get("parents", []):
            by_kind[p["from"]].append((s, p))

    out = [
        "//! Where every generated layer is reached from, and what to write back",
        "//! when one is stacked. Values come from the IANA registry or the RFC",
        "//! cited in each layer's module.",
        "//!",
        "//! " + BANNER.format(spec="*.toml"),
        "",
        "use crate::proto::ProtoId;",
        "",
    ]

    if any(by_kind[k] for k in PARENT_KINDS if k.endswith("_port")):
        out += [
            "const fn port_bits<const N: usize>(ports: &[u16]) -> [u64; N] {",
            "    let mut bits = [0u64; N];",
            "    let mut i = 0;",
            "    while i < ports.len() {",
            "        bits[(ports[i] >> 6) as usize] |= 1u64 << (ports[i] & 63);",
            "        i += 1;",
            "    }",
            "    bits",
            "}",
            "",
            "/// The table is sized to the largest claimed port, so a port past its end",
            "/// is unclaimed by construction.",
            "#[inline]",
            "fn claimed(bits: &[u64], v: u16) -> bool {",
            "    let i = (v >> 6) as usize;",
            "    i < bits.len() && bits[i] & (1u64 << (v & 63)) != 0",
            "}",
            "",
        ]

    def arms_for(entries, guarded: bool) -> list[str]:
        """Two protocols may share a selector — NetFlow v5, v9 and IPFIX all
        arrive on UDP 2055 — so candidates are grouped by value and each one's
        guard decides in turn."""
        by_value: dict[int, list[tuple[dict, dict]]] = {}
        for s, p in entries:
            for v in p["values"]:
                by_value.setdefault(v, []).append((s, p))
        groups: dict[tuple, list[int]] = {}
        for v in sorted(by_value):
            key = tuple((s["id"], p.get("guard")) for s, p in by_value[v])
            groups.setdefault(key, []).append(v)
        arms = []
        for key, vals in sorted(groups.items(), key=lambda kv: kv[1][0]):
            pat = " | ".join(str(v) for v in vals)
            cands = [
                (pid, g if guarded else None) for pid, g in key
            ]
            if len(cands) == 1 and cands[0][1] is None:
                arms.append(f"        {pat} => Some(ProtoId::{cands[0][0]}),")
            elif len(cands) == 1:
                arms.append(
                    f"        {pat} => {cands[0][1]}(payload)"
                    f".then_some(ProtoId::{cands[0][0]}),"
                )
            else:
                arms.append(f"        {pat} => {{")
                for pid, guard in cands:
                    if guard:
                        arms.append(f"            if {guard}(payload) {{")
                        arms.append(f"                return Some(ProtoId::{pid});")
                        arms.append("            }")
                    else:
                        arms.append(f"            Some(ProtoId::{pid})")
                if all(g for _, g in cands):
                    arms.append("            None")
                arms.append("        }")
        return arms

    tests: list[str] = []
    gates: list[tuple[str, str]] = []

    for kind, (fname, ty) in PARENT_KINDS.items():
        entries = by_kind[kind]
        is_port = kind.endswith("_port")
        if not entries:
            body = "    None\n"
            if is_port:
                out.append("#[inline]")
                out.append(
                    f"pub fn {fname}(_sport: {ty}, _dport: {ty}, _payload: &[u8])"
                    " -> Option<ProtoId> {"
                )
            else:
                out.append("#[inline]")
                out.append(f"pub fn {fname}(_v: {ty}) -> Option<ProtoId> {{")
            out.append(body.rstrip())
            out.append("}")
            out.append("")
            continue

        if is_port:
            if ty != "u16":
                raise SpecError(f"{kind}: the port bitmap is u16-only")
            inner = f"{fname}_one"
            values = f"{kind.upper()}_VALUES"
            bits = f"{kind.upper()}_CLAIMED"
            arms = arms_for(entries, True)
            used = any("payload" in a for a in arms)
            ports = sorted({v for _, p in entries for v in p["values"]})
            out += [
                f"const {values}: &[u16] = &[" + ", ".join(str(v) for v in ports) + "];",
                "",
                f"static {bits}: [u64; {(ports[-1] >> 6) + 1}] = port_bits({values});",
                "",
                "// Out of line: almost no traffic claims a layer here, so the match",
                "// must not weigh on the callers that never reach it.",
                "#[inline(never)]",
                f"fn {inner}(v: {ty}, {'payload' if used else '_payload'}: &[u8])"
                " -> Option<ProtoId> {",
                "    match v {",
                *arms,
                "        _ => None,",
                "    }",
                "}",
                "",
                "/// The destination port names the service, so it is asked first.",
                "#[inline]",
                f"pub fn {fname}(sport: {ty}, dport: {ty}, payload: &[u8])"
                " -> Option<ProtoId> {",
                f"    if !claimed(&{bits}, dport) && !claimed(&{bits}, sport) {{",
                "        return None;",
                "    }",
                f"    {inner}(dport, payload).or_else(|| {inner}(sport, payload))",
                "}",
                "",
            ]
            tests += [
                "    #[test]",
                f"    fn {kind}_bitmap_agrees_with_the_match() {{",
                f"        for v in 0..={ty}::MAX {{",
                f"            let c = super::claimed(&super::{bits}, v);",
                f"            assert_eq!(c, super::{values}.contains(&v), \"{kind} {{v}}\");",
                "            for p in PROBES {",
                f"                assert!(c || super::{inner}(v, p).is_none(),",
                f"                    \"{kind} {{v}} dispatches past the bitmap\");",
                "            }",
                "        }",
                "    }",
                "",
            ]
        else:
            out.append("#[inline]")
            out.append(f"pub fn {fname}(v: {ty}) -> Option<ProtoId> {{")
            out.append("    match v {")
            out.extend(arms_for(entries, False))
            out.append("        _ => None,")
            out.append("    }")
            out.append("}")
            out.append("")

        # Reverse direction: stacking a layer writes the parent's selector.
        rev = [
            (s, p)
            for s, p in entries
            if p.get("bind", p["values"][0]) is not False
        ]
        if rev:
            out.append("#[inline]")
            out.append(f"pub fn {fname}_of(p: ProtoId) -> Option<{ty}> {{")
            out.append("    match p {")
            seen = set()
            for s, p in rev:
                if s["id"] in seen:
                    continue
                seen.add(s["id"])
                v = p.get("bind", p["values"][0])
                out.append(f"        ProtoId::{s['id']} => Some({v}),")
            out.append("        _ => None,")
            out.append("    }")
            out.append("}")
            out.append("")
            if is_port:
                gates.append((fname, f"{kind.upper()}_CLAIMED"))
    if gates:
        tests += [
            "    /// The reverse map is what stacking a layer writes, so a port it",
            "    /// names that the gate does not claim would build a packet the",
            "    /// dissector cannot read back.",
            "    #[test]",
            "    fn every_bound_port_is_still_claimed() {",
            "        for id in crate::proto::builtins() {",
            *[
                f"            if let Some(v) = super::{fname}_of(id) {{\n"
                f"                assert!(super::claimed(&super::{bits}, v),"
                f' "{fname} {{v}}");\n'
                "            }"
                for fname, bits in gates
            ],
            "        }",
            "    }",
            "",
        ]
    if tests:
        out += [
            "#[cfg(test)]",
            "mod tests {",
            "    /// A guard that rejects every probe would hide a dropped bitmap bit,",
            "    /// so the probes have to reach as many arms as they can.",
            "    const PROBES: &[&[u8]] = &[",
            "        &[],",
            "        &[0u8; 64],",
            "        &[0xff; 64],",
            "        b\"GET / HTTP/1.1\\r\\nHost: h\\r\\n\\r\\n\",",
            "    ];",
            "",
            *tests,
            "}",
        ]
    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------
# registration edits


def splice(text: str, tag: str, body: str) -> str:
    begin, end = f"// protogen:{tag} begin", f"// protogen:{tag} end"
    pat = re.compile(
        r"([ \t]*)" + re.escape(begin) + r".*?[ \t]*" + re.escape(end), re.S
    )
    m = pat.search(text)
    if not m:
        raise SpecError(f"marker {tag!r} not found in the target file")
    indent = m.group(1)
    lines = [indent + begin]
    for line in body.splitlines():
        lines.append((indent + line).rstrip() if line else "")
    lines.append(indent + end)
    return pat.sub(lambda _: "\n".join(lines), text, count=1)


def render_registration(specs: list[dict]) -> dict[Path, list[tuple[str, str]]]:
    ids = "\n".join(
        f"pub const {s['id']}: ProtoId = ProtoId({s['num']});"
        for s in sorted(specs, key=lambda s: s["num"])
    )
    builtins = "\n".join(
        f"ProtoId::{s['id']}," for s in sorted(specs, key=lambda s: s["num"])
    )
    descs = "\n".join(
        f"t[ProtoId::{s['id']}.0 as usize] = &{s['module']}::DESC;"
        for s in sorted(specs, key=lambda s: s["num"])
    )
    acc = []
    for s in sorted(specs, key=lambda s: s["num"]):
        if s.get("accessors"):
            names = ", ".join(rs_str(a) for a in s["accessors"])
            acc.append(f"ProtoId::{s['id']} => &[{names}],")
    parsed = []
    groups = []
    for s in sorted(specs, key=lambda s: s["num"]):
        if s.get("parsed_field"):
            parsed.append(f"ProtoId::{s['id']} => {rs_str(s['parsed_field'])},")
        if s.get("group"):
            groups.append(
                f"ProtoId::{s['id']} => Some(&crate::layers::{s['module']}::GROUP),"
            )
    mods = "\n".join(
        f"pub mod {m};"
        for m in sorted({s["module"] for s in specs} | {"dispatch"})
    )
    return {
        PROTO_RS: [
            ("ids", ids),
            ("builtins", builtins),
            ("desc", descs),
            ("accessors", "\n".join(acc)),
            ("parsed", "\n".join(parsed)),
            ("groups", "\n".join(groups)),
        ],
        MOD_RS: [("mods", mods)],
    }


# --------------------------------------------------------------------------


def rustfmt(files: dict[Path, str]) -> dict[Path, str]:
    """CI runs `cargo fmt --check` over the generated tree, so the generator has
    to emit what rustfmt would. Without this the `--check` run and the format
    check contradict each other."""
    exe = shutil.which("rustfmt")
    if not exe:
        print("protogen: rustfmt not found; output left unformatted", file=sys.stderr)
        return files
    # Through stdin, so rustfmt does not try to resolve the `mod` lines in
    # layers/mod.rs against a directory that is not there. Run from the repo
    # root, which is where rustfmt.toml is found.
    out = {}
    for path, text in files.items():
        r = subprocess.run(
            [exe, "--edition", "2021", "--emit", "stdout"],
            input=text,
            capture_output=True,
            text=True,
            cwd=ROOT,
        )
        if r.returncode != 0:
            raise SpecError(f"rustfmt rejected {path.name}:\n{r.stderr}")
        out[path] = r.stdout
    return out


def generate() -> dict[Path, str]:
    specs = load_specs()
    out: dict[Path, str] = {}
    for s in specs:
        path = LAYERS / f"{s['module']}.rs"
        existing = path.read_text() if path.exists() else ""
        out[path] = render_layer(s, existing)
    out[LAYERS / "dispatch.rs"] = render_dispatch(specs)
    for path, regions in render_registration(specs).items():
        text = out.get(path, path.read_text())
        for tag, body in regions:
            text = splice(text, tag, body)
        out[path] = text
    return rustfmt(out)


def main(argv: list[str]) -> int:
    check = "--check" in argv
    try:
        files = generate()
    except SpecError as e:
        print(f"protogen: {e}", file=sys.stderr)
        return 2
    changed = []
    for path, text in sorted(files.items()):
        old = path.read_text() if path.exists() else None
        if old == text:
            continue
        changed.append(path.relative_to(ROOT))
        if not check:
            path.write_text(text)
    if check and changed:
        print("protogen: out of date, re-run dev/protogen/protogen.py:", file=sys.stderr)
        for p in changed:
            print(f"  {p}", file=sys.stderr)
        return 1
    print(f"protogen: {len(files)} files, {len(changed)} {'stale' if check else 'written'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
