"""Hand-built byte vectors and a pure-Python internet checksum.

Every vector below is laid out from the RFC / IEEE field diagram cited above it.
Nothing here is generated by running another packet library.
"""

import struct


def checksum(data: bytes) -> int:
    """Internet checksum, RFC 1071: one's complement of the one's complement
    sum of 16-bit big-endian words, odd trailing byte padded with zero."""
    if len(data) % 2:
        data += b"\x00"
    total = 0
    for i in range(0, len(data), 2):
        total += (data[i] << 8) | data[i + 1]
        total = (total & 0xFFFF) + (total >> 16)
    return (~total) & 0xFFFF


def pseudo_v4(src: bytes, dst: bytes, proto: int, length: int) -> bytes:
    """IPv4 transport pseudo-header (RFC 9293 3.1 / RFC 768)."""
    return src + dst + b"\x00" + bytes([proto]) + struct.pack("!H", length)


def pseudo_v6(src: bytes, dst: bytes, nh: int, length: int) -> bytes:
    """IPv6 upper-layer pseudo-header (RFC 8200 8.1)."""
    return src + dst + struct.pack("!I", length) + b"\x00\x00\x00" + bytes([nh])


# Ethernet II frame carrying IPv4 and TCP.
# IEEE 802.3 clause 3 framing, RFC 791 3.1 IPv4 header, RFC 9293 3.1 TCP header.
ETHER_IP_TCP = (
    b"\x00\x11\x22\x33\x44\x55"      # Ethernet destination
    b"\x66\x77\x88\x99\xaa\xbb"      # Ethernet source
    b"\x08\x00"                      # EtherType: IPv4
    b"\x45\x00\x00\x28"              # version 4, IHL 5, TOS 0, total length 40
    b"\x00\x01\x00\x00"              # identification 1, flags 0, frag offset 0
    b"\x40\x06\x00\x00"              # TTL 64, protocol 6 (TCP), checksum 0
    b"\x0a\x00\x00\x01"              # source 10.0.0.1
    b"\x0a\x00\x00\x02"              # destination 10.0.0.2
    b"\x1f\x90\x00\x50"              # source port 8080, destination port 80
    b"\x00\x00\x00\x01"              # sequence number 1
    b"\x00\x00\x00\x00"              # acknowledgement number 0
    b"\x50\x02\x20\x00"              # data offset 5, flags SYN, window 8192
    b"\x00\x00\x00\x00"              # checksum 0, urgent pointer 0
)

# Same frame with one 802.1Q tag: IEEE Std 802.1Q clause 9.
# TCI 0x6064 = PCP 3, DEI 0, VID 100.
VLAN_IP = (
    b"\x00\x11\x22\x33\x44\x55"
    b"\x66\x77\x88\x99\xaa\xbb"
    b"\x81\x00"                      # TPID 0x8100
    b"\x60\x64"                      # TCI: prio 3, id 0, vlan 100
    b"\x08\x00"                      # inner EtherType: IPv4
    b"\x45\x00\x00\x14"              # IPv4, total length 20
    b"\x00\x01\x00\x00"
    b"\x40\x06\x00\x00"
    b"\x0a\x00\x00\x01"
    b"\x0a\x00\x00\x02"
)

# ICMP Echo Request, RFC 792 Echo message diagram. The checksum is the
# hand-computed value for this message, so checksum(ICMP_ECHO) == 0.
ICMP_ECHO = (
    b"\x08\x00"                      # type 8 (echo request), code 0
    b"\x48\x2d"                      # checksum
    b"\x12\x34"                      # identifier
    b"\x00\x01"                      # sequence number
    b"\xde\xad\xbe\xef"              # payload
)

# ARP request, RFC 826 "Packet format": who-has 10.0.0.2, tell 10.0.0.1.
ARP_WHO_HAS = (
    b"\x00\x01"                      # hardware type: Ethernet
    b"\x08\x00"                      # protocol type: IPv4
    b"\x06"                          # hardware address length
    b"\x04"                          # protocol address length
    b"\x00\x01"                      # opcode: request
    b"\x00\x11\x22\x33\x44\x55"      # sender hardware address
    b"\x0a\x00\x00\x01"              # sender protocol address
    b"\x00\x00\x00\x00\x00\x00"      # target hardware address (unknown)
    b"\x0a\x00\x00\x02"              # target protocol address
)

# DNS message header, RFC 1035 4.1.1. Flags 0x0100: QR 0, OPCODE 0, RD 1.
DNS_HEADER = (
    b"\x12\x34"                      # ID
    b"\x01\x00"                      # QR/OPCODE/AA/TC/RD/RA/Z/RCODE
    b"\x00\x01"                      # QDCOUNT
    b"\x00\x00"                      # ANCOUNT
    b"\x00\x00"                      # NSCOUNT
    b"\x00\x00"                      # ARCOUNT
)

# Bytes that no implemented dissector claims, used for the Raw fallback tests.
GARBAGE = bytes(range(0x30, 0x60))
