"""Little-endian fields, through the Bluetooth layers that carry them.

Vectors are built by hand from the Bluetooth Core Specification v5.4 and the
Assigned Numbers document, not generated by scapy.
"""

import wiry
from wiry import (
    HCI_ACL_Hdr,
    HCI_Cmd_Create_Connection,
    HCI_Cmd_Inquiry,
    HCI_Command_Hdr,
    HCI_Event_Read_Remote_Supported_Features_Complete,
    HCI_Hdr,
    EIR_ClassOfDevice,
    LL_CTE_REQ,
)

# Vol 4 Part E §5.4.2: handle in bits 0-11 of a little-endian word, the packet
# boundary flag in 12-13, broadcast in 14-15, then a little-endian length.
ACL = bytes([0x02, 0x2A, 0x20, 0x04, 0x00]) + b"data"


def test_an_acl_header_reads_its_flags_from_the_top_of_the_word():
    p = HCI_Hdr(ACL)
    assert p.layers()[:2] == ["HCI_Hdr", "HCI_ACL_Hdr"]
    assert (p.connection_handle, p.PB, p.BC, p[HCI_ACL_Hdr].len) == (0x02A, 2, 0, 4)


def test_an_acl_header_builds_the_same_word_and_its_length():
    built = bytes(HCI_Hdr() / HCI_ACL_Hdr(connection_handle=0x02A, PB=2) / b"data")
    assert built == ACL


def test_writing_one_field_of_a_group_leaves_its_neighbours():
    p = HCI_Hdr(ACL)
    p.connection_handle = 0xABC
    assert bytes(p)[1:3] == bytes([0xBC, 0x2A])
    assert (p.connection_handle, p.PB, p.BC) == (0xABC, 2, 0)


def test_a_command_opcode_is_ogf_and_ocf_in_one_little_endian_word():
    # §7.1.1 Inquiry: OGF 0x01, OCF 0x0001, opcode 0x0401; a LAP of 0x9E8B33
    # is sent least significant octet first.
    built = bytes(HCI_Hdr() / HCI_Command_Hdr() / HCI_Cmd_Inquiry(inquiry_length=8))
    assert built == bytes([0x01, 0x01, 0x04, 0x05, 0x33, 0x8B, 0x9E, 0x08, 0x00])
    p = HCI_Hdr(built)
    assert HCI_Cmd_Inquiry in p
    assert (p.ogf, p.ocf, p[HCI_Command_Hdr].len, p.lap) == (1, 1, 5, 0x9E8B33)


def test_an_assigned_length_is_kept():
    built = bytes(HCI_Command_Hdr(len=10) / HCI_Cmd_Inquiry())
    assert built[2] == 10


def test_a_bd_addr_is_sent_least_significant_octet_first():
    # Vol 2 Part B §1.2 and Vol 4 Part E §5.2.
    built = bytes(HCI_Command_Hdr() / HCI_Cmd_Create_Connection(bd_addr="aa:bb:cc:dd:ee:ff"))
    assert built[3:9] == bytes([0xFF, 0xEE, 0xDD, 0xCC, 0xBB, 0xAA])
    p = HCI_Command_Hdr(built)
    assert p.bd_addr == "aa:bb:cc:dd:ee:ff"


def test_a_sixty_four_bit_feature_mask_is_one_little_endian_integer():
    # Vol 2 Part C §3.3: bit 0 of the first octet is 3-slot packets and bit 7
    # of the last is extended features.
    raw = bytes([0x00, 0x01, 0x00, 0x01, 0, 0, 0, 0, 0, 0, 0x80])
    p = HCI_Event_Read_Remote_Supported_Features_Complete(raw)
    assert int(p.lmp_features) == (1 << 63) | 1
    assert p.lmp_features.extended_features
    assert getattr(p.lmp_features, "3_slot_packets")


def test_a_class_of_device_counts_from_the_top_of_three_octets():
    # Assigned Numbers §2.8: format bits 0-1, minor class 2-7, major class
    # 8-12, services 13-23. 0x5A020C is a smartphone offering networking,
    # capturing, object transfer and telephony.
    p = EIR_ClassOfDevice(bytes([0x0C, 0x02, 0x5A]))
    assert (p.major_device_class, p.minor_device_class, p.fixed) == (2, 3, 0)
    assert int(p.major_service_classes) == 0x5A020C >> 13
    assert bytes(EIR_ClassOfDevice(major_service_classes=0x2D0, major_device_class=2,
                                   minor_device_class=3)) == bytes([0x0C, 0x02, 0x5A])


def test_contrib_bit_fields_count_from_the_bottom_of_the_octet():
    # Vol 6 Part B §2.4.2.33: MinCTELenReq is bits 0-4, CTETypeReq bits 6-7.
    p = LL_CTE_REQ(bytes([0x94]))
    assert (p.min_cte_len_req, p.rfu, p.cte_type_req) == (0x14, 0, 2)
    assert bytes(LL_CTE_REQ(min_cte_len_req=0x14, cte_type_req=2)) == bytes([0x94])


def test_columns_read_a_little_endian_group_as_each_packet_does(tmp_path):
    frames = [HCI_Hdr() / HCI_ACL_Hdr(connection_handle=h, PB=h % 4, BC=(h >> 2) % 4) / b"x"
              for h in (0, 1, 0x2A, 0x7FF, 0xFFF)]
    path = tmp_path / "hci.pcap"
    wiry.wrpcap(str(path), frames)
    pl = wiry.rdpcap(str(path))
    cols = pl.columns([("HCI_ACL_Hdr", f) for f in ("connection_handle", "PB", "BC")])
    per = [(p.connection_handle, p.PB, p.BC) for p in pl]
    assert list(zip(*cols.values())) == per
    assert per == [(h, h % 4, (h >> 2) % 4) for h in (0, 1, 0x2A, 0x7FF, 0xFFF)]
