"""Encapsulation layers: the chain must not stop at the tunnel.

Vectors are laid out from the RFC field diagrams cited above each one. Nothing
here is generated by running another packet library.
"""

import struct

import pytest

from wiry import (
    ERSPAN_II, ERSPAN_III, Ether, GENEVE, GRE, GTP_U_Header, IP, IPv6,
    IPv6ExtHdrDestOpt, IPv6ExtHdrFragment, IPv6ExtHdrHopByHop,
    IPv6ExtHdrRouting, MPLS, PPP, PPPoE, PPPoED, Raw, TCP, UDP, VXLAN, rdpcap,
    wrpcap,
)


def ip4(proto, payload, src="10.0.0.1", dst="10.0.0.2"):
    return bytes(IP(src=src, dst=dst, proto=proto) / Raw(load=payload))


def inner_frame(dst="33:33:33:33:33:33"):
    return bytes(Ether(dst=dst, src="44:44:44:44:44:44") / IP(src="192.168.1.1") / TCP(dport=443))


# --- IPv6 extension headers, RFC 8200 §4 -----------------------------------


@pytest.mark.parametrize(
    "nh,cls,name",
    [
        (0, IPv6ExtHdrHopByHop, "IPv6ExtHdrHopByHop"),
        (60, IPv6ExtHdrDestOpt, "IPv6ExtHdrDestOpt"),
    ],
)
def test_an_option_header_is_walked_to_the_transport(nh, cls, name):
    # RFC 2711 §2.1 Router Alert, then PadN to fill the 8-octet unit.
    opts = b"\x05\x02\x00\x00\x01\x00"
    payload = bytes([17]) + b"\x00" + opts + bytes(UDP(sport=1234, dport=80))
    pkt = Ether(bytes(Ether() / IPv6(nh=nh) / Raw(load=payload)))
    assert pkt.layers() == ["Ether", "IPv6", name, "UDP"]
    assert pkt[name].nh == 17
    assert pkt[name].len == 0
    assert pkt[UDP].dport == 80


def test_a_routing_header_names_its_type_and_segments_left():
    # RFC 8200 §4.4 Type 0, one address, segments left 1.
    payload = bytes([6, 0x02, 0x00, 0x01, 0, 0, 0, 0]) + b"\x20\x01\x0d\xb8" + bytes(12)
    payload += bytes(TCP(dport=22))
    pkt = Ether(bytes(Ether() / IPv6(nh=43) / Raw(load=payload)))
    assert pkt.layers() == ["Ether", "IPv6", "IPv6ExtHdrRouting", "TCP"]
    assert pkt[IPv6ExtHdrRouting].type == 0
    assert pkt[IPv6ExtHdrRouting].segleft == 1
    assert pkt[TCP].dport == 22


def test_a_later_fragment_carries_no_transport_header():
    # RFC 8200 §4.5: offset 23 eight-octet units, M clear.
    payload = bytes([6, 0x00, 0x00, 0xB8, 0, 0, 0, 7]) + bytes(TCP())
    pkt = Ether(bytes(Ether() / IPv6(nh=44) / Raw(load=payload)))
    assert pkt.layers() == ["Ether", "IPv6", "IPv6ExtHdrFragment", "Raw"]
    assert pkt[IPv6ExtHdrFragment].offset == 23
    assert pkt[IPv6ExtHdrFragment].m == 0


def test_a_first_fragment_still_reaches_the_transport():
    payload = bytes([6, 0x00, 0x00, 0x01, 0, 0, 0, 7]) + bytes(TCP(dport=8080))
    pkt = Ether(bytes(Ether() / IPv6(nh=44) / Raw(load=payload)))
    assert pkt.layers() == ["Ether", "IPv6", "IPv6ExtHdrFragment", "TCP"]
    assert pkt[TCP].dport == 8080


def test_an_extension_chain_builds_and_reads_back():
    pkt = Ether() / IPv6() / IPv6ExtHdrHopByHop() / IPv6ExtHdrFragment(id=9) / UDP(dport=53)
    back = Ether(bytes(pkt))
    assert back.layers() == [
        "Ether", "IPv6", "IPv6ExtHdrHopByHop", "IPv6ExtHdrFragment", "UDP",
    ]
    assert back[IPv6].nh == 0
    assert back[IPv6ExtHdrHopByHop].nh == 44
    assert back[IPv6ExtHdrFragment].nh == 17
    assert back[IPv6ExtHdrFragment].id == 9
    # RFC 8200 §3: everything past the fixed header, extension headers included.
    assert back[IPv6].plen == len(bytes(pkt)) - 14 - 40


# --- GRE, RFC 2784 / RFC 2890 ----------------------------------------------


def test_gre_carries_a_datagram():
    pkt = Ether(bytes(Ether() / IP() / GRE() / IP(src="192.168.1.1") / TCP(dport=443)))
    assert pkt.layers() == ["Ether", "IP", "GRE", "IP", "TCP"]
    assert pkt[GRE].proto == 0x0800
    assert pkt[IP:2].src == "192.168.1.1"
    assert pkt[TCP].dport == 443


def test_gre_key_and_sequence_move_the_fields_that_follow():
    pkt = Ether() / IP() / GRE(key_present=1, seqnum_present=1, key=0x11223344, seqnum=9)
    pkt = pkt / IP() / UDP()
    back = Ether(bytes(pkt))
    assert back.layers() == ["Ether", "IP", "GRE", "IP", "UDP"]
    assert back[GRE].key == 0x11223344
    assert back[GRE].seqnum == 9


def test_gre_carries_a_whole_frame_under_transparent_ethernet_bridging():
    payload = b"\x00\x00\x65\x58" + inner_frame()
    pkt = Ether(bytes(Ether() / IP(proto=47) / Raw(load=payload)))
    assert pkt.layers() == ["Ether", "IP", "GRE", "Ether", "IP", "TCP"]
    assert pkt[Ether:2].dst == "33:33:33:33:33:33"


# --- IP in IP, RFC 2003 / RFC 4213 -----------------------------------------


@pytest.mark.parametrize(
    "outer,proto,inner,chain",
    [
        (IP(), 4, IP(src="192.168.1.1"), ["Ether", "IP", "IP", "TCP"]),
        (IP(), 41, IPv6(), ["Ether", "IP", "IPv6", "TCP"]),
        (IPv6(), 4, IP(src="192.168.1.1"), ["Ether", "IPv6", "IP", "TCP"]),
        (IPv6(), 41, IPv6(), ["Ether", "IPv6", "IPv6", "TCP"]),
    ],
)
def test_a_datagram_tunnelled_in_a_datagram(outer, proto, inner, chain):
    pkt = Ether(bytes(Ether() / outer / inner / TCP(dport=22)))
    assert pkt.layers() == chain
    assert pkt[TCP].dport == 22


# --- VXLAN, RFC 7348 --------------------------------------------------------


def test_vxlan_reaches_the_inner_addresses():
    pkt = Ether() / IP(dst="10.9.9.9") / UDP() / VXLAN(vni=0x1234)
    pkt = pkt / Ether() / IP(dst="192.168.1.2") / TCP(dport=443)
    back = Ether(bytes(pkt))
    assert back.layers() == ["Ether", "IP", "UDP", "VXLAN", "Ether", "IP", "TCP"]
    assert back[UDP].dport == 4789
    assert back[VXLAN].vni == 0x1234
    assert back[IP].dst == "10.9.9.9"
    assert back[IP:2].dst == "192.168.1.2"


def test_a_vxlan_header_with_no_frame_under_it_is_raw():
    payload = b"\x08\x00\x00\x00\x00\x12\x34\x00" + b"\xff" * 4
    pkt = Ether(bytes(Ether() / IP() / UDP(sport=40000, dport=4789) / Raw(load=payload)))
    assert pkt.layers() == ["Ether", "IP", "UDP", "VXLAN", "Raw"]


# --- Geneve, RFC 8926 -------------------------------------------------------


def test_geneve_walks_past_its_options():
    opts = b"\x01\x02\x01\x01\xde\xad\xbe\xef"
    pkt = Ether() / IP() / UDP() / GENEVE(vni=0xABC, options=opts) / Ether() / IP() / UDP()
    back = Ether(bytes(pkt))
    assert back.layers() == ["Ether", "IP", "UDP", "GENEVE", "Ether", "IP", "UDP"]
    assert back[UDP].dport == 6081
    assert back[GENEVE].optionlen == 2
    assert back[GENEVE].vni == 0xABC
    assert back[GENEVE].options == opts


# --- MPLS, RFC 3032 ---------------------------------------------------------


def test_an_mpls_stack_is_walked_to_its_bottom():
    pkt = Ether() / MPLS(label=16) / MPLS(label=100) / IP(src="192.168.1.1") / UDP(dport=161)
    back = Ether(bytes(pkt))
    assert back.layers() == ["Ether", "MPLS", "MPLS", "IP", "UDP"]
    assert back[Ether].type == 0x8847
    assert back[MPLS].s == 0
    assert back[MPLS:2].s == 1
    assert back[MPLS:2].label == 100
    assert back[UDP].dport == 161


def test_mpls_carries_an_ethernet_pseudowire():
    pkt = Ether() / MPLS(label=1) / Ether(dst="33:33:33:33:33:33") / IP() / TCP()
    back = Ether(bytes(pkt))
    assert back.layers() == ["Ether", "MPLS", "Ether", "IP", "TCP"]
    assert back[Ether:2].dst == "33:33:33:33:33:33"


def test_a_pseudowire_control_word_is_not_guessed_at():
    # RFC 4385 §3: a leading zero nibble is a control word, which has no layer
    # here, so the payload stays opaque rather than being read as a frame.
    payload = b"\x00\x01\x01\x40" + b"\x00\x00\x04\xd2" + inner_frame()
    pkt = Ether(bytes(Ether(type=0x8847) / Raw(load=payload)))
    assert pkt.layers() == ["Ether", "MPLS", "Raw"]


# --- PPPoE, RFC 2516 / RFC 1661 ---------------------------------------------


def test_a_pppoe_session_reaches_the_datagram():
    pkt = Ether() / PPPoE(sessionid=7) / PPP() / IP(src="192.168.1.1") / UDP(dport=53)
    back = Ether(bytes(pkt))
    assert back.layers() == ["Ether", "PPPoE", "PPP", "IP", "UDP"]
    assert back[Ether].type == 0x8864
    assert back[PPPoE].sessionid == 7
    assert back[PPPoE].len == len(bytes(pkt)) - 14 - 6
    assert back[PPP].proto == 0x0021


def test_a_discovery_packet_keeps_its_tag_list_opaque():
    # PADI, code 0x09, one zero-length Service-Name tag.
    body = b"\x11\x09\x00\x00\x00\x04\x01\x01\x00\x00"
    pkt = Ether(bytes(Ether(type=0x8863) / Raw(load=body)))
    assert pkt.layers() == ["Ether", "PPPoED", "Raw"]
    assert pkt[PPPoED].code == 9


# --- GTP-U, 3GPP TS 29.281 --------------------------------------------------


def test_gtp_u_carries_the_subscriber_datagram():
    pkt = Ether() / IP() / UDP() / GTP_U_Header(teid=0xDEADBEEF) / IP(src="192.168.1.1") / TCP()
    back = Ether(bytes(pkt))
    assert back.layers() == ["Ether", "IP", "UDP", "GTP_U_Header", "IP", "TCP"]
    assert back[UDP].dport == 2152
    assert back[GTP_U_Header].teid == 0xDEADBEEF
    assert back[GTP_U_Header].length == 40
    assert back[IP:2].src == "192.168.1.1"


def test_a_gtp_extension_header_is_walked_past():
    inner = bytes(IP(src="192.168.1.1") / TCP())
    body = bytes([0x34, 0xFF]) + struct.pack("!H", 8 + len(inner)) + b"\x00\x00\x00\x05"
    body += b"\x00\x00\x00\x85" + b"\x01\x00\x00\x00" + inner
    pkt = Ether(bytes(Ether() / IP() / UDP(sport=40000, dport=2152) / Raw(load=body)))
    assert pkt.layers() == ["Ether", "IP", "UDP", "GTP_U_Header", "IP", "TCP"]
    assert pkt[GTP_U_Header].next_ex == 0x85
    assert pkt[IP:2].src == "192.168.1.1"


# --- ERSPAN, draft-foschiano-erspan-03 --------------------------------------


def test_erspan_type_two_carries_the_mirrored_frame():
    body = b"\x10\x00\x88\xbe" + b"\x00\x00\x00\x01"
    body += b"\x10\x64\x00\x05" + b"\x00\x00\x00\x09" + inner_frame()
    pkt = Ether(bytes(Ether() / IP(proto=47) / Raw(load=body)))
    assert pkt.layers() == ["Ether", "IP", "GRE", "ERSPAN_II", "Ether", "IP", "TCP"]
    assert pkt[ERSPAN_II].vlan == 100
    assert pkt[ERSPAN_II].session_id == 5
    assert pkt[ERSPAN_II].index == 9


def test_erspan_type_one_has_no_header_of_its_own():
    body = b"\x00\x00\x88\xbe" + inner_frame()
    pkt = Ether(bytes(Ether() / IP(proto=47) / Raw(load=body)))
    assert pkt.layers() == ["Ether", "IP", "GRE", "Ether", "IP", "TCP"]


def test_erspan_type_three_optional_subheader():
    for o in (0, 1):
        body = b"\x00\x00\x22\xeb"
        body += b"\x20\x64\x00\x05" + b"\x11\x22\x33\x44" + bytes([0, 0, 0, o])
        if o:
            body += b"\xde\xad\xbe\xef\x00\x00\x00\x00"
        body += inner_frame()
        pkt = Ether(bytes(Ether() / IP(proto=47) / Raw(load=body)))
        assert pkt.layers() == ["Ether", "IP", "GRE", "ERSPAN_III", "Ether", "IP", "TCP"]
        assert pkt[ERSPAN_III].timestamp == 0x11223344
        assert pkt[ERSPAN_III].o == o
        # Only a header measured against the O bit lands the frame right here.
        assert pkt[Ether:2].dst == "33:33:33:33:33:33"


# --- Nesting, round-trip, and the bulk path ---------------------------------


def test_a_tunnel_inside_a_tunnel_inside_a_tunnel():
    pkt = Ether() / IP(dst="10.0.0.1") / GRE()
    pkt = pkt / IP(dst="10.0.0.2") / UDP() / VXLAN(vni=5)
    pkt = pkt / Ether() / IP(dst="10.0.0.3") / TCP(dport=443)
    back = Ether(bytes(pkt))
    assert back.layers() == [
        "Ether", "IP", "GRE", "IP", "UDP", "VXLAN", "Ether", "IP", "TCP",
    ]
    assert [back[IP:i].dst for i in (1, 2, 3)] == ["10.0.0.1", "10.0.0.2", "10.0.0.3"]
    assert back[TCP].dport == 443


def test_an_arbitrarily_nested_capture_is_bounded():
    body = bytes(Ether() / IP() / TCP())
    for _ in range(100):
        body = b"\x00\x00\x65\x58" + body
        body = ip4(47, body)
    pkt = Ether(bytes(Ether() / Raw(load=body)))
    assert len(pkt.layers()) <= 33
    assert bytes(pkt) == bytes(Ether() / Raw(load=body))


@pytest.mark.parametrize(
    "make",
    [
        lambda: Ether() / IP() / GRE() / IP() / TCP(),
        lambda: Ether() / IP() / UDP() / VXLAN() / Ether() / IP() / UDP(),
        lambda: Ether() / IP() / UDP() / GENEVE() / Ether() / IP() / TCP(),
        lambda: Ether() / IP() / UDP() / GTP_U_Header() / IP() / TCP(),
        lambda: Ether() / MPLS() / IP() / UDP(),
        lambda: Ether() / PPPoE() / PPP() / IP() / TCP(),
        lambda: Ether() / IPv6() / IPv6ExtHdrDestOpt() / TCP(),
    ],
)
def test_every_tunnel_round_trips_byte_for_byte(make):
    raw = bytes(make())
    assert bytes(Ether(raw)) == raw
    for cut in range(len(raw)):
        assert bytes(Ether(raw[:cut])) == raw[:cut]


def tunnel_capture():
    return [
        Ether() / IP(dst="10.0.0.1") / UDP() / VXLAN(vni=1)
        / Ether() / IP(dst="192.168.0.1") / TCP(dport=80),
        Ether() / IP(dst="10.0.0.2") / GRE() / IP(dst="192.168.0.2") / TCP(dport=443),
        Ether() / IP(dst="10.0.0.3") / TCP(dport=22),
        Ether() / IPv6() / IPv6ExtHdrHopByHop() / UDP(dport=546),
    ]


def test_the_bulk_path_sees_inner_layers_and_agrees_with_the_loop(tmp_path):
    path = str(tmp_path / "tunnels.pcap")
    wrpcap(path, tunnel_capture())
    cap = rdpcap(path)

    specs = [("IP", "dst"), ("TCP", "dport"), ("VXLAN", "vni"), ("GRE", "proto")]
    cols = cap.columns(specs)
    for layer, field in specs:
        want = [
            getattr(pkt[layer], field) if pkt.haslayer(layer) else None for pkt in cap
        ]
        assert cols[f"{layer}.{field}"] == want, f"{layer}.{field}"

    # The bulk path must not quietly report the inner tunnel endpoint for the
    # outer one: IP.dst names the first, the rest are reachable by index.
    assert cols["IP.dst"] == ["10.0.0.1", "10.0.0.2", "10.0.0.3", None]
    assert cols["VXLAN.vni"] == [1, None, None, None]


def test_filtering_on_an_inner_layer_selects_in_the_engine(tmp_path):
    path = str(tmp_path / "tunnels.pcap")
    wrpcap(path, tunnel_capture())
    cap = rdpcap(path)
    got = cap.filter([("VXLAN", "vni", 1)])
    assert len(got) == 1
    assert got[0].haslayer(VXLAN)
    assert [p.summary() for p in cap.filter([("GRE", "proto", 0x0800)])] == [
        "Ether / IP / GRE / IP / TCP"
    ]


# --- Lengths no field can hold are refused, never wrapped -------------------


def padn(n):
    """RFC 8200 §4.2 PadN blocks totalling n octets."""
    out = b""
    while n > 0:
        k = min(n, 257)
        if k == 1:
            out += b"\x00"
            n -= 1
            continue
        out += b"\x01" + bytes([k - 2]) + b"\x00" * (k - 2)
        n -= k
    return out


def test_a_geneve_option_block_wider_than_six_bits_is_refused():
    # RFC 8926 §3.1: Opt Len is six bits of 4-octet words, so 252 octets is the
    # most it can name. 256 used to write 64 & 0x3f == 0 and swallow the block.
    ok = Ether() / IP() / UDP() / GENEVE(options=b"\xaa" * 252) / Ether() / IP() / TCP()
    assert Ether(bytes(ok))[GENEVE].optionlen == 63
    assert Ether(bytes(ok)).layers()[-1] == "TCP"
    with pytest.raises(ValueError, match="GENEVE.optionlen"):
        bytes(Ether() / IP() / UDP() / GENEVE(options=b"\xaa" * 256) / Ether() / IP())


def test_an_extension_header_wider_than_eight_bits_is_refused():
    # RFC 8200 §4.3: Hdr Ext Len is eight bits of 8-octet units, so 2046 octets
    # of options is the most it can name; 2054 used to clamp to 255 and read the
    # eight octets past the claim as the transport header.
    ok = Ether() / IPv6() / IPv6ExtHdrDestOpt(options=padn(2046)) / UDP()
    assert Ether(bytes(ok))[IPv6ExtHdrDestOpt].len == 255
    assert Ether(bytes(ok)).layers()[-1] == "UDP"
    with pytest.raises(ValueError, match="IPv6ExtHdrDestOpt.len"):
        bytes(Ether() / IPv6() / IPv6ExtHdrDestOpt(options=padn(2054)) / UDP())


def test_a_pppoe_payload_wider_than_sixteen_bits_is_refused():
    # RFC 2516 §4: LENGTH is sixteen bits and nothing encloses PPPoE that would
    # catch the overflow, so 70000 octets used to emit 70002 % 65536 == 4466.
    with pytest.raises(ValueError, match="PPPoE.len"):
        bytes(Ether() / PPPoE() / PPP() / Raw(load=b"x" * 70000))
    with pytest.raises(ValueError, match="GTP_U_Header.length"):
        bytes(Ether() / GTP_U_Header() / Raw(load=b"x" * 70000))


# --- A clipped capture keeps the lengths the wire gave (E12) ----------------


def clipped_hop_by_hop():
    """IPv6 claiming 200 payload octets, carrying 24 of a 48-octet header."""
    payload = bytes([17, 5]) + b"\x01\x00" * 11
    return bytes(Ether() / IPv6(plen=200, nh=0)) + payload


def test_editing_a_clipped_capture_does_not_shrink_an_extension_header_length():
    raw = clipped_hop_by_hop()
    pkt = Ether(raw)
    assert pkt[IPv6ExtHdrHopByHop].len == 5
    pkt[IPv6].hlim = 1
    assert Ether(bytes(pkt))[IPv6ExtHdrHopByHop].len == 5


def test_editing_a_clipped_capture_does_not_shrink_a_geneve_option_length():
    # Opt Len 16 words = 64 octets of options, of which 20 were captured.
    body = b"\x10\x00\x65\x58\x00\x00\x01\x00" + b"\xaa" * 20
    raw = bytes(Ether() / IP(len=20 + 8 + 200) / UDP(sport=40000, dport=6081, len=208)) + body
    pkt = Ether(raw)
    assert pkt[GENEVE].optionlen == 16
    pkt[IP].ttl = 3
    assert Ether(bytes(pkt))[GENEVE].optionlen == 16


# --- ERSPAN Type II is told from Type I by GRE's sequence bit ---------------


def test_stacking_erspan_type_two_sets_the_gre_sequence_bit():
    # draft-foschiano-erspan-03 §4. Without it the built frame dissects back as
    # a bare Type I and the mirrored frame reads eight octets out of place.
    pkt = Ether() / IP() / GRE() / ERSPAN_II(session_id=5) / Ether() / IP() / TCP()
    back = Ether(bytes(pkt))
    assert back.layers() == ["Ether", "IP", "GRE", "ERSPAN_II", "Ether", "IP", "TCP"]
    assert back[GRE].seqnum_present == 1
    assert back[ERSPAN_II].session_id == 5
    # Type III is reached by its own EtherType, so the bit stays clear.
    three = Ether(bytes(Ether() / IP() / GRE() / ERSPAN_III() / Ether() / IP() / TCP()))
    assert three.layers() == ["Ether", "IP", "GRE", "ERSPAN_III", "Ether", "IP", "TCP"]
    assert three[GRE].seqnum_present == 0


# --- Every layer, cut at every offset ---------------------------------------


def truncation_corpus():
    """One crafted packet per encapsulation, laid out from the RFCs above."""
    tcp = bytes(TCP())
    ip = lambda proto, body: bytes(IP(proto=proto) / Raw(load=body))
    ip6 = lambda nh, body: bytes(IPv6(nh=nh) / Raw(load=body))
    udp = lambda dport, body: bytes(UDP(sport=40000, dport=dport) / Raw(load=body))
    eth = lambda t, body: bytes(Ether(type=t) / Raw(load=body))
    gre_erspan = b"\x10\x00\x88\xbe\x00\x00\x00\x01"
    return {
        "hopbyhop": eth(0x86DD, ip6(0, bytes([17, 0, 5, 2, 0, 0, 1, 0]) + bytes(UDP()))),
        "routing": eth(0x86DD, ip6(43, bytes([6, 2, 0, 1, 0, 0, 0, 0]) + bytes(16) + tcp)),
        "fragment": eth(0x86DD, ip6(44, bytes([6, 0, 0, 1, 0, 0, 0, 7]) + tcp)),
        "destopt": eth(0x86DD, ip6(60, bytes([6, 0, 1, 4, 0, 0, 0, 0]) + tcp)),
        "gre": eth(0x0800, ip(47, b"\xb0\x00\x08\x00" + bytes(12) + ip(6, tcp))),
        "gre-teb": eth(0x0800, ip(47, b"\x00\x00\x65\x58" + inner_frame())),
        "vxlan": eth(0x0800, ip(17, udp(4789, b"\x08\x00\x00\x00\x00\x12\x34\x00" + inner_frame()))),
        "geneve": eth(0x0800, ip(17, udp(6081, b"\x02\x00\x65\x58\x00\x0a\xbc\x00"
                                         + b"\x01\x02\x01\x01\xde\xad\xbe\xef" + inner_frame()))),
        "gtp": eth(0x0800, ip(17, udp(2152, bytes([0x34, 0xFF])
                                      + struct.pack("!H", 12 + len(ip(6, tcp)))
                                      + b"\x00\x00\x00\x05\x00\x00\x00\x85\x01\x00\x00\x00"
                                      + ip(6, tcp)))),
        "mpls": eth(0x8847, b"\x00\x01\x00\x40\x00\x02\x01\x40" + ip(6, tcp)),
        "mpls-pw": eth(0x8847, b"\x00\x01\x01\x40" + inner_frame()),
        "pppoe": eth(0x8864, b"\x11\x00\x00\x07"
                     + struct.pack("!H", 2 + len(ip(6, tcp))) + b"\x00\x21" + ip(6, tcp)),
        "pppoed": eth(0x8863, b"\x11\x09\x00\x00\x00\x04\x01\x01\x00\x00"),
        "erspan2": eth(0x0800, ip(47, gre_erspan + b"\x10\x64\x00\x05\x00\x00\x00\x09"
                                  + inner_frame())),
        "erspan3": eth(0x0800, ip(47, b"\x00\x00\x22\xeb"
                                  + b"\x20\x64\x00\x05\x11\x22\x33\x44\x00\x00\x00\x01"
                                  + b"\xde\xad\xbe\xef\x00\x00\x00\x00" + inner_frame())),
        "ip-in-ip": eth(0x0800, ip(4, ip(6, tcp))),
        "6in4": eth(0x0800, ip(41, ip6(6, tcp))),
        "4in6": eth(0x86DD, ip6(4, ip(6, tcp))),
    }


@pytest.mark.parametrize("name", sorted(truncation_corpus()))
def test_every_layer_survives_a_cut_at_every_offset(name):
    raw = truncation_corpus()[name]
    for cut in range(len(raw) + 1):
        want = raw[:cut]
        pkt = Ether(want)
        assert bytes(pkt) == want, f"{name} cut={cut}"
        # The write half needs its own coverage: a read-only sweep leaves every
        # recomputation unexercised, which is where the panics lived before.
        pkt.summary()
        pkt.show()
        again = Ether(want)
        for layer in dict.fromkeys(again.layers()):
            obj = again[layer]
            for field in obj.fields():
                value = getattr(obj, field)
                if isinstance(value, int):
                    setattr(obj, field, value)
        bytes(again)
