"""Names the Python-modelled layers export, by defining module.

Kept apart from the modules themselves so `import wiry` and `dir(wiry)`
can list them without importing any.
"""

EXPORTS = {
    "asn1.asn1": (
        "ASN1_Error", "ASN1_Encoding_Error", "ASN1_Decoding_Error",
        "ASN1_BadTag_Decoding_Error", "ASN1Codec", "ASN1_Codecs",
        "ASN1Tag", "ASN1_Class", "ASN1_Class_UNIVERSAL", "ASN1_Object",
        "ASN1_DECODING_ERROR", "ASN1_force", "ASN1_BADTAG", "ASN1_INTEGER",
        "ASN1_BOOLEAN", "ASN1_BIT_STRING", "ASN1_STRING", "ASN1_NULL",
        "ASN1_OID", "ASN1_ENUMERATED", "ASN1_UTF8_STRING",
        "ASN1_NUMERIC_STRING", "ASN1_PRINTABLE_STRING", "ASN1_T61_STRING",
        "ASN1_VIDEOTEX_STRING", "ASN1_IA5_STRING", "ASN1_GENERAL_STRING",
        "ASN1_GENERALIZED_TIME", "ASN1_UTC_TIME", "ASN1_ISO646_STRING",
        "ASN1_UNIVERSAL_STRING", "ASN1_BMP_STRING", "ASN1_SEQUENCE",
        "ASN1_SET", "ASN1_IPADDRESS", "ASN1_COUNTER32", "ASN1_COUNTER64",
        "ASN1_GAUGE32", "ASN1_TIME_TICKS", "RandASN1Object", "RandOID",
        "GeneralizedTime", "IntAutoTime", "ZuluTime",
    ),
    "asn1.ber": (
        "BER_Exception", "BER_Encoding_Error", "BER_Decoding_Error",
        "BER_BadTag_Decoding_Error", "BER_len_enc", "BER_len_dec",
        "BER_num_enc", "BER_num_dec", "BER_id_dec", "BER_id_enc",
        "BER_tagging_dec", "BER_tagging_enc", "BERcodec_Object",
        "BERcodec_INTEGER", "BERcodec_BOOLEAN", "BERcodec_BIT_STRING",
        "BERcodec_STRING", "BERcodec_NULL", "BERcodec_OID",
        "BERcodec_ENUMERATED", "BERcodec_UTF8_STRING",
        "BERcodec_NUMERIC_STRING", "BERcodec_PRINTABLE_STRING",
        "BERcodec_T61_STRING", "BERcodec_VIDEOTEX_STRING",
        "BERcodec_IA5_STRING", "BERcodec_GENERAL_STRING",
        "BERcodec_UTC_TIME", "BERcodec_GENERALIZED_TIME",
        "BERcodec_ISO646_STRING", "BERcodec_UNIVERSAL_STRING",
        "BERcodec_BMP_STRING", "BERcodec_SEQUENCE", "BERcodec_SET",
        "BERcodec_IPADDRESS", "BERcodec_COUNTER32", "BERcodec_COUNTER64",
        "BERcodec_GAUGE32", "BERcodec_TIME_TICKS",
    ),
    "asn1.mib": (
        "MIBDict", "load_mib",
    ),
    "asn1fields": (
        "ASN1F_badsequence", "ASN1F_element", "ASN1F_field",
        "ASN1F_BOOLEAN", "ASN1F_INTEGER", "ASN1F_enum_INTEGER",
        "ASN1F_BIT_STRING", "ASN1F_STRING", "ASN1F_NULL", "ASN1F_OID",
        "ASN1F_ENUMERATED", "ASN1F_UTF8_STRING", "ASN1F_NUMERIC_STRING",
        "ASN1F_PRINTABLE_STRING", "ASN1F_T61_STRING",
        "ASN1F_VIDEOTEX_STRING", "ASN1F_IA5_STRING",
        "ASN1F_GENERAL_STRING", "ASN1F_UTC_TIME", "ASN1F_GENERALIZED_TIME",
        "ASN1F_ISO646_STRING", "ASN1F_UNIVERSAL_STRING",
        "ASN1F_BMP_STRING", "ASN1F_SEQUENCE", "ASN1F_SET",
        "ASN1F_SEQUENCE_OF", "ASN1F_SET_OF", "ASN1F_IPADDRESS",
        "ASN1F_TIME_TICKS", "ASN1F_optional", "ASN1F_omit", "ASN1F_CHOICE",
        "ASN1F_PACKET", "ASN1F_BIT_STRING_ENCAPS", "ASN1F_FLAGS",
        "ASN1F_STRING_PacketField", "ASN1F_STRING_ENCAPS",
    ),
    "asn1packet": (
        "ASN1_Packet",
    ),
    "layers.snmp": (
        "ASN1_Class_SNMP", "ASN1_SNMP_PDU_GET",
        "ASN1_SNMP_PDU_NEXT", "ASN1_SNMP_PDU_RESPONSE",
        "ASN1_SNMP_PDU_SET", "ASN1_SNMP_PDU_TRAPv1", "ASN1_SNMP_PDU_BULK",
        "ASN1_SNMP_PDU_INFORM", "ASN1_SNMP_PDU_TRAPv2",
        "BERcodec_SNMP_PDU_GET", "BERcodec_SNMP_PDU_NEXT",
        "BERcodec_SNMP_PDU_RESPONSE", "BERcodec_SNMP_PDU_SET",
        "BERcodec_SNMP_PDU_TRAPv1", "BERcodec_SNMP_PDU_BULK",
        "BERcodec_SNMP_PDU_INFORM", "BERcodec_SNMP_PDU_TRAPv2",
        "ASN1F_SNMP_PDU_GET", "ASN1F_SNMP_PDU_NEXT",
        "ASN1F_SNMP_PDU_RESPONSE", "ASN1F_SNMP_PDU_SET",
        "ASN1F_SNMP_PDU_TRAPv1", "ASN1F_SNMP_PDU_BULK",
        "ASN1F_SNMP_PDU_INFORM", "ASN1F_SNMP_PDU_TRAPv2", "SNMPvarbind",
        "SNMPget", "SNMPnext", "SNMPresponse", "SNMPset", "SNMPtrapv1",
        "SNMPbulk", "SNMPinform", "SNMPtrapv2", "SNMP", "snmpget",
        "snmpwalk",
    ),
    "layers.x509": (
        "ASN1P_OID", "ASN1P_INTEGER", "ASN1P_PRIVSEQ", "RSAPublicKey",
        "RSAOtherPrimeInfo", "RSAPrivateKey", "ValidationParms",
        "DomainParameters", "DHPublicKey", "ECFieldID", "ECCurve",
        "ECSpecifiedDomain", "ECParameters", "ECDSAPublicKey",
        "ECDSAPrivateKey", "ECDSASignature", "DHParameter",
        "EdDSAPublicKey", "CurvePrivateKey", "EdDSAPrivateKey",
        "MLDSAPublicKey", "MLDSAPrivateKeySeed",
        "MLDSAPrivateKeyExpandedKey", "MLDSAPrivateKeyBoth",
        "MLDSAPrivateKey", "ASN1F_X509_DirectoryString",
        "X509_AttributeValue", "X509_Attribute",
        "X509_AttributeTypeAndValue", "X509_RDN", "X509_OtherName",
        "ASN1F_X509_otherName", "X509_RFC822Name", "X509_DNSName",
        "X509_X400Address", "X509_DirectoryName", "X509_EDIPartyName",
        "X509_URI", "X509_IPAddress", "X509_RegisteredID",
        "X509_GeneralName", "X509_ExtAuthorityKeyIdentifier",
        "X509_ExtSubjectDirectoryAttributes",
        "X509_ExtSubjectKeyIdentifier", "X509_ExtFullName",
        "X509_ExtNameRelativeToCRLIssuer", "X509_ExtDistributionPointName",
        "X509_ExtDistributionPoint", "X509_ExtKeyUsage",
        "X509_ExtPrivateKeyUsagePeriod", "X509_PolicyMapping",
        "X509_ExtPolicyMappings", "X509_ExtBasicConstraints",
        "X509_ExtCRLNumber", "X509_ExtReasonCode",
        "X509_ExtDeltaCRLIndicator", "X509_ExtIssuingDistributionPoint",
        "X509_ExtCertificateIssuer", "X509_ExtInvalidityDate",
        "X509_ExtSubjectAltName", "X509_ExtIssuerAltName",
        "X509_ExtGeneralSubtree", "X509_ExtNameConstraints",
        "X509_ExtPolicyConstraints", "X509_ExtExtendedKeyUsage",
        "X509_ExtNoticeReference", "X509_ExtUserNotice",
        "X509_ExtPolicyQualifierInfo", "X509_ExtPolicyInformation",
        "X509_ExtCertificatePolicies", "X509_ExtCRLDistributionPoints",
        "X509_ExtInhibitAnyPolicy", "X509_ExtFreshestCRL",
        "X509_AccessDescription", "X509_ExtAuthInfoAccess",
        "X509_ExtQcStatement", "X509_ExtQcStatements",
        "X509_ExtSubjInfoAccess", "X509_ExtNetscapeCertType",
        "X509_ExtComment", "X509_ExtCertificateTemplateName",
        "X509_ExtOidNTDSCaSecurity", "X509_ExtCertificateTemplateOID",
        "ASN1F_EXT_SEQUENCE", "X509_Extension", "X509_Extensions",
        "X509_AlgorithmIdentifier", "ASN1F_X509_PublicKeyField",
        "X509_SubjectPublicKeyInfo", "X509_OneAsymmetricKey",
        "RSAPrivateKey_OpenSSL", "ECDSAPrivateKey_OpenSSL",
        "X509_Validity", "X509_TBSCertificate", "ASN1F_X509_Cert",
        "X509_Cert", "X509_RevokedCertificate", "X509_TBSCertList",
        "ASN1F_X509_CRL", "X509_CRL", "CMS_EncapsulatedContentInfo",
        "CMS_RevocationInfoChoice", "CMS_CertificateChoices",
        "CMS_IssuerAndSerialNumber", "CMS_OtherKeyAttribute",
        "CMS_SubjectKeyIdentifier", "CMS_SignerInfo",
        "CMS_SignedAttrsForSignature", "CMS_SignedData",
        "CMS_KeyTransRecipientInfo", "CMS_OriginatorPublicKey",
        "CMS_OriginatorIdentifierOrKey", "CMS_RecipientEncryptedKey",
        "CMS_KeyAgreeRecipientInfo", "CMS_RecipientInfo",
        "CMS_OriginatorInfo", "CMS_EncryptedContentInfo",
        "CMS_EnvelopedData", "CMS_ContentInfo",
        "PKCS10_CertificationRequestInfo", "PKCS10_CertificationRequest",
        "CMC_TaggedAttribute", "CMC_TaggedCertificationRequest",
        "CMC_TaggedRequest", "CMC_TaggedContentInfo", "CMC_OtherMsg",
        "CMC_PKIData", "CMC_AddExtensions", "CMC_AddAttributes",
        "CMC_ENROLLMENT_CSP_PROVIDER", "CMC_REQUEST_CLIENT_INFO",
        "CMC_EnrollmentNameValuePair", "CMC_ENROLL_ATTESTATION_STATEMENT",
        "OCSP_CertID", "OCSP_GoodInfo", "OCSP_RevokedInfo",
        "OCSP_UnknownInfo", "OCSP_CertStatus", "OCSP_SingleResponse",
        "OCSP_ByName", "OCSP_ByKey", "OCSP_ResponderID",
        "OCSP_ResponseData", "ASN1F_OCSP_BasicResponse",
        "OCSP_ResponseBytes", "OCSP_Response",
    ),
}

# Rust layers whose scapy contract is a tree of Python objects. The Rust layer
# stays in the dissection chain, so a capture of them is found, counted and
# filtered without Python; the name exported is the Python model.
PY_MODELLED = {"SNMP": "layers.snmp"}
