"""Names the Python-modelled layers export, by defining module.

Kept apart from the modules themselves so `import wiry` and `dir(wiry)`
can list them without importing any.
"""

EXPORTS = {
    "asn1.asn1": (
        "ASN1_Error", "ASN1_Encoding_Error", "ASN1_Decoding_Error",
        "ASN1_BadTag_Decoding_Error", "ASN1Codec", "ASN1_Codecs",
        "ASN1Tag", "ASN1_Class", "ASN1_Class_UNIVERSAL", "ASN1_Object",
        "ASN1_DECODING_ERROR", "ASN1_force", "ASN1_BADTAG", "ASN1_INTEGER",
        "ASN1_BOOLEAN", "ASN1_BIT_STRING", "ASN1_STRING", "ASN1_NULL",
        "ASN1_OID", "ASN1_ENUMERATED", "ASN1_UTF8_STRING",
        "ASN1_NUMERIC_STRING", "ASN1_PRINTABLE_STRING", "ASN1_T61_STRING",
        "ASN1_VIDEOTEX_STRING", "ASN1_IA5_STRING", "ASN1_GENERAL_STRING",
        "ASN1_GENERALIZED_TIME", "ASN1_UTC_TIME", "ASN1_ISO646_STRING",
        "ASN1_UNIVERSAL_STRING", "ASN1_BMP_STRING", "ASN1_SEQUENCE",
        "ASN1_SET", "ASN1_IPADDRESS", "ASN1_COUNTER32", "ASN1_COUNTER64",
        "ASN1_GAUGE32", "ASN1_TIME_TICKS", "RandASN1Object", "RandOID",
        "GeneralizedTime", "IntAutoTime", "ZuluTime",
    ),
    "asn1.ber": (
        "BER_Exception", "BER_Encoding_Error", "BER_Decoding_Error",
        "BER_BadTag_Decoding_Error", "BER_len_enc", "BER_len_dec",
        "BER_num_enc", "BER_num_dec", "BER_id_dec", "BER_id_enc",
        "BER_tagging_dec", "BER_tagging_enc", "BERcodec_Object",
        "BERcodec_INTEGER", "BERcodec_BOOLEAN", "BERcodec_BIT_STRING",
        "BERcodec_STRING", "BERcodec_NULL", "BERcodec_OID",
        "BERcodec_ENUMERATED", "BERcodec_UTF8_STRING",
        "BERcodec_NUMERIC_STRING", "BERcodec_PRINTABLE_STRING",
        "BERcodec_T61_STRING", "BERcodec_VIDEOTEX_STRING",
        "BERcodec_IA5_STRING", "BERcodec_GENERAL_STRING",
        "BERcodec_UTC_TIME", "BERcodec_GENERALIZED_TIME",
        "BERcodec_ISO646_STRING", "BERcodec_UNIVERSAL_STRING",
        "BERcodec_BMP_STRING", "BERcodec_SEQUENCE", "BERcodec_SET",
        "BERcodec_IPADDRESS", "BERcodec_COUNTER32", "BERcodec_COUNTER64",
        "BERcodec_GAUGE32", "BERcodec_TIME_TICKS",
    ),
    "asn1.mib": (
        "MIBDict", "load_mib",
    ),
    "asn1fields": (
        "ASN1F_badsequence", "ASN1F_element", "ASN1F_field",
        "ASN1F_BOOLEAN", "ASN1F_INTEGER", "ASN1F_enum_INTEGER",
        "ASN1F_BIT_STRING", "ASN1F_STRING", "ASN1F_NULL", "ASN1F_OID",
        "ASN1F_ENUMERATED", "ASN1F_UTF8_STRING", "ASN1F_NUMERIC_STRING",
        "ASN1F_PRINTABLE_STRING", "ASN1F_T61_STRING",
        "ASN1F_VIDEOTEX_STRING", "ASN1F_IA5_STRING",
        "ASN1F_GENERAL_STRING", "ASN1F_UTC_TIME", "ASN1F_GENERALIZED_TIME",
        "ASN1F_ISO646_STRING", "ASN1F_UNIVERSAL_STRING",
        "ASN1F_BMP_STRING", "ASN1F_SEQUENCE", "ASN1F_SET",
        "ASN1F_SEQUENCE_OF", "ASN1F_SET_OF", "ASN1F_IPADDRESS",
        "ASN1F_TIME_TICKS", "ASN1F_optional", "ASN1F_omit", "ASN1F_CHOICE",
        "ASN1F_PACKET", "ASN1F_BIT_STRING_ENCAPS", "ASN1F_FLAGS",
        "ASN1F_STRING_PacketField", "ASN1F_STRING_ENCAPS",
    ),
    "asn1packet": (
        "ASN1_Packet",
    ),
    "layers.snmp": (
        "ASN1_Class_SNMP", "ASN1_SNMP_PDU_GET",
        "ASN1_SNMP_PDU_NEXT", "ASN1_SNMP_PDU_RESPONSE",
        "ASN1_SNMP_PDU_SET", "ASN1_SNMP_PDU_TRAPv1", "ASN1_SNMP_PDU_BULK",
        "ASN1_SNMP_PDU_INFORM", "ASN1_SNMP_PDU_TRAPv2",
        "BERcodec_SNMP_PDU_GET", "BERcodec_SNMP_PDU_NEXT",
        "BERcodec_SNMP_PDU_RESPONSE", "BERcodec_SNMP_PDU_SET",
        "BERcodec_SNMP_PDU_TRAPv1", "BERcodec_SNMP_PDU_BULK",
        "BERcodec_SNMP_PDU_INFORM", "BERcodec_SNMP_PDU_TRAPv2",
        "ASN1F_SNMP_PDU_GET", "ASN1F_SNMP_PDU_NEXT",
        "ASN1F_SNMP_PDU_RESPONSE", "ASN1F_SNMP_PDU_SET",
        "ASN1F_SNMP_PDU_TRAPv1", "ASN1F_SNMP_PDU_BULK",
        "ASN1F_SNMP_PDU_INFORM", "ASN1F_SNMP_PDU_TRAPv2", "SNMPvarbind",
        "SNMPget", "SNMPnext", "SNMPresponse", "SNMPset", "SNMPtrapv1",
        "SNMPbulk", "SNMPinform", "SNMPtrapv2", "SNMP", "snmpget",
        "snmpwalk",
    ),
    "layers.x509": (
        "ASN1P_OID", "ASN1P_INTEGER", "ASN1P_PRIVSEQ", "RSAPublicKey",
        "RSAOtherPrimeInfo", "RSAPrivateKey", "ValidationParms",
        "DomainParameters", "DHPublicKey", "ECFieldID", "ECCurve",
        "ECSpecifiedDomain", "ECParameters", "ECDSAPublicKey",
        "ECDSAPrivateKey", "ECDSASignature", "DHParameter",
        "EdDSAPublicKey", "CurvePrivateKey", "EdDSAPrivateKey",
        "MLDSAPublicKey", "MLDSAPrivateKeySeed",
        "MLDSAPrivateKeyExpandedKey", "MLDSAPrivateKeyBoth",
        "MLDSAPrivateKey", "ASN1F_X509_DirectoryString",
        "X509_AttributeValue", "X509_Attribute",
        "X509_AttributeTypeAndValue", "X509_RDN", "X509_OtherName",
        "ASN1F_X509_otherName", "X509_RFC822Name", "X509_DNSName",
        "X509_X400Address", "X509_DirectoryName", "X509_EDIPartyName",
        "X509_URI", "X509_IPAddress", "X509_RegisteredID",
        "X509_GeneralName", "X509_ExtAuthorityKeyIdentifier",
        "X509_ExtSubjectDirectoryAttributes",
        "X509_ExtSubjectKeyIdentifier", "X509_ExtFullName",
        "X509_ExtNameRelativeToCRLIssuer", "X509_ExtDistributionPointName",
        "X509_ExtDistributionPoint", "X509_ExtKeyUsage",
        "X509_ExtPrivateKeyUsagePeriod", "X509_PolicyMapping",
        "X509_ExtPolicyMappings", "X509_ExtBasicConstraints",
        "X509_ExtCRLNumber", "X509_ExtReasonCode",
        "X509_ExtDeltaCRLIndicator", "X509_ExtIssuingDistributionPoint",
        "X509_ExtCertificateIssuer", "X509_ExtInvalidityDate",
        "X509_ExtSubjectAltName", "X509_ExtIssuerAltName",
        "X509_ExtGeneralSubtree", "X509_ExtNameConstraints",
        "X509_ExtPolicyConstraints", "X509_ExtExtendedKeyUsage",
        "X509_ExtNoticeReference", "X509_ExtUserNotice",
        "X509_ExtPolicyQualifierInfo", "X509_ExtPolicyInformation",
        "X509_ExtCertificatePolicies", "X509_ExtCRLDistributionPoints",
        "X509_ExtInhibitAnyPolicy", "X509_ExtFreshestCRL",
        "X509_AccessDescription", "X509_ExtAuthInfoAccess",
        "X509_ExtQcStatement", "X509_ExtQcStatements",
        "X509_ExtSubjInfoAccess", "X509_ExtNetscapeCertType",
        "X509_ExtComment", "X509_ExtCertificateTemplateName",
        "X509_ExtOidNTDSCaSecurity", "X509_ExtCertificateTemplateOID",
        "ASN1F_EXT_SEQUENCE", "X509_Extension", "X509_Extensions",
        "X509_AlgorithmIdentifier", "ASN1F_X509_PublicKeyField",
        "X509_SubjectPublicKeyInfo", "X509_OneAsymmetricKey",
        "RSAPrivateKey_OpenSSL", "ECDSAPrivateKey_OpenSSL",
        "X509_Validity", "X509_TBSCertificate", "ASN1F_X509_Cert",
        "X509_Cert", "X509_RevokedCertificate", "X509_TBSCertList",
        "ASN1F_X509_CRL", "X509_CRL", "CMS_EncapsulatedContentInfo",
        "CMS_RevocationInfoChoice", "CMS_CertificateChoices",
        "CMS_IssuerAndSerialNumber", "CMS_OtherKeyAttribute",
        "CMS_SubjectKeyIdentifier", "CMS_SignerInfo",
        "CMS_SignedAttrsForSignature", "CMS_SignedData",
        "CMS_KeyTransRecipientInfo", "CMS_OriginatorPublicKey",
        "CMS_OriginatorIdentifierOrKey", "CMS_RecipientEncryptedKey",
        "CMS_KeyAgreeRecipientInfo", "CMS_RecipientInfo",
        "CMS_OriginatorInfo", "CMS_EncryptedContentInfo",
        "CMS_EnvelopedData", "CMS_ContentInfo",
        "PKCS10_CertificationRequestInfo", "PKCS10_CertificationRequest",
        "CMC_TaggedAttribute", "CMC_TaggedCertificationRequest",
        "CMC_TaggedRequest", "CMC_TaggedContentInfo", "CMC_OtherMsg",
        "CMC_PKIData", "CMC_AddExtensions", "CMC_AddAttributes",
        "CMC_ENROLLMENT_CSP_PROVIDER", "CMC_REQUEST_CLIENT_INFO",
        "CMC_EnrollmentNameValuePair", "CMC_ENROLL_ATTESTATION_STATEMENT",
        "OCSP_CertID", "OCSP_GoodInfo", "OCSP_RevokedInfo",
        "OCSP_UnknownInfo", "OCSP_CertStatus", "OCSP_SingleResponse",
        "OCSP_ByName", "OCSP_ByKey", "OCSP_ResponderID",
        "OCSP_ResponseData", "ASN1F_OCSP_BasicResponse",
        "OCSP_ResponseBytes", "OCSP_Response",
    ),
    "layers.ldap": (
        "LDAPString", "LDAPOID", "LDAPDN", "RelativeLDAPDN",
        "AttributeType", "AttributeValue", "URI",
        "AttributeValueAssertion", "LDAPReferral", "LDAPResult",
        "ASN1_Class_LDAP", "ASN1_Class_LDAP_Authentication",
        "LDAP_Authentication_simple",
        "BERcodec_LDAP_Authentication_simple",
        "ASN1F_LDAP_Authentication_simple",
        "LDAP_Authentication_krbv42LDAP",
        "BERcodec_LDAP_Authentication_krbv42LDAP",
        "ASN1F_LDAP_Authentication_krbv42LDAP",
        "LDAP_Authentication_krbv42DSA",
        "BERcodec_LDAP_Authentication_krbv42DSA",
        "ASN1F_LDAP_Authentication_krbv42DSA",
        "LDAP_Authentication_sicilyPackageDiscovery",
        "BERcodec_LDAP_Authentication_sicilyPackageDiscovery",
        "ASN1F_LDAP_Authentication_sicilyPackageDiscovery",
        "LDAP_Authentication_sicilyNegotiate",
        "BERcodec_LDAP_Authentication_sicilyNegotiate",
        "ASN1F_LDAP_Authentication_sicilyNegotiate",
        "LDAP_Authentication_sicilyResponse",
        "BERcodec_LDAP_Authentication_sicilyResponse",
        "ASN1F_LDAP_Authentication_sicilyResponse",
        "LDAP_Authentication_SaslCredentials", "LDAP_BindRequest",
        "LDAP_BindResponse", "LDAP_UnbindRequest",
        "LDAP_SubstringFilterInitial", "LDAP_SubstringFilterAny",
        "LDAP_SubstringFilterFinal", "LDAP_SubstringFilterStr",
        "LDAP_SubstringFilter", "LDAP_FilterAnd", "LDAP_FilterOr",
        "LDAP_FilterNot", "LDAP_FilterPresent", "LDAP_FilterEqual",
        "LDAP_FilterGreaterOrEqual", "LDAP_FilterLessOrEqual",
        "LDAP_FilterApproxMatch", "LDAP_FilterExtensibleMatch",
        "ASN1_Class_LDAP_Filter", "LDAP_Filter",
        "LDAP_SearchRequestAttribute", "LDAP_SearchRequest",
        "LDAP_AttributeValue", "LDAP_PartialAttribute",
        "LDAP_SearchResponseEntry", "LDAP_SearchResponseResultDone",
        "LDAP_SearchResponseReference", "LDAP_ModifyRequestChange",
        "LDAP_ModifyRequest", "LDAP_ModifyResponse", "LDAP_Attribute",
        "LDAP_AddRequest", "LDAP_AddResponse", "LDAP_DelRequest",
        "LDAP_DelResponse", "LDAP_ModifyDNRequest",
        "LDAP_ModifyDNResponse", "LDAP_AbandonRequest",
        "LDAP_ExtendedResponse", "LDAP_Control",
        "LDAP_realSearchControlValue", "LDAP_serverSDFlagsControl", "LDAP",
        "CLDAP", "LDAP_PROPERTY_SET", "LDAP_CONTROL_ACCESS_RIGHTS",
        "LDAP_DS_ACCESS_RIGHTS", "LDAP_SASL_Buffer",
    ),
    "layers.gssapi": (
        "ASN1_Class_GSSAPI", "ASN1_GSSAPI_APPLICATION",
        "BERcodec_GSSAPI_APPLICATION", "ASN1F_GSSAPI_APPLICATION",
        "GSSAPI_BLOB", "GSSAPI_BLOB_SIGNATURE", "GSS_C_QOP_DEFAULT",
        "GSS_C_NO_CHANNEL_BINDINGS", "GSS_S_COMPLETE",
        "GSS_C_CALLING_ERROR_OFFSET", "GSS_C_ROUTINE_ERROR_OFFSET",
        "GSS_C_SUPPLEMENTARY_OFFSET", "GSS_S_CALL_INACCESSIBLE_READ",
        "GSS_S_CALL_INACCESSIBLE_WRITE", "GSS_S_CALL_BAD_STRUCTURE",
        "GSS_S_BAD_MECH", "GSS_S_BAD_NAME", "GSS_S_BAD_NAMETYPE",
        "GSS_S_BAD_BINDINGS", "GSS_S_BAD_STATUS", "GSS_S_BAD_SIG",
        "GSS_S_BAD_MIC", "GSS_S_NO_CRED", "GSS_S_NO_CONTEXT",
        "GSS_S_DEFECTIVE_TOKEN", "GSS_S_DEFECTIVE_CREDENTIAL",
        "GSS_S_CREDENTIALS_EXPIRED", "GSS_S_CONTEXT_EXPIRED",
        "GSS_S_FAILURE", "GSS_S_BAD_QOP", "GSS_S_UNAUTHORIZED",
        "GSS_S_UNAVAILABLE", "GSS_S_DUPLICATE_ELEMENT",
        "GSS_S_NAME_NOT_MN", "GSS_S_CONTINUE_NEEDED",
        "GSS_S_DUPLICATE_TOKEN", "GSS_S_OLD_TOKEN", "GSS_S_UNSEQ_TOKEN",
        "GSS_S_GAP_TOKEN", "ChannelBindingType", "GssBufferDesc",
        "GssChannelBindings", "GSS_C_FLAGS", "GSS_S_FLAGS",
        "GSS_QOP_REQ_FLAGS", "SSP",
    ),
    "layers.ntlm": (
        "NTLM_VARIANT", "NTLM_Header", "NTLM_NEGOTIATE",
        "Single_Host_Data", "AV_PAIR", "NTLM_CHALLENGE", "LM_RESPONSE",
        "LMv2_RESPONSE", "NTLM_RESPONSE", "NTLMv2_CLIENT_CHALLENGE",
        "NTLMv2_RESPONSE", "NTLM_AUTHENTICATE", "NTLM_AUTHENTICATE_V2",
        "HTTP_ntlm_negotiate", "NEGOEX_EXCHANGE_NTLM_ITEM",
        "NEGOEX_EXCHANGE_NTLM", "HMAC_MD5", "MD4le", "RC4Init", "RC4",
        "RC4K", "NTLMSSP_MESSAGE_SIGNATURE", "NTOWFv2",
        "NTLMv2_ComputeSessionBaseKey", "MAC", "SIGN", "SEAL", "UNSEAL",
        "SIGNKEY", "SEALKEY", "NTLMSSP", "NTLMSSP_DOMAIN",
    ),
    "layers.kerberos": (
        "ASN1_Class_KRB", "KerberosString", "Realm", "Int32", "UInt32",
        "PrincipalName", "KerberosTime", "Microseconds", "EncryptedData",
        "EncryptionKey", "Checksum", "KerberosFlags", "HostAddress",
        "HostAddresses", "AuthorizationDataItem", "AuthorizationData",
        "AD_IF_RELEVANT", "AD_KDCIssued", "AD_AND_OR", "ADMANDATORYFORKDC",
        "PADATA", "PA_ENC_TS_ENC", "ETYPE_INFO_ENTRY", "ETYPE_INFO",
        "ETYPE_INFO_ENTRY2", "ETYPE_INFO2", "TD_CMS_DIGEST_ALGORITHMS",
        "PA_AUTHENTICATION_SET_ELEM", "PA_AUTHENTICATION_SET",
        "PA_PAC_REQUEST", "LSAP_TOKEN_INFO_INTEGRITY",
        "KERB_AD_RESTRICTION_ENTRY", "KERB_AUTH_DATA_AP_OPTIONS",
        "KERB_AUTH_DATA_CLIENT_TARGET", "KERB_AD_LOGIN_ALIAS",
        "PA_SUPPORTED_ENCTYPES", "PA_PAC_OPTIONS", "KERB_KEY_LIST_REQ",
        "KERB_KEY_LIST_REP", "KERB_SUPERSEDED_BY_USER",
        "KERB_DMSA_KEY_PACKAGE", "KrbFastArmor", "KrbFastArmoredReq",
        "PA_FX_FAST_REQUEST", "KrbFastArmoredRep", "PA_FX_FAST_REPLY",
        "KrbFastFinished", "KrbFastResponse",
        "ExternalPrincipalIdentifier", "PA_PK_AS_REQ", "PAChecksum2",
        "KRB_PKAuthenticator", "KDFAlgorithmId", "KRB_AuthPack",
        "DHRepInfo", "EncKeyPack", "PA_PK_AS_REP", "KDCDHKeyInfo",
        "PA_FOR_USER", "S4UUserID", "PA_S4U_X509_USER", "KRB_MSG_TYPES",
        "KRB_Ticket", "TransitedEncoding", "EncTicketPart",
        "KRB_KDC_REQ_BODY", "KRB_KDC_REQ", "KrbFastReq", "KRB_AS_REQ",
        "KRB_TGS_REQ", "KRB_KDC_REP", "KRB_AS_REP", "KRB_TGS_REP",
        "LastReqItem", "EncKDCRepPart", "EncASRepPart", "EncTGSRepPart",
        "KRB_AP_REQ", "KRB_Authenticator", "KRB_AP_REP", "EncAPRepPart",
        "KRB_PRIV", "EncKrbPrivPart", "KRB_CRED", "KrbCredInfo",
        "EncKrbCredPart", "MethodData", "KRB_ERROR", "KERB_EXT_ERROR",
        "KERB_EXT_ERROR_NTSTATUS", "KERB_ERROR_DATA", "KERB_ERROR_UNK",
        "KRB_TGT_REQ", "KRB_TGT_REP", "KRB_FINISHED", "KRB_GSS_EXT",
        "KRB_AuthenticatorChecksum", "KRB_InnerToken", "KRB_GSSAPI_Token",
        "KRB_GSS_MIC_RFC1964", "KRB_GSS_Wrap_RFC1964",
        "KRB_GSS_Delete_sec_context_RFC1964", "KRB_GSS_MIC",
        "KRB_GSS_Wrap", "IAKERB_HEADER", "Kerberos", "KerberosTCPHeader",
        "KPASSWD_REQ", "ChangePasswdData", "KPASSWD_REP",
        "KPASSWD_RESULTS", "DOMAIN_PASSWORD_INFORMATION", "KPasswdResult",
        "KPasswdRepData", "Kpasswd", "KpasswdTCPHeader",
        "KDC_PROXY_MESSAGE", "KdcProxySocket", "IAKerbSocket",
        "PKINIT_KEX_METHOD", "KerberosClient", "krb_as_req", "krb_tgs_req",
        "krb_as_and_tgs", "krb_get_salt", "kpasswd", "KerberosSSP",
    ),
    "layers.dhcp6": (
        "IP6ListField", "DomainNameListField", "dns_get_str", "dns_encode",
        "DNSStrField", "dhcp6_cls_by_type",
        "All_DHCP_Relay_Agents_and_Servers", "All_DHCP_Servers", "dhcp6opts",
        "dhcp6opts_by_code", "dhcp6types", "duidtypes", "duidhwtypes",
        "DUID_LLT", "DUID_EN", "DUID_LL", "DUID_UUID", "duid_cls",
        "DHCP6OptUnknown", "DHCP6OptClientId", "DHCP6OptServerId",
        "DHCP6OptIAAddress", "DHCP6OptIA_NA", "DHCP6OptIA_TA",
        "DHCP6OptOptReq", "DHCP6OptPref", "DHCP6OptElapsedTime",
        "DHCP6OptAuth", "DHCP6OptServerUnicast", "dhcp6statuscodes",
        "DHCP6OptStatusCode", "DHCP6OptRapidCommit", "USER_CLASS_DATA",
        "DHCP6OptUserClass", "VENDOR_CLASS_DATA", "DHCP6OptVendorClass",
        "VENDOR_SPECIFIC_OPTION", "DHCP6OptVendorSpecificInfo",
        "DHCP6OptIfaceId", "DHCP6OptReconfMsg", "DHCP6OptReconfAccept",
        "DHCP6OptSIPDomains", "DHCP6OptSIPServers", "DHCP6OptDNSServers",
        "DHCP6OptDNSDomains", "DHCP6OptIAPrefix", "DHCP6OptIA_PD",
        "DHCP6OptNISServers", "DHCP6OptNISPServers", "DHCP6OptNISDomain",
        "DHCP6OptNISPDomain", "DHCP6OptSNTPServers", "IRT_DEFAULT",
        "IRT_MINIMUM", "DHCP6OptInfoRefreshTime", "DHCP6OptBCMCSDomains",
        "DHCP6OptBCMCSServers", "DHCP6OptGeoConfElement", "DHCP6OptGeoConf",
        "DHCP6OptRemoteID", "DHCP6OptSubscriberID", "DHCP6OptClientFQDN",
        "DHCP6OptPanaAuthAgent", "DHCP6OptNewPOSIXTimeZone",
        "DHCP6OptNewTZDBTimeZone", "DHCP6OptRelayAgentERO",
        "DHCP6OptLQClientLink", "DHCP6NTPSubOptSrvAddr",
        "DHCP6NTPSubOptMCAddr", "DHCP6NTPSubOptSrvFQDN", "DHCP6OptNTPServer",
        "DHCP6OptBootFileUrl", "DHCP6OptClientArchType",
        "DHCP6OptClientNetworkInterId", "DHCP6OptERPDomain",
        "DHCP6OptRelaySuppliedOpt", "DHCP6OptVSS",
        "DHCP6OptClientLinkLayerAddr", "DHCP6OptCaptivePortal",
        "DHCP6OptMudUrl", "DHCP6OptAddrRegEnable",
        "DHCP6RelayAgentUnicastAddr", "DHCP6RelayHopCount",
        "DHCP6ServerUnicastAddr", "DHCP6ClientUnicastAddr", "DHCP6ClientIA_TA",
        "DHCP6ClientIA_NA", "DHCP6ClientIAID", "T1", "T2", "DHCP6ServerDUID",
        "DHCP6CurrentTransactionID", "DHCP6PrefVal", "DHCP6",
        "DHCP6OptRelayMsg", "DHCP6_Solicit", "DHCP6_Advertise",
        "DHCP6_Request", "DHCP6_Confirm", "DHCP6_Renew", "DHCP6_Rebind",
        "DHCP6_Reply", "DHCP6_Release", "DHCP6_Decline", "DHCP6_Reconf",
        "DHCP6_InfoRequest", "DHCP6_RelayForward", "DHCP6_RelayReply",
        "DHCP6_AddrRegInform", "DHCP6_AddrRegReply", "DHCPv6_am", "dhcp6d",
    ),
}

# Rust layers whose scapy contract is a tree of Python objects. The Rust layer
# stays in the dissection chain, so a capture of them is found, counted and
# filtered without Python; the name exported is the Python model.
PY_MODELLED = {
    "SNMP": "layers.snmp", "LDAP": "layers.ldap", "DHCP6": "layers.dhcp6",
}

# Where scapy splits one Rust layer into a class per variant, the function
# that picks the class. Such a layer is built as Raw octets under the layer
# below it, since the Rust layer's own fields cannot hold the whole message.
PY_DECODER = {"DHCP6": "_dhcp6_dispatcher"}
