//! RFC 4302 §2: an Authentication Header is a one-octet Next Header, a one-octet
//! Payload Length giving the header size in 32-bit words minus two, a reserved
//! 16-bit field, a 32-bit Security Parameters Index, a 32-bit Sequence Number and
//! a variable Integrity Check Value. Next Header values come from the IANA
//! "Protocol Numbers" registry, so the protocol the header covers is dissected
//! after it.
//!
//! Generated by dev/protogen from dev/protogen/specs/ah.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{Next, ProtoDesc, ProtoId};

// protogen:hand begin
/// RFC 4302 §2.2: Payload Length is the whole header in 32-bit words, minus
/// two.
fn header_len(hdr: &[u8]) -> usize {
    match hdr.get(1) {
        Some(n) => (*n as usize + 2) * 4,
        None => 12,
    }
}

fn next(hdr: &[u8]) -> Next {
    let Some(nh) = hdr.first().copied() else {
        return Next::Raw;
    };
    match nh {
        1 => Next::Proto(ProtoId::Icmp),
        6 => Next::Proto(ProtoId::Tcp),
        17 => Next::Proto(ProtoId::Udp),
        58 => Next::Proto(ProtoId::Icmpv6),
        _ => match crate::layers::dispatch::by_ipproto(nh) {
            Some(p) => Next::Proto(p),
            None => Next::Raw,
        },
    }
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("nh", 0, 8, 0),
    FieldDesc::uint("payloadlen", 8, 8, 4),
    FieldDesc::uint("reserved", 16, 16, 0),
    FieldDesc::uint("spi", 32, 32, 0),
    FieldDesc::uint("seq", 64, 32, 0),
];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Ah,
    name: "AH",
    fields: FIELDS,
    min_len: 12,
    header_len,
    next,
    build_len: 12,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 4302 §2, hand-built: next header TCP (6), payload length 4 giving a 24-octet header, 12 octets of ICV.
    fn vector() -> Vec<u8> {
        vec![
            0x06, 0x04, 0x00, 0x00, 0x11, 0x22, 0x33, 0x44, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Ah);
        let l = p.find_layer(ProtoId::Ah).unwrap();
        assert_eq!(p.get(l, "nh").unwrap(), FieldValue::Uint(6));
        assert_eq!(p.get(l, "payloadlen").unwrap(), FieldValue::Uint(4));
        assert_eq!(p.get(l, "reserved").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "spi").unwrap(), FieldValue::Uint(287454020));
        assert_eq!(p.get(l, "seq").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Ah);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Ah);
        let l = p.find_layer(ProtoId::Ah).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Ah, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
