// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/contrib/bgp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-09-18 — BGPRouteRefresh's field table transcribed; checked against RFC 2918 §3 and RFC 7313 §3

//! RFC 2918 §3, ROUTE-REFRESH message: a 16-bit Address Family Identifier, a
//! reserved octet and a one-octet Subsequent Address Family Identifier. RFC 7313
//! §3 reuses the reserved octet as a message subtype (0 normal, 1 BoRR, 2 EoRR)
//! and lets an Outbound Route Filtering payload follow, which stays opaque.
//! Identifiers from the IANA "Address Family Numbers" and "SAFI Values"
//! registries.
//!
//! Generated by dev/protogen from dev/protogen/specs/bgp_route_refresh.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("afi", 0, 16, 1),
    FieldDesc::uint("subtype", 16, 8, 0),
    FieldDesc::uint("safi", 24, 8, 1),
];

fn header_len(_: &[u8]) -> usize {
    4
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::BgpRouteRefresh,
    name: "BGPRouteRefresh",
    fields: FIELDS,
    min_len: 4,
    header_len,
    next: crate::proto::next_raw,
    build_len: 4,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 2918 §3 ROUTE-REFRESH for IPv4 unicast.
    fn vector() -> Vec<u8> {
        vec![0x00, 0x01, 0x00, 0x01]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::BgpRouteRefresh);
        let l = p.find_layer(ProtoId::BgpRouteRefresh).unwrap();
        assert_eq!(p.get(l, "afi").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "subtype").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "safi").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::BgpRouteRefresh);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::BgpRouteRefresh);
        let l = p.find_layer(ProtoId::BgpRouteRefresh).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::BgpRouteRefresh, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
