// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/contrib/bgp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-09-18 — BGPUpdate's field order, BGPPathAttr's flags/type/length rule with its Extended-Length bit, and the path_attributes code table transcribed; the three regions answer one item list rather than three PacketListFields. Checked against RFC 4271 §4.3

//! RFC 4271 §4.3, UPDATE message: a 16-bit count of withdrawn-route octets, that
//! many withdrawn routes, a 16-bit count of path-attribute octets, that many path
//! attributes, and then the Network Layer Reachability Information to the end of
//! the message. §4.3 encodes a route as a one-octet prefix length in *bits*
//! followed by the smallest number of octets that holds it, and a path attribute
//! as an attribute-flags octet, a type octet and a length that is one octet, or
//! two when the flags' Extended Length bit (0x10) is set.
//!
//! Three variable regions in sequence, two of them at offsets no earlier field
//! fixes, is outside the flat table and outside the repeating-group construct
//! alike, so the whole body past `withdrawn_routes_len` is one variable field and
//! the walk over it is hand-written. It answers one list under `body`, whose item
//! names say which of the three regions each came from: `withdrawn` for a
//! withdrawn prefix, the RFC 4271 §5 attribute name (or its code) for a path
//! attribute, and `nlri` for an advertised prefix. Path attribute *values* are
//! kept as octets: their layout varies by type code — DEVIATIONS E1.
//!
//! Generated by dev/protogen from dev/protogen/specs/bgp_update.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
use crate::options::{Item, ItemValue};

/// Every walk here is over an attacker-controlled length, so each is bounded
/// and each returns what it managed.
const MAX_ITEMS: usize = 512;

fn be16(b: &[u8], at: usize) -> usize {
    match b.get(at..at + 2) {
        Some(w) => u16::from_be_bytes([w[0], w[1]]) as usize,
        None => 0,
    }
}

/// RFC 4271 §5 path attribute type codes, and RFC 1997, 4456, 4760, 4360,
/// 6793, 7311 and 8092 for the ones registered since.
fn attr_name(code: u8) -> Option<&'static str> {
    Some(match code {
        1 => "ORIGIN",
        2 => "AS_PATH",
        3 => "NEXT_HOP",
        4 => "MULTI_EXIT_DISC",
        5 => "LOCAL_PREF",
        6 => "ATOMIC_AGGREGATE",
        7 => "AGGREGATOR",
        8 => "COMMUNITY",
        9 => "ORIGINATOR_ID",
        10 => "CLUSTER_LIST",
        14 => "MP_REACH_NLRI",
        15 => "MP_UNREACH_NLRI",
        16 => "EXTENDED COMMUNITIES",
        17 => "AS4_PATH",
        18 => "AS4_AGGREGATOR",
        26 => "AIGP",
        32 => "LARGE_COMMUNITY",
        _ => return None,
    })
}

/// RFC 4271 §4.3: a prefix is a length in bits and only the octets that hold
/// it. Rendered the way an address leaves the engine everywhere else.
fn prefixes(region: &[u8], name: &'static str, out: &mut Vec<Item>) {
    let mut i = 0usize;
    while i < region.len() && out.len() < MAX_ITEMS {
        let bits = region[i] as usize;
        if bits > 32 {
            break;
        }
        let octets = bits.div_ceil(8);
        let Some(p) = region.get(i + 1..i + 1 + octets) else {
            break;
        };
        let mut a = [0u8; 4];
        a[..octets].copy_from_slice(p);
        out.push(Item::named(
            name,
            bits as u32,
            ItemValue::Text(format!("{}.{}.{}.{}/{}", a[0], a[1], a[2], a[3], bits)),
        ));
        i += 1 + octets;
    }
}

/// §4.3: the length is two octets rather than one when the Extended Length bit
/// is set, so reading it with the wrong width mis-decodes every attribute
/// after the first rather than failing.
fn attributes(region: &[u8], out: &mut Vec<Item>) {
    let mut i = 0usize;
    while i + 3 <= region.len() && out.len() < MAX_ITEMS {
        let flags = region[i];
        let code = region[i + 1];
        let wide = flags & 0x10 != 0;
        let (hdr, len) = if wide {
            (4, be16(region, i + 2))
        } else {
            (3, region[i + 2] as usize)
        };
        let Some(v) = region.get(i + hdr..i + hdr + len) else {
            break;
        };
        out.push(match attr_name(code) {
            Some(n) => Item::bytes(n, code as u32, v),
            None => Item::unknown(code as u32, v),
        });
        i += hdr + len;
    }
}

fn parse_options(hdr: &[u8]) -> Vec<Item> {
    let mut out = Vec::new();
    let wlen = be16(hdr, 0);
    let Some(withdrawn) = hdr.get(2..2 + wlen) else {
        return out;
    };
    prefixes(withdrawn, "withdrawn", &mut out);
    let at = 2 + wlen;
    let alen = be16(hdr, at);
    let Some(attrs) = hdr.get(at + 2..at + 2 + alen) else {
        return out;
    };
    attributes(attrs, &mut out);
    prefixes(hdr.get(at + 2 + alen..).unwrap_or(&[]), "nlri", &mut out);
    out
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("withdrawn_routes_len", 0, 16, 0),
    FieldDesc::var_bytes("body", 16),
];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::BgpUpdate,
    name: "BGPUpdate",
    fields: FIELDS,
    min_len: 4,
    header_len: crate::proto::header_len_rest,
    next: crate::proto::next_end,
    build_len: 4,
    parse_options: Some(parse_options),
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 4271 §4.3 UPDATE, hand-built: no withdrawn routes, ORIGIN=IGP and NEXT_HOP=10.0.0.1, advertising 192.168.1.0/24.
    fn vector() -> Vec<u8> {
        vec![
            0x00, 0x00, 0x00, 0x0b, 0x40, 0x01, 0x01, 0x00, 0x40, 0x03, 0x04, 0x0a, 0x00, 0x00,
            0x01, 0x18, 0xc0, 0xa8, 0x01,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::BgpUpdate);
        let l = p.find_layer(ProtoId::BgpUpdate).unwrap();
        assert_eq!(
            p.get(l, "withdrawn_routes_len").unwrap(),
            FieldValue::Uint(0)
        );
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::BgpUpdate);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::BgpUpdate);
        let l = p.find_layer(ProtoId::BgpUpdate).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::BgpUpdate, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }

    #[test]
    fn path_attributes_and_nlri_read_under_one_list() {
        let p = Packet::dissect(vector(), ProtoId::BgpUpdate);
        let l = p.find_layer(ProtoId::BgpUpdate).unwrap();
        let items = p.options(l).unwrap();
        assert_eq!(
            items.iter().map(|i| i.name.as_ref()).collect::<Vec<_>>(),
            vec!["ORIGIN", "NEXT_HOP", "nlri"]
        );
        assert_eq!(items[0].value, ItemValue::Bytes(vec![0]));
        assert_eq!(items[1].value, ItemValue::Bytes(vec![10, 0, 0, 1]));
        assert_eq!(items[2].value, ItemValue::Text("192.168.1.0/24".into()));
    }

    /// RFC 4271 §4.3: the Extended Length bit widens the length octet, and
    /// reading it at the wrong width mis-decodes every attribute after it.
    #[test]
    fn an_extended_length_attribute_is_read_at_two_octets() {
        let mut data = vec![0u8, 0, 0, 9, 0x50, 0x0e, 0x00, 0x05, 1, 2, 3, 4, 5];
        data.extend_from_slice(&[0x08, 0x0a]);
        let p = Packet::dissect(data, ProtoId::BgpUpdate);
        let l = p.find_layer(ProtoId::BgpUpdate).unwrap();
        let items = p.options(l).unwrap();
        assert_eq!(items[0].name, "MP_REACH_NLRI");
        assert_eq!(items[0].value, ItemValue::Bytes(vec![1, 2, 3, 4, 5]));
        assert_eq!(items[1].value, ItemValue::Text("10.0.0.0/8".into()));
    }

    #[test]
    fn withdrawn_routes_are_named_apart_from_advertised_ones() {
        let data = vec![0u8, 3, 0x10, 0x0a, 0x00, 0x00, 0x00];
        let p = Packet::dissect(data, ProtoId::BgpUpdate);
        let l = p.find_layer(ProtoId::BgpUpdate).unwrap();
        let items = p.options(l).unwrap();
        assert_eq!(items.len(), 1);
        assert_eq!(items[0].name, "withdrawn");
        assert_eq!(items[0].value, ItemValue::Text("10.0.0.0/16".into()));
    }

    #[test]
    fn a_prefix_length_no_address_can_hold_stops_the_walk() {
        let data = vec![0u8, 0, 0, 0, 0xff, 1, 2, 3, 4];
        let p = Packet::dissect(data, ProtoId::BgpUpdate);
        let l = p.find_layer(ProtoId::BgpUpdate).unwrap();
        assert!(p.options(l).unwrap().is_empty());
    }
    // protogen:tests end
}
