// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth4LE.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of LL_VERSION_IND converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth4LE.py, class LL_VERSION_IND (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth4LE/ll_version_ind.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("version", 0, 8, 8).named(&[
        (6, "4.0"),
        (7, "4.1"),
        (8, "4.2"),
        (9, "5.0"),
        (10, "5.1"),
        (11, "5.2"),
    ]),
    FieldDesc::le_uint("company", 8, 16, 0).named(&[
        (15, "Broadcom Corporation"),
        (89, "Nordic Semiconductor ASA"),
    ]),
    FieldDesc::le_uint("subversion", 24, 16, 0),
];

fn header_len(_: &[u8]) -> usize {
    5
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::LLVERSIONIND,
    name: "LL_VERSION_IND",
    fields: FIELDS,
    min_len: 5,
    header_len,
    next: crate::proto::next_raw,
    build_len: 5,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
