// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth4LE.py
//   scapy 2.8.0.post0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of BTLE_DATA converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth4LE.py, class BTLE_DATA (scapy 2.8.0.post0), converted
//! by dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth4LE/btle_data.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("RFU", 0, 3, 0),
    FieldDesc::uint("MD", 3, 1, 0),
    FieldDesc::uint("SN", 4, 1, 0),
    FieldDesc::uint("NESN", 5, 1, 0),
    FieldDesc::uint("LLID", 6, 2, 0).named(&[(1, "continue"), (2, "start"), (3, "control")]),
    FieldDesc::uint("len", 8, 8, 0).recomputed(),
];

fn header_len(_: &[u8]) -> usize {
    2
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::BTLEDATA,
    name: "BTLE_DATA",
    fields: FIELDS,
    min_len: 2,
    header_len,
    next: crate::proto::next_raw,
    build_len: 2,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
