// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth.py
//   scapy 2.8.0.post0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of EIR_Flags converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth.py, class EIR_Flags (scapy 2.8.0.post0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth/eir_flags.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[FieldDesc::flags(
    "flags",
    0,
    8,
    &[
        "limited_disc_mode",
        "general_disc_mode",
        "br_edr_not_supported",
        "simul_le_br_edr_ctrl",
        "simul_le_br_edr_host",
        "reserved",
        "reserved",
        "reserved",
    ],
)
.with_default(2)];

fn header_len(_: &[u8]) -> usize {
    1
}

fn content_len(_: &[u8]) -> usize {
    1
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::EIRFlags,
    name: "EIR_Flags",
    fields: FIELDS,
    min_len: 1,
    header_len,
    next: crate::proto::next_end,
    build_len: 1,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
