// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of HCI_Cmd_Hold_Mode converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth.py, class HCI_Cmd_Hold_Mode (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth/hci_cmd_hold_mode.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::le_uint("connection_handle", 0, 16, 0),
    FieldDesc::le_uint("hold_mode_max_interval", 16, 16, 2),
    FieldDesc::le_uint("hold_mode_min_interval", 32, 16, 2),
];

fn header_len(_: &[u8]) -> usize {
    6
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::HCICmdHoldMode,
    name: "HCI_Cmd_Hold_Mode",
    fields: FIELDS,
    min_len: 6,
    header_len,
    next: crate::proto::next_raw,
    build_len: 6,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
