// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of EIR_Appearance converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth.py, class EIR_Appearance (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth/eir_appearance.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("category", 0, 10, 0)
        .little_endian(0, 2)
        .named(&[
            (0, "Unknown"),
            (1, "Phone"),
            (2, "Computer"),
            (3, "Watch"),
            (4, "Clock"),
            (5, "Display"),
            (6, "Remote Control"),
            (7, "Eyeglasses"),
            (8, "Tag"),
            (9, "Keyring"),
            (10, "Media Player"),
            (11, "Barcode Scanner"),
            (12, "Thermometer"),
            (13, "Heart Rate Sensor"),
            (14, "Blood Pressure"),
            (15, "Human Interface Device"),
            (16, "Glucose Meter"),
            (17, "Running Walking Sensor"),
            (18, "Cycling"),
            (19, "Control Device"),
            (20, "Network Device"),
            (21, "Sensor"),
            (22, "Light Fixtures"),
            (23, "Fan"),
            (24, "HVAC"),
            (25, "Air Conditioning"),
            (26, "Humidifier"),
            (27, "Heating"),
            (28, "Access Control"),
            (29, "Motorized Device"),
            (30, "Power Device"),
            (31, "Light Source"),
            (32, "Window Covering"),
            (33, "Audio Sink"),
            (34, "Audio Source"),
            (35, "Motorized Vehicle"),
            (36, "Domestic Appliance"),
            (37, "Wearable Audio Device"),
            (38, "Aircraft"),
            (39, "AV Equipment"),
            (40, "Display Equipment"),
            (41, "Hearing aid"),
            (42, "Gaming"),
            (43, "Signage"),
            (49, "Pulse Oximeter"),
            (50, "Weight Scale"),
            (51, "Personal Mobility Device"),
            (52, "Continuous Glucose Monitor"),
            (53, "Insulin Pump"),
            (54, "Medication Delivery"),
            (55, "Spirometer"),
            (81, "Outdoor Sports Activity"),
        ]),
    FieldDesc::uint("subcategory", 10, 6, 0).little_endian(0, 2),
];

fn header_len(_: &[u8]) -> usize {
    2
}

fn content_len(_: &[u8]) -> usize {
    2
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::EIRAppearance,
    name: "EIR_Appearance",
    fields: FIELDS,
    min_len: 2,
    header_len,
    next: crate::proto::next_end,
    build_len: 2,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
