// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of HCI_Mon_New_Index converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth.py, class HCI_Mon_New_Index (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth/hci_mon_new_index.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("bus", 0, 8, 0).named(&[(0, "BR/EDR"), (1, "AMP")]),
    FieldDesc::uint("type", 8, 8, 0).named(&[
        (0, "Virtual"),
        (1, "USB"),
        (2, "PC Card"),
        (3, "UART"),
        (4, "RS232"),
        (5, "PCI"),
        (6, "SDIO"),
    ]),
    FieldDesc::mac("addr", 16).little_endian(2, 6),
    FieldDesc::bytes("devname", 64, 64),
];

fn header_len(_: &[u8]) -> usize {
    16
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::HCIMonNewIndex,
    name: "HCI_Mon_New_Index",
    fields: FIELDS,
    min_len: 16,
    header_len,
    next: crate::proto::next_raw,
    build_len: 16,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
