// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth4LE.py
//   scapy 2.8.0.post0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of BTLE_CONNECT_REQ converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth4LE.py, class BTLE_CONNECT_REQ (scapy 2.8.0.post0),
//! converted by dev/protogen/scapy2spec.py from the field objects scapy builds at
//! run time. scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth4LE/btle_connect_req.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::mac("InitA", 0).little_endian(0, 6),
    FieldDesc::mac("AdvA", 48).little_endian(6, 6),
    FieldDesc::le_uint("AA", 96, 32, 0),
    FieldDesc::le_uint("crc_init", 128, 24, 0),
    FieldDesc::uint("win_size", 152, 8, 0),
    FieldDesc::le_uint("win_offset", 160, 16, 0),
    FieldDesc::le_uint("interval", 176, 16, 0),
    FieldDesc::le_uint("latency", 192, 16, 0),
    FieldDesc::le_uint("timeout", 208, 16, 0),
    FieldDesc::le_uint("chM", 224, 40, 0),
    FieldDesc::uint("SCA", 264, 3, 0),
    FieldDesc::uint("hop", 267, 5, 0),
];

fn header_len(_: &[u8]) -> usize {
    34
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::BTLECONNECTREQ,
    name: "BTLE_CONNECT_REQ",
    fields: FIELDS,
    min_len: 34,
    header_len,
    next: crate::proto::next_raw,
    build_len: 34,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
