// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of HCI_Cmd_Periodic_Inquiry_Mode converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth.py, class HCI_Cmd_Periodic_Inquiry_Mode (scapy 2.7.0),
//! converted by dev/protogen/scapy2spec.py from the field objects scapy builds at
//! run time. scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth/hci_cmd_periodic_inquiry_mode.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::le_uint("max_period_length", 0, 16, 3),
    FieldDesc::le_uint("min_period_length", 16, 16, 2),
    FieldDesc::le_uint("lap", 32, 24, 10390323),
    FieldDesc::uint("inquiry_length", 56, 8, 0),
    FieldDesc::uint("num_responses", 64, 8, 0),
];

fn header_len(_: &[u8]) -> usize {
    9
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::HCICmdPeriodicInquiryMode,
    name: "HCI_Cmd_Periodic_Inquiry_Mode",
    fields: FIELDS,
    min_len: 9,
    header_len,
    next: crate::proto::next_raw,
    build_len: 9,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
