// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth4LE.py
//   scapy 2.8.0.post0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of BTLE_CTRL converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth4LE.py, class BTLE_CTRL (scapy 2.8.0.post0), converted
//! by dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth4LE/btle_ctrl.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[FieldDesc::uint("opcode", 0, 8, 0).named(&[
    (0, "LL_CONNECTION_UPDATE_REQ"),
    (1, "LL_CHANNEL_MAP_REQ"),
    (2, "LL_TERMINATE_IND"),
    (3, "LL_ENC_REQ"),
    (4, "LL_ENC_RSP"),
    (5, "LL_START_ENC_REQ"),
    (6, "LL_START_ENC_RSP"),
    (7, "LL_UNKNOWN_RSP"),
    (8, "LL_FEATURE_REQ"),
    (9, "LL_FEATURE_RSP"),
    (10, "LL_PAUSE_ENC_REQ"),
    (11, "LL_PAUSE_ENC_RSP"),
    (12, "LL_VERSION_IND"),
    (13, "LL_REJECT_IND"),
    (14, "LL_SLAVE_FEATURE_REQ"),
    (15, "LL_CONNECTION_PARAM_REQ"),
    (16, "LL_CONNECTION_PARAM_RSP"),
    (20, "LL_LENGTH_REQ"),
    (21, "LL_LENGTH_RSP"),
    (22, "LL_PHY_REQ"),
    (23, "LL_PHY_RSP"),
    (24, "LL_PHY_UPDATE_IND"),
    (25, "LL_MIN_USED_CHANNELS"),
    (26, "LL_CTE_REQ"),
    (27, "LL_CTE_RSP"),
    (28, "LL_PERIODIC_SYNC_IND"),
    (29, "LL_CLOCK_ACCURACY_REQ"),
    (30, "LL_CLOCK_ACCURACY_RSP"),
    (31, "LL_CIS_REQ"),
    (32, "LL_CIS_RSP"),
    (33, "LL_CIS_IND"),
    (34, "LL_CIS_TERMINATE_IND"),
    (35, "LL_POWER_CONTROL_REQ"),
    (36, "LL_POWER_CONTROL_RSP"),
    (37, "LL_POWER_CHANGE_IND"),
    (38, "LL_SUBRATE_REQ"),
    (39, "LL_SUBRATE_IND"),
    (40, "LL_CHANNEL_REPORTING_IND"),
    (41, "LL_CHANNEL_STATUS_IND"),
])];

fn header_len(_: &[u8]) -> usize {
    1
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::BTLECTRL,
    name: "BTLE_CTRL",
    fields: FIELDS,
    min_len: 1,
    header_len,
    next: crate::proto::next_raw,
    build_len: 1,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
