// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth4LE.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of LL_CIS_REQ converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth4LE.py, class LL_CIS_REQ (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth4LE/ll_cis_req.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("cig_id", 0, 8, 0),
    FieldDesc::uint("cis_id", 8, 8, 0),
    FieldDesc::flags("phy_c_to_p", 16, 8, &["phy_1m", "phy_2m", "phy_coded"]),
    FieldDesc::flags("phy_p_to_c", 24, 8, &["phy_1m", "phy_2m", "phy_coded"]),
    FieldDesc::uint("max_sdu_c_to_p", 36, 12, 0).little_endian(4, 2),
    FieldDesc::uint("rfu1", 33, 3, 0).little_endian(4, 2),
    FieldDesc::uint("framed", 32, 1, 0).little_endian(4, 2),
    FieldDesc::uint("max_sdu_p_to_c", 52, 12, 0).little_endian(6, 2),
    FieldDesc::uint("rfu2", 48, 4, 0).little_endian(6, 2),
    FieldDesc::uint("sdu_interval_c_to_p", 68, 20, 0).little_endian(8, 3),
    FieldDesc::uint("rfu3", 64, 4, 0).little_endian(8, 3),
    FieldDesc::uint("sdu_interval_p_to_c", 92, 20, 0).little_endian(11, 3),
    FieldDesc::uint("rfu4", 88, 4, 0).little_endian(11, 3),
    FieldDesc::le_uint("max_pdu_c_to_p", 112, 16, 0),
    FieldDesc::le_uint("max_pdu_p_to_c", 128, 16, 0),
    FieldDesc::uint("nse", 144, 8, 0),
    FieldDesc::uint("subinterval", 152, 24, 0),
    FieldDesc::uint("bn_c_to_p", 180, 4, 0),
    FieldDesc::uint("bn_p_to_c", 176, 4, 0),
    FieldDesc::uint("ft_c_to_p", 184, 8, 0),
    FieldDesc::uint("ft_p_to_c", 192, 8, 0),
    FieldDesc::le_uint("iso_interval", 200, 16, 0),
    FieldDesc::uint("cis_offset_min", 216, 24, 0),
    FieldDesc::uint("cis_offset_max", 240, 24, 0),
    FieldDesc::le_uint("conn_event_count", 264, 16, 0),
];

fn header_len(_: &[u8]) -> usize {
    35
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::LLCISREQ,
    name: "LL_CIS_REQ",
    fields: FIELDS,
    min_len: 35,
    header_len,
    next: crate::proto::next_raw,
    build_len: 35,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
