// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of ATT_Find_By_Type_Value_Response converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth.py, class ATT_Find_By_Type_Value_Response (scapy
//! 2.7.0), converted by dev/protogen/scapy2spec.py from the field objects scapy
//! builds at run time. scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth/att_find_by_type_value_response.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};
use crate::repeat::{ElemLen, Extent, GroupDesc};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[FieldDesc::var_bytes("handles", 0)];

pub static GROUP_FIELDS: &[FieldDesc] = &[
    FieldDesc::le_uint("handle", 0, 16, 0),
    FieldDesc::le_uint("value", 16, 16, 0),
];

pub static GROUP: GroupDesc = GroupDesc::new(
    "ATT_Handle",
    GROUP_FIELDS,
    ElemLen::Fixed(4),
    Extent::Rest,
    0,
);

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::ATTFindByTypeValueResponse,
    name: "ATT_Find_By_Type_Value_Response",
    fields: FIELDS,
    min_len: 0,
    header_len: crate::proto::header_len_rest,
    next: crate::proto::next_raw,
    build_len: 0,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
