// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of HCI_Mon_Hdr converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth.py, class HCI_Mon_Hdr (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth/hci_mon_hdr.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::le_uint("opcode", 0, 16, 0).named(&[
        (0, "New index"),
        (1, "Delete index"),
        (2, "Command pkt"),
        (3, "Event pkt"),
        (4, "ACL TX pkt"),
        (5, "ACL RX pkt"),
        (6, "SCO TX pkt"),
        (7, "SCO RX pkt"),
        (8, "Open index"),
        (9, "Close index"),
        (10, "Index info"),
        (11, "Vendor diag"),
        (12, "System note"),
        (13, "User logging"),
        (14, "Ctrl open"),
        (15, "Ctrl close"),
        (16, "Ctrl command"),
        (17, "Ctrl event"),
        (18, "ISO TX pkt"),
        (19, "ISO RX pkt"),
    ]),
    FieldDesc::le_uint("adapter_id", 16, 16, 0),
    FieldDesc::le_uint("len", 32, 16, 0),
];

fn header_len(_: &[u8]) -> usize {
    6
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::HCIMonHdr,
    name: "HCI_Mon_Hdr",
    fields: FIELDS,
    min_len: 6,
    header_len,
    next: crate::proto::next_raw,
    build_len: 6,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
