// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth.py
//   scapy 2.8.0.post0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of ATT_Read_Multiple_Response converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth.py, class ATT_Read_Multiple_Response (scapy
//! 2.8.0.post0), converted by dev/protogen/scapy2spec.py from the field objects
//! scapy builds at run time. scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth/att_read_multiple_response.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[FieldDesc::var_bytes("values", 0)];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::ATTReadMultipleResponse,
    name: "ATT_Read_Multiple_Response",
    fields: FIELDS,
    min_len: 0,
    header_len: crate::proto::header_len_rest,
    next: crate::proto::next_raw,
    build_len: 0,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
