// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of HCI_LE_Meta_Long_Term_Key_Request converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth.py, class HCI_LE_Meta_Long_Term_Key_Request (scapy
//! 2.7.0), converted by dev/protogen/scapy2spec.py from the field objects scapy
//! builds at run time. scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth/hci_le_meta_long_term_key_request.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::le_uint("handle", 0, 16, 0),
    FieldDesc::bytes("rand", 16, 64),
    FieldDesc::le_uint("ediv", 80, 16, 0),
];

fn header_len(_: &[u8]) -> usize {
    12
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::HCILEMetaLongTermKeyRequest,
    name: "HCI_LE_Meta_Long_Term_Key_Request",
    fields: FIELDS,
    min_len: 12,
    header_len,
    next: crate::proto::next_raw,
    build_len: 12,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
