// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of L2CAP_Create_Channel_Request converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth.py, class L2CAP_Create_Channel_Request (scapy 2.7.0),
//! converted by dev/protogen/scapy2spec.py from the field objects scapy builds at
//! run time. scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth/l2cap_create_channel_request.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::le_uint("psm", 0, 16, 0).named(&[
        (1, "SDP"),
        (3, "RFCOMM"),
        (5, "TCS-BIN"),
        (7, "TCS-BIN-CORDLESS"),
        (15, "BNEP"),
        (17, "HID-Control"),
        (19, "HID-Interrupt"),
        (21, "UPnP"),
        (23, "AVCTP-Control"),
        (25, "AVDTP"),
        (27, "AVCTP-Browsing"),
        (29, "UDI_C-Plane"),
        (31, "ATT"),
        (33, "3DSP"),
        (35, "IPSP"),
        (37, "OTS"),
    ]),
    FieldDesc::le_uint("scid", 16, 16, 0),
    FieldDesc::uint("controller_id", 32, 8, 0),
];

fn header_len(_: &[u8]) -> usize {
    5
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::L2CAPCreateChannelRequest,
    name: "L2CAP_Create_Channel_Request",
    fields: FIELDS,
    min_len: 5,
    header_len,
    next: crate::proto::next_raw,
    build_len: 5,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
