// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth.py
//   scapy 2.8.0.post0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of L2CAP_Create_Channel_Response converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth.py, class L2CAP_Create_Channel_Response (scapy
//! 2.8.0.post0), converted by dev/protogen/scapy2spec.py from the field objects
//! scapy builds at run time. scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth/l2cap_create_channel_response.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::le_uint("dcid", 0, 16, 0),
    FieldDesc::le_uint("scid", 16, 16, 0),
    FieldDesc::le_uint("result", 32, 16, 0).named(&[
        (0, "Connection successful"),
        (1, "Connection pending"),
        (2, "Connection refused - PSM not supported"),
        (3, "Connection refused - security block"),
        (4, "Connection refused - no resources available"),
        (5, "Connection refused - cont_ID not supported"),
        (6, "Connection refused - invalid scid"),
        (7, "Connection refused - scid already allocated"),
    ]),
    FieldDesc::le_uint("status", 48, 16, 0).named(&[
        (0, "No further information available"),
        (1, "Authentication pending"),
        (2, "Authorization pending"),
    ]),
];

fn header_len(_: &[u8]) -> usize {
    8
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::L2CAPCreateChannelResponse,
    name: "L2CAP_Create_Channel_Response",
    fields: FIELDS,
    min_len: 8,
    header_len,
    next: crate::proto::next_raw,
    build_len: 8,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
