// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/bluetooth.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of L2CAP_ConnResp converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/bluetooth.py, class L2CAP_ConnResp (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/bluetooth/l2cap_connresp.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::le_uint("dcid", 0, 16, 0),
    FieldDesc::le_uint("scid", 16, 16, 0),
    FieldDesc::le_uint("result", 32, 16, 0).named(&[
        (0, "success"),
        (1, "pend"),
        (2, "cr_bad_psm"),
        (3, "cr_sec_block"),
        (4, "cr_no_mem"),
        (5, "reserved"),
        (6, "cr_inval_scid"),
        (7, "cr_scid_in_use"),
    ]),
    FieldDesc::le_uint("status", 48, 16, 0).named(&[
        (0, "no_info"),
        (1, "authen_pend"),
        (2, "author_pend"),
        (3, "reserved"),
    ]),
];

fn header_len(_: &[u8]) -> usize {
    8
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::L2CAPConnResp,
    name: "L2CAP_ConnResp",
    fields: FIELDS,
    min_len: 8,
    header_len,
    next: crate::proto::next_raw,
    build_len: 8,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
