//! Cisco Discovery Protocol version 2, as published by Cisco Systems in
//! "Cisco Discovery Protocol Configuration Guide" and the protocol description in
//! Cisco document 13418: a one-octet version, a one-octet time-to-live, a
//! two-octet checksum, then TLVs of a two-octet type and a two-octet length that
//! counts both header words. Carried over 802.2 SNAP with OUI 0x00000C and
//! protocol id 0x2000.
//!
//! Generated by dev/protogen from dev/protogen/specs/cdp.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
use crate::layers::tlv::{self, TlvFmt};
use crate::options::Item;

/// A CDP TLV length counts the type and length words themselves.
const FMT: TlvFmt = TlvFmt::new(16, 16).covering_header();

fn tlv_name(t: u32) -> Option<&'static str> {
    Some(match t {
        0x0001 => "DeviceID",
        0x0002 => "Addresses",
        0x0003 => "PortID",
        0x0004 => "Capabilities",
        0x0005 => "SoftwareVersion",
        0x0006 => "Platform",
        0x0009 => "VTPDomain",
        0x000a => "NativeVLAN",
        0x000b => "Duplex",
        0x0016 => "MgmtAddresses",
        _ => return None,
    })
}

fn parse_options(hdr: &[u8]) -> Vec<Item> {
    let region = hdr.get(4..).unwrap_or(&[]);
    tlv::walk(region, &FMT)
        .into_iter()
        .map(|r| match (tlv_name(r.tag), r.tag) {
            (Some(n), 0x0001 | 0x0003 | 0x0005 | 0x0006 | 0x0009) => {
                tlv::text_item(n, r.tag, r.value)
            }
            (Some(n), _) => Item::bytes(n, r.tag, r.value),
            (None, _) => Item::unknown(r.tag, r.value),
        })
        .collect()
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("vers", 0, 8, 2),
    FieldDesc::uint("ttl", 8, 8, 180),
    FieldDesc::uint("cksum", 16, 16, 0),
    FieldDesc::var_bytes("msg", 32),
];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Cdp,
    name: "CDP",
    fields: FIELDS,
    min_len: 4,
    header_len: crate::proto::header_len_rest,
    next: crate::proto::next_end,
    build_len: 4,
    parse_options: Some(parse_options),
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// CDPv2 announcement, hand-built: version 2, TTL 180, one Device-ID TLV carrying "r1".
    fn vector() -> Vec<u8> {
        vec![0x02, 0xb4, 0x00, 0x00, 0x00, 0x01, 0x00, 0x06, 0x72, 0x31]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Cdp);
        let l = p.find_layer(ProtoId::Cdp).unwrap();
        assert_eq!(p.get(l, "vers").unwrap(), FieldValue::Uint(2));
        assert_eq!(p.get(l, "ttl").unwrap(), FieldValue::Uint(180));
        assert_eq!(p.get(l, "cksum").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Cdp);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Cdp);
        let l = p.find_layer(ProtoId::Cdp).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Cdp, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
