//! RFC 8415 §8: a client/server message is a one-octet message type and a 24-bit
//! transaction id, followed by options. §9 gives the Relay-forward (12) and
//! Relay-reply (13) messages instead a one-octet hop count and two 128-bit
//! addresses, which is why those three fields are conditional. §21.1: an option is
//! a 16-bit code and a 16-bit length that counts only the option data. Message
//! types and option codes from the IANA "Dynamic Host Configuration Protocol for
//! IPv6 (DHCPv6)" registry.
//!
//! Generated by dev/protogen from dev/protogen/specs/dhcp6.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
use crate::layers::tlv::{self, TlvFmt};
use crate::options::Item;

fn msgtype(hdr: &[u8]) -> u8 {
    hdr.first().copied().unwrap_or(1)
}

/// RFC 8415 §9: a relay message carries a hop count and two addresses where a
/// client/server message carries a transaction id.
fn is_relay(hdr: &[u8]) -> bool {
    matches!(msgtype(hdr), 12 | 13)
}

fn is_client_server(hdr: &[u8]) -> bool {
    !is_relay(hdr)
}

fn fixed_len(hdr: &[u8]) -> usize {
    if is_relay(hdr) {
        34
    } else {
        4
    }
}

/// RFC 8415 §21.1: a 16-bit code and a 16-bit length counting only the data.
const OPTS: TlvFmt = TlvFmt::new(16, 16);

fn opt_name(t: u32) -> Option<&'static str> {
    Some(match t {
        1 => "clientid",
        2 => "serverid",
        3 => "IA_NA",
        4 => "IA_TA",
        5 => "IAADDR",
        6 => "oro",
        7 => "preference",
        8 => "elapsedtime",
        9 => "relaymsg",
        13 => "status",
        14 => "rapidcommit",
        16 => "vendorclass",
        18 => "interfaceid",
        23 => "dnsservers",
        24 => "dnsdomains",
        25 => "IA_PD",
        26 => "IAPREFIX",
        39 => "clientfqdn",
        _ => return None,
    })
}

fn parse_options(hdr: &[u8]) -> Vec<Item> {
    let region = hdr.get(fixed_len(hdr)..).unwrap_or(&[]);
    tlv::items(region, &OPTS, opt_name)
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("msgtype", 0, 8, 1),
    FieldDesc::uint("trid", 8, 24, 0).when(is_client_server),
    FieldDesc::uint("hopcount", 8, 8, 0).when(is_relay),
    FieldDesc::ipv6("linkaddr", 16).when(is_relay),
    FieldDesc::ipv6("peeraddr", 144).when(is_relay),
    FieldDesc::var_bytes("options", 32),
];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Dhcp6,
    name: "DHCP6",
    fields: FIELDS,
    min_len: 4,
    header_len: crate::proto::header_len_rest,
    next: crate::proto::next_end,
    build_len: 4,
    parse_options: Some(parse_options),
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 8415 §16.1 Solicit, transaction id 0x0a0b0c, carrying one Elapsed Time option (code 8).
    fn vector() -> Vec<u8> {
        vec![0x01, 0x0a, 0x0b, 0x0c, 0x00, 0x08, 0x00, 0x02, 0x00, 0x00]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Dhcp6);
        let l = p.find_layer(ProtoId::Dhcp6).unwrap();
        assert_eq!(p.get(l, "msgtype").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "trid").unwrap(), FieldValue::Uint(658188));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Dhcp6);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Dhcp6);
        let l = p.find_layer(ProtoId::Dhcp6).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Dhcp6, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
