//! Where every generated layer is reached from, and what to write back
//! when one is stacked. Values come from the IANA registry or the RFC
//! cited in each layer's module.
//!
//! Generated by dev/protogen from dev/protogen/specs/*.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::proto::ProtoId;

/// Every port lookup is on the dissection path of traffic that claims
/// no layer here, so the match is reached only through this bitmap.
const fn port_bits<const N: usize>(ports: &[u16]) -> [u64; N] {
    let mut bits = [0u64; N];
    let mut i = 0;
    while i < ports.len() {
        bits[(ports[i] >> 6) as usize] |= 1u64 << (ports[i] & 63);
        i += 1;
    }
    bits
}

#[inline]
pub fn by_ethertype(v: u16) -> Option<ProtoId> {
    match v {
        35020 => Some(ProtoId::Lldp),
        _ => None,
    }
}

#[inline]
pub fn by_ethertype_of(p: ProtoId) -> Option<u16> {
    match p {
        ProtoId::Lldp => Some(35020),
        _ => None,
    }
}

#[inline]
pub fn by_ipproto(v: u8) -> Option<ProtoId> {
    match v {
        2 => Some(ProtoId::Igmp),
        50 => Some(ProtoId::Esp),
        51 => Some(ProtoId::Ah),
        89 => Some(ProtoId::Ospf),
        112 => Some(ProtoId::Vrrp),
        132 => Some(ProtoId::Sctp),
        _ => None,
    }
}

#[inline]
pub fn by_ipproto_of(p: ProtoId) -> Option<u8> {
    match p {
        ProtoId::Ah => Some(51),
        ProtoId::Esp => Some(50),
        ProtoId::Igmp => Some(2),
        ProtoId::Ospf => Some(89),
        ProtoId::Sctp => Some(132),
        ProtoId::Vrrp => Some(112),
        _ => None,
    }
}

static UDP_PORT_CLAIMED: [u64; 810] = port_bits(&[
    69, 80, 123, 137, 161, 162, 443, 514, 520, 546, 547, 1645, 1646, 1812, 1813, 1985, 2055, 3784,
    3785, 4739, 4784, 5060, 5061, 6343, 9995, 9996, 51820,
]);

#[inline]
fn by_udp_port_claimed(v: u16) -> bool {
    let i = (v >> 6) as usize;
    i < UDP_PORT_CLAIMED.len() && UDP_PORT_CLAIMED[i] & (1u64 << (v & 63)) != 0
}

#[inline(never)]
fn by_udp_port_one(v: u16, payload: &[u8]) -> Option<ProtoId> {
    match v {
        69 => Some(ProtoId::Tftp),
        80 | 443 => crate::layers::quic::looks_like(payload).then_some(ProtoId::Quic),
        123 => Some(ProtoId::Ntp),
        137 => Some(ProtoId::Nbns),
        161 | 162 => Some(ProtoId::Snmp),
        514 => Some(ProtoId::Syslog),
        520 => Some(ProtoId::Rip),
        546 | 547 => Some(ProtoId::Dhcp6),
        1645 | 1646 | 1812 | 1813 => Some(ProtoId::Radius),
        1985 => Some(ProtoId::Hsrp),
        2055 | 9995 | 9996 => {
            if crate::layers::ipfix::looks_like(payload) {
                return Some(ProtoId::Ipfix);
            }
            if crate::layers::netflow5::looks_like(payload) {
                return Some(ProtoId::NetflowV5);
            }
            if crate::layers::netflow9::looks_like(payload) {
                return Some(ProtoId::NetflowV9);
            }
            None
        }
        3784 | 3785 | 4784 => Some(ProtoId::Bfd),
        4739 => crate::layers::ipfix::looks_like(payload).then_some(ProtoId::Ipfix),
        5060 | 5061 => crate::layers::sip::looks_like(payload).then_some(ProtoId::Sip),
        6343 => Some(ProtoId::SFlow),
        51820 => Some(ProtoId::WireGuard),
        _ => None,
    }
}

/// The destination port names the service, so it is asked first.
#[inline]
pub fn by_udp_port(sport: u16, dport: u16, payload: &[u8]) -> Option<ProtoId> {
    if by_udp_port_claimed(dport) {
        if let Some(p) = by_udp_port_one(dport, payload) {
            return Some(p);
        }
    }
    if by_udp_port_claimed(sport) {
        return by_udp_port_one(sport, payload);
    }
    None
}

#[inline]
pub fn by_udp_port_of(p: ProtoId) -> Option<u16> {
    match p {
        ProtoId::Bfd => Some(3784),
        ProtoId::Dhcp6 => Some(547),
        ProtoId::Hsrp => Some(1985),
        ProtoId::Ipfix => Some(4739),
        ProtoId::Nbns => Some(137),
        ProtoId::NetflowV5 => Some(2055),
        ProtoId::NetflowV9 => Some(2055),
        ProtoId::Ntp => Some(123),
        ProtoId::Quic => Some(443),
        ProtoId::Radius => Some(1812),
        ProtoId::Rip => Some(520),
        ProtoId::SFlow => Some(6343),
        ProtoId::Sip => Some(5060),
        ProtoId::Snmp => Some(161),
        ProtoId::Syslog => Some(514),
        ProtoId::Tftp => Some(69),
        ProtoId::WireGuard => Some(51820),
        _ => None,
    }
}

static TCP_PORT_CLAIMED: [u64; 139] = port_bits(&[
    21, 22, 23, 25, 80, 139, 143, 179, 389, 443, 445, 465, 502, 563, 587, 636, 989, 990, 992, 993,
    995, 1883, 3128, 3268, 5060, 5061, 8000, 8008, 8080, 8443, 8883, 8888,
]);

#[inline]
fn by_tcp_port_claimed(v: u16) -> bool {
    let i = (v >> 6) as usize;
    i < TCP_PORT_CLAIMED.len() && TCP_PORT_CLAIMED[i] & (1u64 << (v & 63)) != 0
}

#[inline(never)]
fn by_tcp_port_one(v: u16, payload: &[u8]) -> Option<ProtoId> {
    match v {
        21 => crate::layers::ftp::looks_like(payload).then_some(ProtoId::Ftp),
        22 => crate::layers::ssh::looks_like(payload).then_some(ProtoId::Ssh),
        23 => Some(ProtoId::Telnet),
        25 | 587 => crate::layers::smtp::looks_like(payload).then_some(ProtoId::Smtp),
        80 | 3128 | 8000 | 8008 | 8080 | 8888 => {
            crate::layers::http::looks_like(payload).then_some(ProtoId::Http)
        }
        139 => crate::layers::nbtsession::looks_like(payload).then_some(ProtoId::NbtSession),
        143 => crate::layers::imap::looks_like(payload).then_some(ProtoId::Imap),
        179 => crate::layers::bgp::looks_like(payload).then_some(ProtoId::Bgp),
        389 | 3268 => crate::layers::ldap::looks_like(payload).then_some(ProtoId::Ldap),
        443 | 465 | 563 | 636 | 989 | 990 | 992 | 993 | 995 | 5061 | 8443 => {
            crate::layers::tls::looks_like(payload).then_some(ProtoId::Tls)
        }
        445 => crate::layers::smb2::looks_like(payload).then_some(ProtoId::Smb2),
        502 => crate::layers::modbus::looks_like(payload).then_some(ProtoId::Modbus),
        1883 | 8883 => crate::layers::mqtt::looks_like(payload).then_some(ProtoId::Mqtt),
        5060 => crate::layers::sip::looks_like(payload).then_some(ProtoId::Sip),
        _ => None,
    }
}

/// The destination port names the service, so it is asked first.
#[inline]
pub fn by_tcp_port(sport: u16, dport: u16, payload: &[u8]) -> Option<ProtoId> {
    if by_tcp_port_claimed(dport) {
        if let Some(p) = by_tcp_port_one(dport, payload) {
            return Some(p);
        }
    }
    if by_tcp_port_claimed(sport) {
        return by_tcp_port_one(sport, payload);
    }
    None
}

#[inline]
pub fn by_tcp_port_of(p: ProtoId) -> Option<u16> {
    match p {
        ProtoId::Bgp => Some(179),
        ProtoId::Ftp => Some(21),
        ProtoId::Http => Some(80),
        ProtoId::Imap => Some(143),
        ProtoId::Ldap => Some(389),
        ProtoId::Modbus => Some(502),
        ProtoId::Mqtt => Some(1883),
        ProtoId::NbtSession => Some(139),
        ProtoId::Sip => Some(5060),
        ProtoId::Smb2 => Some(445),
        ProtoId::Smtp => Some(25),
        ProtoId::Ssh => Some(22),
        ProtoId::Telnet => Some(23),
        ProtoId::Tls => Some(443),
        _ => None,
    }
}

#[inline]
pub fn by_llc_sap(v: u8) -> Option<ProtoId> {
    match v {
        66 => Some(ProtoId::Stp),
        170 => Some(ProtoId::Snap),
        _ => None,
    }
}

#[inline]
pub fn by_llc_sap_of(p: ProtoId) -> Option<u8> {
    match p {
        ProtoId::Snap => Some(170),
        ProtoId::Stp => Some(66),
        _ => None,
    }
}

#[inline]
pub fn by_icmpv6_type(v: u8) -> Option<ProtoId> {
    match v {
        130 => Some(ProtoId::Icmpv6MlQuery),
        131 => Some(ProtoId::Icmpv6MlReport),
        132 => Some(ProtoId::Icmpv6MlDone),
        133 => Some(ProtoId::Icmpv6NdRs),
        134 => Some(ProtoId::Icmpv6NdRa),
        135 => Some(ProtoId::Icmpv6NdNs),
        136 => Some(ProtoId::Icmpv6NdNa),
        137 => Some(ProtoId::Icmpv6NdRedirect),
        143 => Some(ProtoId::Icmpv6MlReport2),
        _ => None,
    }
}

#[inline]
pub fn by_icmpv6_type_of(p: ProtoId) -> Option<u8> {
    match p {
        ProtoId::Icmpv6NdNa => Some(136),
        ProtoId::Icmpv6NdNs => Some(135),
        ProtoId::Icmpv6NdRa => Some(134),
        ProtoId::Icmpv6NdRedirect => Some(137),
        ProtoId::Icmpv6NdRs => Some(133),
        ProtoId::Icmpv6MlDone => Some(132),
        ProtoId::Icmpv6MlQuery => Some(130),
        ProtoId::Icmpv6MlReport => Some(131),
        ProtoId::Icmpv6MlReport2 => Some(143),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    #[test]
    fn udp_port_bitmap_covers_every_arm() {
        for v in 0..=u16::MAX {
            let want = matches!(
                v,
                69 | 80
                    | 123
                    | 137
                    | 161
                    | 162
                    | 443
                    | 514
                    | 520
                    | 546
                    | 547
                    | 1645
                    | 1646
                    | 1812
                    | 1813
                    | 1985
                    | 2055
                    | 3784
                    | 3785
                    | 4739
                    | 4784
                    | 5060
                    | 5061
                    | 6343
                    | 9995
                    | 9996
                    | 51820
            );
            assert_eq!(super::by_udp_port_claimed(v), want, "udp_port {v}");
        }
    }

    #[test]
    fn tcp_port_bitmap_covers_every_arm() {
        for v in 0..=u16::MAX {
            let want = matches!(
                v,
                21 | 22
                    | 23
                    | 25
                    | 80
                    | 139
                    | 143
                    | 179
                    | 389
                    | 443
                    | 445
                    | 465
                    | 502
                    | 563
                    | 587
                    | 636
                    | 989
                    | 990
                    | 992
                    | 993
                    | 995
                    | 1883
                    | 3128
                    | 3268
                    | 5060
                    | 5061
                    | 8000
                    | 8008
                    | 8080
                    | 8443
                    | 8883
                    | 8888
            );
            assert_eq!(super::by_tcp_port_claimed(v), want, "tcp_port {v}");
        }
    }
}
