// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/dot11.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of AKMSuite converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/dot11.py, class AKMSuite (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/dot11/akmsuite.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("oui", 0, 24, 4012),
    FieldDesc::uint("suite", 24, 8, 1).named(&[
        (0, "Reserved"),
        (1, "802.1X"),
        (2, "PSK"),
        (3, "FT-802.1X"),
        (4, "FT-PSK"),
        (5, "WPA-SHA256"),
        (6, "PSK-SHA256"),
        (7, "TDLS"),
        (8, "SAE"),
        (9, "FT-SAE"),
        (10, "AP-PEER-KEY"),
        (11, "WPA-SHA256-SUITE-B"),
        (12, "WPA-SHA384-SUITE-B"),
        (13, "FT-802.1X-SHA384"),
        (14, "FILS-SHA256"),
        (15, "FILS-SHA384"),
        (16, "FT-FILS-SHA256"),
        (17, "FT-FILS-SHA384"),
        (18, "OWE"),
    ]),
];

fn header_len(_: &[u8]) -> usize {
    4
}

fn content_len(_: &[u8]) -> usize {
    4
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::AKMSuite,
    name: "AKMSuite",
    fields: FIELDS,
    min_len: 4,
    header_len,
    next: crate::proto::next_end,
    build_len: 4,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
