// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/dot11.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of RSNCipherSuite converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/dot11.py, class RSNCipherSuite (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/dot11/rsnciphersuite.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("oui", 0, 24, 4012),
    FieldDesc::uint("cipher", 24, 8, 4).named(&[
        (0, "Use group cipher suite"),
        (1, "WEP-40"),
        (2, "TKIP"),
        (3, "OCB"),
        (4, "CCMP-128"),
        (5, "WEP-104"),
        (6, "BIP-CMAC-128"),
        (7, "Group addressed traffic not allowed"),
        (8, "GCMP-128"),
        (9, "GCMP-256"),
        (10, "CCMP-256"),
        (11, "BIP-GMAC-128"),
        (12, "BIP-GMAC-256"),
        (13, "BIP-CMAC-256"),
    ]),
];

fn header_len(_: &[u8]) -> usize {
    4
}

fn content_len(_: &[u8]) -> usize {
    4
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::RSNCipherSuite,
    name: "RSNCipherSuite",
    fields: FIELDS,
    min_len: 4,
    header_len,
    next: crate::proto::next_end,
    build_len: 4,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
