//! IEEE Std 802.11-2020 §9.3.3.6: the Association Response frame body is a 16-bit
//! Capability Information field, a 16-bit Status Code and a 16-bit Association ID,
//! little-endian, followed by information elements.
//!
//! Generated by dev/protogen from dev/protogen/specs/dot11assoresp.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
use crate::options::Item;

fn parse_options(hdr: &[u8]) -> Vec<Item> {
    crate::layers::dot11::info_elements(hdr, 6)
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::le_uint("cap", 0, 16, 0),
    FieldDesc::le_uint("status", 16, 16, 0),
    FieldDesc::le_uint("AID", 32, 16, 0),
    FieldDesc::var_bytes("options", 48),
];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Dot11AssoResp,
    name: "Dot11AssoResp",
    fields: FIELDS,
    min_len: 6,
    header_len: crate::proto::header_len_rest,
    next: crate::proto::next_end,
    build_len: 6,
    parse_options: Some(parse_options),
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// IEEE 802.11-2020 §9.3.3.6, hand-built: status 0, AID 1.
    fn vector() -> Vec<u8> {
        vec![0x01, 0x00, 0x00, 0x00, 0x01, 0xc0]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Dot11AssoResp);
        let l = p.find_layer(ProtoId::Dot11AssoResp).unwrap();
        assert_eq!(p.get(l, "cap").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "status").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "AID").unwrap(), FieldValue::Uint(49153));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Dot11AssoResp);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Dot11AssoResp);
        let l = p.find_layer(ProtoId::Dot11AssoResp).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Dot11AssoResp, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
