// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/dot11.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of Dot11EltCountryConstraintTriplet converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/dot11.py, class Dot11EltCountryConstraintTriplet (scapy 2.7.0),
//! converted by dev/protogen/scapy2spec.py from the field objects scapy builds at
//! run time. scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/dot11/dot11eltcountryconstrainttriplet.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("first_channel_number", 0, 8, 1),
    FieldDesc::uint("num_channels", 8, 8, 24),
    FieldDesc::uint("mtp", 16, 8, 0),
];

fn header_len(_: &[u8]) -> usize {
    3
}

fn content_len(_: &[u8]) -> usize {
    3
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Dot11EltCountryConstraintTriplet,
    name: "Dot11EltCountryConstraintTriplet",
    fields: FIELDS,
    min_len: 3,
    header_len,
    next: crate::proto::next_end,
    build_len: 3,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
