// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/dot11.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of Dot11ReassoReq converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/dot11.py, class Dot11ReassoReq (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/dot11/dot11reassoreq.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::flags(
        "cap",
        0,
        16,
        &[
            "res8",
            "res9",
            "short-slot",
            "res11",
            "res12",
            "DSSS-OFDM",
            "res14",
            "res15",
            "ESS",
            "IBSS",
            "CFP",
            "CFP-req",
            "privacy",
            "short-preamble",
            "PBCC",
            "agility",
        ],
    ),
    FieldDesc::le_uint("listen_interval", 16, 16, 200),
    FieldDesc::mac("current_AP", 32),
];

fn header_len(_: &[u8]) -> usize {
    10
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Dot11ReassoReq,
    name: "Dot11ReassoReq",
    fields: FIELDS,
    min_len: 10,
    header_len,
    next: crate::proto::next_raw,
    build_len: 10,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
