// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/dot11.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of Dot11WNM converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/dot11.py, class Dot11WNM (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/dot11/dot11wnm.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[FieldDesc::uint("action", 0, 8, 0).named(&[
    (0, "Event Request"),
    (1, "Event Report"),
    (2, "Diagnostic Request"),
    (3, "Diagnostic Report"),
    (4, "Location Configuration Request"),
    (5, "Location Configuration Response"),
    (6, "BSS Transition Management Query"),
    (7, "BSS Transition Management Request"),
    (8, "BSS Transition Management Response"),
    (9, "FMS Request"),
    (10, "FMS Response"),
    (11, "Collocated Interference Request"),
    (12, "Collocated Interference Report"),
    (13, "TFS Request"),
    (14, "TFS Response"),
    (15, "TFS Notify"),
    (16, "WNM Sleep Mode Request"),
    (17, "WNM Sleep Mode Response"),
    (18, "TIM Broadcast Request"),
    (19, "TIM Broadcast Response"),
    (20, "QoS Traffic Capability Update"),
    (21, "Channel Usage Request"),
    (22, "Channel Usage Response"),
    (23, "DMS Request"),
    (24, "DMS Response"),
    (25, "Timing Measurement Request"),
    (26, "WNM Notification Request"),
    (27, "WNM Notification Response"),
    (28, "WNM-Notify Response"),
])];

fn header_len(_: &[u8]) -> usize {
    1
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Dot11WNM,
    name: "Dot11WNM",
    fields: FIELDS,
    min_len: 1,
    header_len,
    next: crate::proto::next_raw,
    build_len: 1,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
