// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/dot11.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of Dot11SpectrumManagement converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/dot11.py, class Dot11SpectrumManagement (scapy 2.7.0), converted
//! by dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/dot11/dot11spectrummanagement.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[FieldDesc::uint("action", 0, 8, 0).named(&[
    (0, "Measurement Request"),
    (1, "Measurement Report"),
    (2, "TPC Request"),
    (3, "TPC Report"),
    (4, "Channel Switch Announcement"),
])];

fn header_len(_: &[u8]) -> usize {
    1
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Dot11SpectrumManagement,
    name: "Dot11SpectrumManagement",
    fields: FIELDS,
    min_len: 1,
    header_len,
    next: crate::proto::next_raw,
    build_len: 1,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
