// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/dot11.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of Dot11Action converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/dot11.py, class Dot11Action (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/dot11/dot11action.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[FieldDesc::uint("category", 0, 8, 0).named(&[
    (0, "Spectrum Management"),
    (1, "QoS"),
    (2, "DLS"),
    (3, "Block"),
    (4, "Public"),
    (5, "Radio Measurement"),
    (6, "Fast BSS Transition"),
    (7, "HT"),
    (8, "SA Query"),
    (9, "Protected Dual of Public Action"),
    (10, "WNM"),
    (11, "Unprotected WNM"),
    (12, "TDLS"),
    (13, "Mesh"),
    (14, "Multihop"),
    (15, "Self-protected"),
    (16, "DMG"),
    (17, "Reserved Wi-Fi Alliance"),
    (18, "Fast Session Transfer"),
    (19, "Robust AV Streaming"),
    (20, "Unprotected DMG"),
    (21, "VHT"),
])];

fn header_len(_: &[u8]) -> usize {
    1
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Dot11Action,
    name: "Dot11Action",
    fields: FIELDS,
    min_len: 1,
    header_len,
    next: crate::proto::next_raw,
    build_len: 1,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
