// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/dot15d4.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of Dot15d4CmdDisassociation converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/dot15d4.py, class Dot15d4CmdDisassociation (scapy 2.7.0),
//! converted by dev/protogen/scapy2spec.py from the field objects scapy builds at
//! run time. scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/dot15d4/dot15d4cmddisassociation.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[FieldDesc::uint("disassociation_reason", 0, 8, 2).named(&[
    (1, "coord_wishes_device_to_leave"),
    (2, "device_wishes_to_leave"),
])];

fn header_len(_: &[u8]) -> usize {
    1
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Dot15d4CmdDisassociation,
    name: "Dot15d4CmdDisassociation",
    fields: FIELDS,
    min_len: 1,
    header_len,
    next: crate::proto::next_raw,
    build_len: 1,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
