// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/eap.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of MKASAKUseParamSet converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/eap.py, class MKASAKUseParamSet (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/eap/mkasakuseparamset.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("param_set_type", 0, 8, 3).named(&[
        (1, "Live Peer List"),
        (2, "Potential Peer List"),
        (3, "MACsec SAK Use"),
        (4, "Distributed SAK"),
        (5, "Distributed CAK"),
        (6, "KMD"),
        (7, "Announcement"),
        (255, "ICV Indicator"),
    ]),
    FieldDesc::uint("latest_key_an", 8, 2, 0),
    FieldDesc::uint("latest_key_tx", 10, 1, 0),
    FieldDesc::uint("latest_key_rx", 11, 1, 0),
    FieldDesc::uint("old_key_an", 12, 2, 0),
    FieldDesc::uint("old_key_tx", 14, 1, 0),
    FieldDesc::uint("old_key_rx", 15, 1, 0),
    FieldDesc::uint("plain_tx", 16, 1, 0),
    FieldDesc::uint("plain_rx", 17, 1, 0),
    FieldDesc::uint("X", 18, 1, 0),
    FieldDesc::uint("delay_protect", 19, 1, 0),
    FieldDesc::uint("param_set_body_len", 20, 12, 0),
    FieldDesc::bytes("latest_key_key_server_member_id", 32, 96),
    FieldDesc::bytes("latest_key_key_number", 128, 32),
    FieldDesc::bytes("latest_key_lowest_acceptable_pn", 160, 32),
    FieldDesc::bytes("old_key_key_server_member_id", 192, 96),
    FieldDesc::bytes("old_key_key_number", 288, 32),
    FieldDesc::bytes("old_key_lowest_acceptable_pn", 320, 32),
];

fn header_len(_: &[u8]) -> usize {
    44
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::MKASAKUseParamSet,
    name: "MKASAKUseParamSet",
    fields: FIELDS,
    min_len: 44,
    header_len,
    next: crate::proto::next_raw,
    build_len: 44,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
