//! RFC 2281 §5: a one-octet version, a one-octet opcode, a one-octet state, the
//! hello and hold times in seconds, a one-octet priority, a one-octet group, a
//! reserved octet, eight octets of authentication data and the four-octet virtual
//! IP address.
//!
//! Generated by dev/protogen from dev/protogen/specs/hsrp.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("version", 0, 8, 0),
    FieldDesc::uint("opcode", 8, 8, 0),
    FieldDesc::uint("state", 16, 8, 16),
    FieldDesc::uint("hellotime", 24, 8, 3),
    FieldDesc::uint("holdtime", 32, 8, 10),
    FieldDesc::uint("priority", 40, 8, 120),
    FieldDesc::uint("group", 48, 8, 0),
    FieldDesc::uint("reserved", 56, 8, 0),
    FieldDesc::bytes("auth", 64, 64).defaulting_to(&[99, 105, 115, 99, 111, 0, 0, 0]),
    FieldDesc::ipv4("virtualIP", 128, 0),
];

fn header_len(_: &[u8]) -> usize {
    20
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Hsrp,
    name: "HSRP",
    fields: FIELDS,
    min_len: 20,
    header_len,
    next: crate::proto::next_raw,
    build_len: 20,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 2281 §5 hello, hand-built: state Active (16), priority 120, group 0, default "cisco" authentication, virtual IP 10.0.0.1.
    fn vector() -> Vec<u8> {
        vec![
            0x00, 0x00, 0x10, 0x03, 0x0a, 0x78, 0x00, 0x00, 0x63, 0x69, 0x73, 0x63, 0x6f, 0x00,
            0x00, 0x00, 0x0a, 0x00, 0x00, 0x01,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Hsrp);
        let l = p.find_layer(ProtoId::Hsrp).unwrap();
        assert_eq!(p.get(l, "version").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "opcode").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "state").unwrap(), FieldValue::Uint(16));
        assert_eq!(p.get(l, "hellotime").unwrap(), FieldValue::Uint(3));
        assert_eq!(p.get(l, "holdtime").unwrap(), FieldValue::Uint(10));
        assert_eq!(p.get(l, "priority").unwrap(), FieldValue::Uint(120));
        assert_eq!(p.get(l, "group").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "reserved").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Hsrp);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Hsrp);
        let l = p.find_layer(ProtoId::Hsrp).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Hsrp, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
