//! RFC 9112 §2.1: an HTTP/1.x message is a start line, then field lines, then an
//! empty line, then an optional body. §3 gives the request line (method, request
//! target, HTTP version) and §4 the status line (version, status code, reason
//! phrase); RFC 9110 §5 gives the field lines, whose names are case-insensitive.
//! This is text, not a field table, so the start line and the field lines are
//! decoded into one named item list and the body is left as payload
//! (DEVIATIONS T1).
//!
//! Generated by dev/protogen from dev/protogen/specs/http.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
use crate::layers::text;
use crate::options::Item;

/// RFC 9110 §9.3, plus the methods RFC 4918 §9 and RFC 5789 §2 add. A method
/// token and a space, or a status line, is what tells the start of a message
/// from the middle of a stream.
const METHODS: &[&[u8]] = &[
    b"GET ",
    b"POST ",
    b"HEAD ",
    b"PUT ",
    b"DELETE ",
    b"OPTIONS ",
    b"TRACE ",
    b"CONNECT ",
    b"PATCH ",
    b"PROPFIND ",
    b"PROPPATCH ",
    b"MKCOL ",
    b"COPY ",
    b"MOVE ",
    b"LOCK ",
    b"UNLOCK ",
];

pub fn looks_like(p: &[u8]) -> bool {
    p.starts_with(b"HTTP/") || METHODS.iter().any(|m| p.starts_with(m))
}

fn header_len(hdr: &[u8]) -> usize {
    text::headers_end(hdr)
}

fn parse_options(hdr: &[u8]) -> Vec<Item> {
    let mut out = Vec::new();
    let lines = text::lines(hdr);
    let Some(first) = lines.first() else {
        return out;
    };
    if let Some((a, b, c)) = text::start_line(first) {
        if a.starts_with(b"HTTP/") {
            out.push(text::named("Http-Version", a));
            out.push(text::named("Status-Code", b));
            out.push(text::named("Reason-Phrase", c));
        } else {
            out.push(text::named("Method", a));
            out.push(text::named("Path", b));
            out.push(text::named("Http-Version", c));
        }
    }
    let at = hdr
        .iter()
        .position(|c| *c == b'\n')
        .map_or(hdr.len(), |i| i + 1);
    out.extend(text::header_items(hdr.get(at..).unwrap_or(&[])));
    out
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[FieldDesc::var_bytes("headers", 0)];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Http,
    name: "HTTP",
    fields: FIELDS,
    min_len: 16,
    header_len,
    next: crate::proto::next_raw,
    build_len: 0,
    parse_options: Some(parse_options),
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 9112 §2.1 request, hand-built.
    fn vector() -> Vec<u8> {
        vec![
            0x47, 0x45, 0x54, 0x20, 0x2f, 0x20, 0x48, 0x54, 0x54, 0x50, 0x2f, 0x31, 0x2e, 0x31,
            0x0d, 0x0a, 0x48, 0x6f, 0x73, 0x74, 0x3a, 0x20, 0x61, 0x2e, 0x69, 0x6f, 0x0d, 0x0a,
            0x0d, 0x0a,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Http);
        assert!(p.find_layer(ProtoId::Http).is_some());

        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Http);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Http);
        let l = p.find_layer(ProtoId::Http).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Http, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
