//! RFC 4861 §4.4, Neighbor Advertisement: ICMPv6 type 136, code 0, checksum, the
//! Router, Solicited and Override flags followed by 29 reserved bits, the 128-bit
//! target address, then options (§4.6).
//!
//! Generated by dev/protogen from dev/protogen/specs/icmpv6_na.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
use crate::options::Item;

fn parse_options(hdr: &[u8]) -> Vec<Item> {
    crate::layers::ndp::options(hdr, 24)
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("type", 0, 8, 136),
    FieldDesc::uint("code", 8, 8, 0),
    FieldDesc::uint("cksum", 16, 16, 0),
    FieldDesc::uint("R", 32, 1, 0),
    FieldDesc::uint("S", 33, 1, 0),
    FieldDesc::uint("O", 34, 1, 0),
    FieldDesc::uint("res", 35, 29, 0),
    FieldDesc::ipv6("tgt", 64),
    FieldDesc::var_bytes("options", 192),
];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Icmpv6NdNa,
    name: "ICMPv6ND_NA",
    fields: FIELDS,
    min_len: 24,
    header_len: crate::proto::header_len_rest,
    next: crate::proto::next_end,
    build_len: 24,
    parse_options: Some(parse_options),
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 4861 §4.4 neighbor advertisement for 2001:db8::2, solicited and override set, with a target link-layer address option.
    fn vector() -> Vec<u8> {
        vec![
            0x88, 0x00, 0x00, 0x00, 0x60, 0x00, 0x00, 0x00, 0x20, 0x01, 0x0d, 0xb8, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x02, 0x01, 0x00, 0x11,
            0x22, 0x33, 0x44, 0x55,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Icmpv6NdNa);
        let l = p.find_layer(ProtoId::Icmpv6NdNa).unwrap();
        assert_eq!(p.get(l, "type").unwrap(), FieldValue::Uint(136));
        assert_eq!(p.get(l, "code").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "cksum").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "R").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "S").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "O").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "res").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Icmpv6NdNa);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Icmpv6NdNa);
        let l = p.find_layer(ProtoId::Icmpv6NdNa).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Icmpv6NdNa, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
