//! RFC 4861 §4.2, Router Advertisement: ICMPv6 type 134, code 0, checksum, a
//! one-octet current hop limit, the Managed and Other configuration flags, a
//! 16-bit router lifetime in seconds, a 32-bit reachable time and a 32-bit
//! retransmit timer, both in milliseconds, then options (§4.6). The Home Agent bit
//! is RFC 6275 §7.1, the two Default Router Preference bits and the Proxy bit are
//! RFC 4191 §2.2 and RFC 4389 §4.1.
//!
//! Generated by dev/protogen from dev/protogen/specs/icmpv6_ra.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
use crate::options::Item;

fn parse_options(hdr: &[u8]) -> Vec<Item> {
    crate::layers::ndp::options(hdr, 16)
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("type", 0, 8, 134),
    FieldDesc::uint("code", 8, 8, 0),
    FieldDesc::uint("cksum", 16, 16, 0),
    FieldDesc::uint("chlim", 32, 8, 0),
    FieldDesc::uint("M", 40, 1, 0),
    FieldDesc::uint("O", 41, 1, 0),
    FieldDesc::uint("H", 42, 1, 0),
    FieldDesc::uint("prf", 43, 2, 0),
    FieldDesc::uint("P", 45, 1, 0),
    FieldDesc::uint("res", 46, 2, 0),
    FieldDesc::uint("routerlifetime", 48, 16, 1800),
    FieldDesc::uint("reachabletime", 64, 32, 0),
    FieldDesc::uint("retranstimer", 96, 32, 0),
    FieldDesc::var_bytes("options", 128),
];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Icmpv6NdRa,
    name: "ICMPv6ND_RA",
    fields: FIELDS,
    min_len: 16,
    header_len: crate::proto::header_len_rest,
    next: crate::proto::next_end,
    build_len: 16,
    parse_options: Some(parse_options),
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 4861 §4.2 router advertisement: hop limit 64, router lifetime 1800 s, one MTU option of 1500.
    fn vector() -> Vec<u8> {
        vec![
            0x86, 0x00, 0x00, 0x00, 0x40, 0x00, 0x07, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x05, 0x01, 0x00, 0x00, 0x00, 0x00, 0x05, 0xdc,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Icmpv6NdRa);
        let l = p.find_layer(ProtoId::Icmpv6NdRa).unwrap();
        assert_eq!(p.get(l, "type").unwrap(), FieldValue::Uint(134));
        assert_eq!(p.get(l, "code").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "cksum").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "chlim").unwrap(), FieldValue::Uint(64));
        assert_eq!(p.get(l, "M").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "O").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "routerlifetime").unwrap(), FieldValue::Uint(1800));
        assert_eq!(p.get(l, "reachabletime").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "retranstimer").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Icmpv6NdRa);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Icmpv6NdRa);
        let l = p.find_layer(ProtoId::Icmpv6NdRa).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Icmpv6NdRa, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
