// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/contrib/igmpv3.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-09-18 — IGMPv3gr's group record and its srcaddrs list transcribed as a nested repeating group; the auxiliary-data length is counted into the record, which scapy does not do

//! RFC 2236 §2 (IGMPv2) and RFC 1112 Appendix I (IGMPv1) give the same eight
//! octets: a one-octet type, a one-octet max response time, a 16-bit checksum and
//! a group address. RFC 3376 §4.1 keeps that prefix for a version 3 Membership
//! Query and appends a suppress/QRV octet, a QQIC octet and a source count; §4.2
//! replaces the group address with a reserved word and a group record count. The
//! three versions share one layer because they share one prefix and differ only in
//! what follows it, which is what a conditional field is for.
//!
//! RFC 3376 §4.2.4 makes the version 3 report's body a count-driven repeating
//! group (`crates/wiry-core/src/repeat.rs`): `numgrp` group records, each a record
//! type, an auxiliary-data length in 32-bit words, a source count, a multicast
//! address, and then that many source addresses — so a record is eight octets plus
//! four per source plus four per auxiliary word, and the sources are a nested
//! group of their own. The version 3 query's source list (§4.1.10) is inside the
//! header but is not decoded: a layer answers under one group. See DEVIATIONS E1.
//!
//! Generated by dev/protogen from dev/protogen/specs/igmp.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};
use crate::repeat::{ElemLen, Extent, GroupDesc, LenTerm};

// protogen:hand begin
fn msg_type(hdr: &[u8]) -> u8 {
    hdr.first().copied().unwrap_or(0x11)
}

/// RFC 3376 §4.2 puts a reserved word and a record count where every other
/// version carries the group address.
fn is_v3_report(hdr: &[u8]) -> bool {
    msg_type(hdr) == 0x22
}

fn has_group_address(hdr: &[u8]) -> bool {
    !is_v3_report(hdr)
}

/// RFC 3376 §4.1: a version 3 query is a type 0x11 message of at least twelve
/// octets. Length is the only thing that tells it from a version 2 query.
fn is_v3_query(hdr: &[u8]) -> bool {
    msg_type(hdr) == 0x11 && hdr.len() >= 12
}

fn header_len(hdr: &[u8]) -> usize {
    // The group records belong to the header, because the walk is handed the
    // header and nothing else.
    if is_v3_report(hdr) {
        return (8 + crate::repeat::region_len(hdr, &GROUP)).min(hdr.len());
    }
    if !is_v3_query(hdr) {
        return 8;
    }
    let n = u16::from_be_bytes([hdr[10], hdr[11]]) as usize;
    (12 + n.min(4096) * 4).min(hdr.len())
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("type", 0, 8, 17),
    FieldDesc::uint("mrcode", 8, 8, 0),
    FieldDesc::uint("chksum", 16, 16, 0),
    FieldDesc::ipv4("gaddr", 32, 0).when(has_group_address),
    FieldDesc::uint("res2", 32, 16, 0).when(is_v3_report),
    FieldDesc::uint("numgrp", 48, 16, 0).when(is_v3_report),
    FieldDesc::uint("s_qrv", 64, 8, 0).when(is_v3_query),
    FieldDesc::uint("qqic", 72, 8, 0).when(is_v3_query),
    FieldDesc::uint("numsrc", 80, 16, 0).when(is_v3_query),
    FieldDesc::var_bytes("records", 64).when(is_v3_report),
];

static GROUP_NESTED_FIELDS: &[FieldDesc] = &[FieldDesc::ipv4("sa", 0, 0)];

static GROUP_NESTED: GroupDesc = GroupDesc::new(
    "srcaddrs",
    GROUP_NESTED_FIELDS,
    ElemLen::Fixed(4),
    Extent::Count {
        bit_off: 16,
        bit_len: 16,
    },
    8,
);

pub static GROUP_FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("rtype", 0, 8, 4),
    FieldDesc::uint("auxdlen", 8, 8, 0),
    FieldDesc::uint("numsrc", 16, 16, 0),
    FieldDesc::ipv4("maddr", 32, 0),
];

pub static GROUP: GroupDesc = GroupDesc::new(
    "IGMPv3gr",
    GROUP_FIELDS,
    ElemLen::Computed {
        base: 8,
        terms: &[
            LenTerm {
                bit_off: 16,
                bit_len: 16,
                scale: 4,
            },
            LenTerm {
                bit_off: 8,
                bit_len: 8,
                scale: 4,
            },
        ],
    },
    Extent::Count {
        bit_off: 48,
        bit_len: 16,
    },
    8,
)
.nesting(&GROUP_NESTED)
.when(is_v3_report);

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Igmp,
    name: "IGMP",
    fields: FIELDS,
    min_len: 8,
    header_len,
    next: crate::proto::next_end,
    build_len: 8,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 2236 §2 membership report for 224.0.0.251, max response time 0.
    fn vector() -> Vec<u8> {
        vec![0x16, 0x00, 0x09, 0x04, 0xe0, 0x00, 0x00, 0xfb]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Igmp);
        let l = p.find_layer(ProtoId::Igmp).unwrap();
        assert_eq!(p.get(l, "type").unwrap(), FieldValue::Uint(22));
        assert_eq!(p.get(l, "mrcode").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "chksum").unwrap(), FieldValue::Uint(2308));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Igmp);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Igmp);
        let l = p.find_layer(ProtoId::Igmp).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Igmp, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }

    use crate::options::{Item, ItemValue};

    /// RFC 3376 §4.2.4 group record: type, auxiliary words, sources, address.
    fn group_record(rtype: u8, auxd: u8, maddr: [u8; 4], srcs: &[[u8; 4]]) -> Vec<u8> {
        let mut v = vec![rtype, auxd];
        v.extend_from_slice(&(srcs.len() as u16).to_be_bytes());
        v.extend_from_slice(&maddr);
        for s in srcs {
            v.extend_from_slice(s);
        }
        v.extend(std::iter::repeat(0u8).take(auxd as usize * 4));
        v
    }

    /// RFC 3376 §4.2 membership report.
    fn report(records: &[Vec<u8>]) -> Vec<u8> {
        let mut v = vec![0x22u8, 0, 0, 0, 0, 0];
        v.extend_from_slice(&(records.len() as u16).to_be_bytes());
        for r in records {
            v.extend_from_slice(r);
        }
        v
    }

    fn named<'a>(it: &'a Item, name: &str) -> &'a ItemValue {
        let ItemValue::Items(v) = &it.value else {
            panic!("not a record")
        };
        &v.iter()
            .find(|f| f.name == name)
            .expect("named field")
            .value
    }

    #[test]
    fn a_version_three_report_reads_its_group_records_and_their_sources() {
        let data = report(&[
            group_record(4, 0, [224, 0, 0, 251], &[[10, 0, 0, 1], [10, 0, 0, 2]]),
            group_record(3, 0, [239, 1, 1, 1], &[]),
        ]);
        let p = Packet::dissect(data, ProtoId::Igmp);
        let l = p.find_layer(ProtoId::Igmp).unwrap();
        assert_eq!(p.get(l, "numgrp").unwrap(), FieldValue::Uint(2));
        let items = p.options(l).unwrap();
        assert_eq!(items.len(), 2);
        assert_eq!(items[0].name, "IGMPv3gr");
        assert_eq!(named(&items[0], "rtype"), &ItemValue::Uint(4));
        assert_eq!(
            named(&items[0], "maddr"),
            &ItemValue::Text("224.0.0.251".into())
        );
        let ItemValue::Items(srcs) = named(&items[0], "srcaddrs") else {
            panic!("no source list")
        };
        // One field and nothing nested, so each source is its own value.
        assert_eq!(srcs.len(), 2);
        assert_eq!(srcs[1].name, "sa");
        assert_eq!(srcs[1].value, ItemValue::Text("10.0.0.2".into()));
        assert!(matches!(named(&items[1], "srcaddrs"), ItemValue::Items(v) if v.is_empty()));
    }

    /// RFC 3376 §4.2.10 puts auxiliary data after the sources and counts it in
    /// 32-bit words, so a record that carries some is longer than its sources
    /// alone say. scapy's `IGMPv3gr` has no auxiliary field at all and reads
    /// the next record from the wrong offset.
    #[test]
    fn auxiliary_data_lengthens_a_record() {
        let data = report(&[
            group_record(1, 2, [224, 0, 0, 1], &[[10, 0, 0, 1]]),
            group_record(2, 0, [224, 0, 0, 2], &[]),
        ]);
        let p = Packet::dissect(data, ProtoId::Igmp);
        let l = p.find_layer(ProtoId::Igmp).unwrap();
        let items = p.options(l).unwrap();
        assert_eq!(items.len(), 2);
        assert_eq!(
            named(&items[1], "maddr"),
            &ItemValue::Text("224.0.0.2".into())
        );
    }

    #[test]
    fn a_version_two_report_has_no_group_at_all() {
        let p = Packet::dissect(vector(), ProtoId::Igmp);
        let l = p.find_layer(ProtoId::Igmp).unwrap();
        assert!(p.options(l).unwrap().is_empty());
        assert_eq!(
            p.get(l, "gaddr").unwrap(),
            FieldValue::Ipv4([224, 0, 0, 251])
        );
    }

    #[test]
    fn a_truncated_report_reads_the_records_that_arrived() {
        let full = report(&[
            group_record(4, 0, [224, 0, 0, 251], &[[10, 0, 0, 1]]),
            group_record(3, 0, [239, 1, 1, 1], &[]),
        ]);
        for n in 0..full.len() {
            let p = Packet::dissect(full[..n].to_vec(), ProtoId::Igmp);
            assert_eq!(p.raw_bytes(), &full[..n]);
        }
        let p = Packet::dissect(full[..full.len() - 2].to_vec(), ProtoId::Igmp);
        let l = p.find_layer(ProtoId::Igmp).unwrap();
        assert_eq!(p.options(l).unwrap().len(), 1);
    }

    #[test]
    fn records_encode_back_to_the_bytes_they_came_from() {
        let data = report(&[
            group_record(4, 0, [224, 0, 0, 251], &[[10, 0, 0, 1], [10, 0, 0, 2]]),
            group_record(3, 0, [239, 1, 1, 1], &[]),
        ]);
        let p = Packet::dissect(data.clone(), ProtoId::Igmp);
        let l = p.find_layer(ProtoId::Igmp).unwrap();
        let items = p.options(l).unwrap();
        assert_eq!(crate::repeat::encode(&GROUP, &items).unwrap(), data[8..]);
    }
    // protogen:tests end
}
