//! RFC 2236 §2 (IGMPv2) and RFC 1112 Appendix I (IGMPv1) give the same eight
//! octets: a one-octet type, a one-octet max response time, a 16-bit checksum and
//! a group address. RFC 3376 §4.1 keeps that prefix for a version 3 Membership
//! Query and appends a suppress/QRV octet, a QQIC octet and a source count; §4.2
//! replaces the group address with a reserved word and a group record count. The
//! three versions share one layer because they share one prefix and differ only in
//! what follows it, which is what a conditional field is for.
//!
//! Generated by dev/protogen from dev/protogen/specs/igmp.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
fn msg_type(hdr: &[u8]) -> u8 {
    hdr.first().copied().unwrap_or(0x11)
}

/// RFC 3376 §4.2 puts a reserved word and a record count where every other
/// version carries the group address.
fn is_v3_report(hdr: &[u8]) -> bool {
    msg_type(hdr) == 0x22
}

fn has_group_address(hdr: &[u8]) -> bool {
    !is_v3_report(hdr)
}

/// RFC 3376 §4.1: a version 3 query is a type 0x11 message of at least twelve
/// octets. Length is the only thing that tells it from a version 2 query.
fn is_v3_query(hdr: &[u8]) -> bool {
    msg_type(hdr) == 0x11 && hdr.len() >= 12
}

fn header_len(hdr: &[u8]) -> usize {
    if !is_v3_query(hdr) {
        return 8;
    }
    let n = u16::from_be_bytes([hdr[10], hdr[11]]) as usize;
    (12 + n.min(4096) * 4).min(hdr.len())
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("type", 0, 8, 17),
    FieldDesc::uint("mrcode", 8, 8, 0),
    FieldDesc::uint("chksum", 16, 16, 0),
    FieldDesc::ipv4("gaddr", 32, 0).when(has_group_address),
    FieldDesc::uint("res2", 32, 16, 0).when(is_v3_report),
    FieldDesc::uint("numgrp", 48, 16, 0).when(is_v3_report),
    FieldDesc::uint("s_qrv", 64, 8, 0).when(is_v3_query),
    FieldDesc::uint("qqic", 72, 8, 0).when(is_v3_query),
    FieldDesc::uint("numsrc", 80, 16, 0).when(is_v3_query),
];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Igmp,
    name: "IGMP",
    fields: FIELDS,
    min_len: 8,
    header_len,
    next: crate::proto::next_end,
    build_len: 8,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 2236 §2 membership report for 224.0.0.251, max response time 0.
    fn vector() -> Vec<u8> {
        vec![0x16, 0x00, 0x09, 0x04, 0xe0, 0x00, 0x00, 0xfb]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Igmp);
        let l = p.find_layer(ProtoId::Igmp).unwrap();
        assert_eq!(p.get(l, "type").unwrap(), FieldValue::Uint(22));
        assert_eq!(p.get(l, "mrcode").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "chksum").unwrap(), FieldValue::Uint(2308));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Igmp);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Igmp);
        let l = p.find_layer(ProtoId::Igmp).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Igmp, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
