// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/inet6.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of MIP6OptBRAdvice converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/inet6.py, class MIP6OptBRAdvice (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/inet6/mip6optbradvice.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("otype", 0, 8, 2).named(&[
        (2, "Binding Refresh Advice"),
        (3, "Alternate Care-of Address"),
        (4, "Nonce Indices"),
        (5, "Binding Authorization Data"),
        (6, "Mobile Network Prefix (RFC3963)"),
        (7, "Link-Layer Address (RFC4068)"),
        (8, "Mobile Node Identifier (RFC4283)"),
        (9, "Mobility Message Authentication (RFC4285)"),
        (10, "Replay Protection (RFC4285)"),
        (11, "CGA Parameters Request (RFC4866)"),
        (12, "CGA Parameters (RFC4866)"),
        (13, "Signature (RFC4866)"),
        (14, "Home Keygen Token (RFC4866)"),
        (15, "Care-of Test Init (RFC4866)"),
        (16, "Care-of Test (RFC4866)"),
    ]),
    FieldDesc::uint("olen", 8, 8, 2),
    FieldDesc::uint("rinter", 16, 16, 0),
];

fn header_len(_: &[u8]) -> usize {
    4
}

fn content_len(_: &[u8]) -> usize {
    4
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::MIP6OptBRAdvice,
    name: "MIP6OptBRAdvice",
    fields: FIELDS,
    min_len: 4,
    header_len,
    next: crate::proto::next_end,
    build_len: 4,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
