// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/inet.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of IPOption_MTU_Reply converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/inet.py, class IPOption_MTU_Reply (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/inet/ipoption_mtu_reply.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("copy_flag", 0, 1, 0),
    FieldDesc::uint("optclass", 1, 2, 0).named(&[(0, "control"), (2, "debug")]),
    FieldDesc::uint("option", 3, 5, 12).named(&[
        (0, "end_of_list"),
        (1, "nop"),
        (2, "security"),
        (3, "loose_source_route"),
        (4, "timestamp"),
        (5, "extended_security"),
        (6, "commercial_security"),
        (7, "record_route"),
        (8, "stream_id"),
        (9, "strict_source_route"),
        (10, "experimental_measurement"),
        (11, "mtu_probe"),
        (12, "mtu_reply"),
        (13, "flow_control"),
        (14, "access_control"),
        (15, "encode"),
        (16, "imi_traffic_descriptor"),
        (17, "extended_IP"),
        (18, "traceroute"),
        (19, "address_extension"),
        (20, "router_alert"),
        (21, "selective_directed_broadcast_mode"),
        (23, "dynamic_packet_state"),
        (24, "upstream_multicast_packet"),
        (25, "quick_start"),
        (30, "rfc4727_experiment"),
    ]),
    FieldDesc::uint("length", 8, 8, 4),
    FieldDesc::uint("mtu", 16, 16, 0),
];

fn header_len(_: &[u8]) -> usize {
    4
}

fn content_len(_: &[u8]) -> usize {
    4
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::IPOptionMTUReply,
    name: "IPOption_MTU_Reply",
    fields: FIELDS,
    min_len: 4,
    header_len,
    next: crate::proto::next_end,
    build_len: 4,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
