// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/kerberos.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of KPasswdRepData converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/kerberos.py, class KPasswdRepData (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! RFC 4120, RFC 1964, RFC 4121, RFC 6113, RFC 6806, RFC 3244, RFC 4556, RFC
//! 8070, RFC 8636 are what scapy's docstring cites for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/kerberos/kpasswdrepdata.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("resultCode", 0, 16, 0).named(&[
        (0, "KRB5_KPASSWD_SUCCESS"),
        (1, "KRB5_KPASSWD_MALFORMED"),
        (2, "KRB5_KPASSWD_HARDERROR"),
        (3, "KRB5_KPASSWD_AUTHERROR"),
        (4, "KRB5_KPASSWD_SOFTERROR"),
        (5, "KRB5_KPASSWD_ACCESSDENIED"),
        (6, "KRB5_KPASSWD_BAD_VERSION"),
        (7, "KRB5_KPASSWD_INITIAL_FLAG_NEEDED"),
    ]),
    FieldDesc::var_bytes("resultString", 16),
];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::KPasswdRepData,
    name: "KPasswdRepData",
    fields: FIELDS,
    min_len: 2,
    header_len: crate::proto::header_len_rest,
    next: crate::proto::next_raw,
    build_len: 2,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
