//! IEEE Std 802.2-1998 (ISO/IEC 8802-2) §3.2: an LLC PDU opens with a one-octet
//! DSAP, a one-octet SSAP and a control field, taken here as the one-octet
//! unnumbered form that every protocol in scope uses. SAP values are IEEE 802
//! assignments: 0x42 spanning tree (IEEE 802.1D §9.3), 0xAA SNAP (RFC 1042),
//! 0xF0 NetBIOS.
//!
//! Generated by dev/protogen from dev/protogen/specs/llc.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{Next, ProtoDesc, ProtoId};

// protogen:hand begin
/// IEEE 802.2 §3.2: the destination SAP names the protocol above.
fn next(hdr: &[u8]) -> Next {
    match hdr
        .first()
        .and_then(|s| crate::layers::dispatch::by_llc_sap(*s))
    {
        Some(p) => Next::Proto(p),
        None => Next::Raw,
    }
}

/// The SAP pair names the protocol in both directions, so stacking sets both
/// halves: a header with DSAP 0x42 and SSAP 0xAA is not a BPDU.
fn bind_next(hdr: &mut [u8], p: ProtoId) {
    let Some(sap) = crate::layers::dispatch::by_llc_sap_of(p) else {
        return;
    };
    if hdr.len() >= 3 {
        hdr[0] = sap;
        hdr[1] = sap;
    }
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("dsap", 0, 8, 170),
    FieldDesc::uint("ssap", 8, 8, 170),
    FieldDesc::uint("ctrl", 16, 8, 3),
];

fn header_len(_: &[u8]) -> usize {
    3
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Llc,
    name: "LLC",
    fields: FIELDS,
    min_len: 3,
    header_len,
    next,
    build_len: 3,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: Some(bind_next),
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// IEEE 802.1D §7.12.3: a BPDU is carried with DSAP = SSAP = 0x42, UI control.
    fn vector() -> Vec<u8> {
        vec![0x42, 0x42, 0x03]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Llc);
        let l = p.find_layer(ProtoId::Llc).unwrap();
        assert_eq!(p.get(l, "dsap").unwrap(), FieldValue::Uint(66));
        assert_eq!(p.get(l, "ssap").unwrap(), FieldValue::Uint(66));
        assert_eq!(p.get(l, "ctrl").unwrap(), FieldValue::Uint(3));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Llc);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Llc);
        let l = p.find_layer(ProtoId::Llc).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Llc, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
