//! IEEE Std 802.1AB-2016 §8.1: an LLDPDU is a sequence of TLVs, each opening with
//! a 7-bit type and a 9-bit length in one 16-bit word, ending at the End Of LLDPDU
//! TLV (type 0). §8.5 gives the mandatory Chassis ID, Port ID and Time To Live
//! TLVs and the optional ones. EtherType 0x88CC is the IEEE 802.1AB assignment.
//!
//! Generated by dev/protogen from dev/protogen/specs/lldp.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
use crate::layers::tlv::{self, TlvFmt};
use crate::options::Item;

const FMT: TlvFmt = TlvFmt::new(7, 9).ending_at(0);

/// IEEE 802.1AB §8.5.
fn tlv_name(t: u32) -> Option<&'static str> {
    Some(match t {
        0 => "End",
        1 => "ChassisID",
        2 => "PortID",
        3 => "TTL",
        4 => "PortDescription",
        5 => "SystemName",
        6 => "SystemDescription",
        7 => "SystemCapabilities",
        8 => "ManagementAddress",
        127 => "Organizational",
        _ => return None,
    })
}

fn parse_options(hdr: &[u8]) -> Vec<Item> {
    tlv::walk(hdr, &FMT)
        .into_iter()
        .map(|r| match (tlv_name(r.tag), r.tag) {
            (Some(n), 0) => Item::flag(n, 0),
            (Some(n), 3) => Item::uint(n, 3, tlv::be(r.value)),
            (Some(n), 4..=6) => tlv::text_item(n, r.tag, r.value),
            (Some(n), _) => Item::bytes(n, r.tag, r.value),
            (None, _) => Item::unknown(r.tag, r.value),
        })
        .collect()
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[FieldDesc::var_bytes_to_end("options", 0)];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Lldp,
    name: "LLDPDU",
    fields: FIELDS,
    min_len: 2,
    header_len: crate::proto::header_len_rest,
    next: crate::proto::next_end,
    build_len: 2,
    parse_options: Some(parse_options),
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// IEEE 802.1AB §8.5 minimal LLDPDU: chassis id (subtype 4, MAC), port id (subtype 3, MAC), TTL 120, End.
    fn vector() -> Vec<u8> {
        vec![
            0x02, 0x07, 0x04, 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x04, 0x07, 0x03, 0x00, 0x11,
            0x22, 0x33, 0x44, 0x55, 0x06, 0x02, 0x00, 0x78, 0x00, 0x00,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Lldp);
        assert!(p.find_layer(ProtoId::Lldp).is_some());

        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Lldp);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Lldp);
        let l = p.find_layer(ProtoId::Lldp).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Lldp, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
