// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/lltd.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of LLTDEmit converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/lltd.py, class LLTDEmit (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/lltd/lltdemit.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};
use crate::repeat::{ElemLen, Extent, GroupDesc};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("descs_count", 0, 16, 0),
    FieldDesc::var_bytes("descs_list", 16),
];

pub static GROUP_FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("type", 0, 8, 0).named(&[(0, "Train"), (1, "Probe")]),
    FieldDesc::uint("pause", 8, 8, 0),
    FieldDesc::mac("src", 16),
    FieldDesc::mac("dst", 64),
];

pub static GROUP: GroupDesc = GroupDesc::new(
    "LLTDEmiteeDesc",
    GROUP_FIELDS,
    ElemLen::Fixed(14),
    Extent::Count {
        bit_off: 0,
        bit_len: 16,
    },
    2,
);

fn header_len(hdr: &[u8]) -> usize {
    let v_descs_count = crate::field::decode(hdr, &FIELDS[0]).as_uint().unwrap_or(0) as i64;
    let n: i64 = v_descs_count.wrapping_mul(14i64);
    2 + n.clamp(0, hdr.len() as i64) as usize
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::LLTDEmit,
    name: "LLTDEmit",
    fields: FIELDS,
    min_len: 2,
    header_len,
    next: crate::proto::next_raw,
    build_len: 2,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
