//! RFC 2710 §4, Multicast Listener Report: ICMPv6 type 131, code 0, checksum, a
//! 16-bit Maximum Response Delay that must be zero, a 16-bit reserved field and
//! the 128-bit multicast address being reported.
//!
//! Generated by dev/protogen from dev/protogen/specs/mld_report.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("type", 0, 8, 131),
    FieldDesc::uint("code", 8, 8, 0),
    FieldDesc::uint("cksum", 16, 16, 0),
    FieldDesc::uint("mrd", 32, 16, 0),
    FieldDesc::uint("reserved", 48, 16, 0),
    FieldDesc::ipv6("mladdr", 64),
];

fn header_len(_: &[u8]) -> usize {
    24
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Icmpv6MlReport,
    name: "ICMPv6MLReport",
    fields: FIELDS,
    min_len: 24,
    header_len,
    next: crate::proto::next_end,
    build_len: 24,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 2710 §4 report for ff02::1:ff00:2.
    fn vector() -> Vec<u8> {
        vec![
            0x83, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0x02, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0xff, 0x00, 0x00, 0x02,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Icmpv6MlReport);
        let l = p.find_layer(ProtoId::Icmpv6MlReport).unwrap();
        assert_eq!(p.get(l, "type").unwrap(), FieldValue::Uint(131));
        assert_eq!(p.get(l, "code").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "cksum").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "mrd").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "reserved").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Icmpv6MlReport);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Icmpv6MlReport);
        let l = p.find_layer(ProtoId::Icmpv6MlReport).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Icmpv6MlReport, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
