// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/inet6.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-09-18 — ICMPv6MLReport2's field names and ICMPv6MLDMultAddrRec's field table transcribed as a nested repeating group; the auxiliary data length is read in 32-bit words per RFC 3810 §5.2.6, which scapy reads as octets, and it is counted into the record width

//! RFC 3810 §5.2, Version 2 Multicast Listener Report: ICMPv6 type 143, a reserved
//! octet, the checksum, a 16-bit reserved field and a 16-bit count of multicast
//! address records. §5.2.4 gives one record a one-octet record type, a one-octet
//! auxiliary data length, a 16-bit source count, the 128-bit multicast address,
//! that many 128-bit source addresses and then the auxiliary data — so a record
//! is twenty octets plus sixteen per source plus the auxiliary data, and the
//! sources are a nested group of their own
//! (`crates/wiry-core/src/repeat.rs`).
//!
//! **§5.2.6 counts the auxiliary data in units of 32-bit words**, which is what
//! the element width uses here. scapy 2.7.0's `ICMPv6MLDMultAddrRec` declares
//! `auxdata_len` with `length_of="auxdata"` and no adjustment, so it reads the
//! field as a count of octets and mis-sizes any record that carries auxiliary
//! data; the RFC is followed instead. The auxiliary data itself is not a named
//! field: it sits after the nested source list, where the flat record table cannot
//! place it (DEVIATIONS E1).
//!
//! Generated by dev/protogen from dev/protogen/specs/mld_report2.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};
use crate::repeat::{ElemLen, Extent, GroupDesc, LenTerm};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("type", 0, 8, 143),
    FieldDesc::uint("res", 8, 8, 0),
    FieldDesc::uint("cksum", 16, 16, 0),
    FieldDesc::uint("reserved", 32, 16, 0),
    FieldDesc::uint("records_number", 48, 16, 0),
    FieldDesc::var_bytes("records", 64),
];

static GROUP_NESTED_FIELDS: &[FieldDesc] = &[FieldDesc::ipv6("src", 0)];

static GROUP_NESTED: GroupDesc = GroupDesc::new(
    "sources",
    GROUP_NESTED_FIELDS,
    ElemLen::Fixed(16),
    Extent::Count {
        bit_off: 16,
        bit_len: 16,
    },
    20,
);

pub static GROUP_FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("rtype", 0, 8, 4),
    FieldDesc::uint("auxdata_len", 8, 8, 0),
    FieldDesc::uint("sources_number", 16, 16, 0),
    FieldDesc::ipv6("dst", 32),
];

pub static GROUP: GroupDesc = GroupDesc::new(
    "ICMPv6MLDMultAddrRec",
    GROUP_FIELDS,
    ElemLen::Computed {
        base: 20,
        terms: &[
            LenTerm {
                bit_off: 16,
                bit_len: 16,
                scale: 16,
            },
            LenTerm {
                bit_off: 8,
                bit_len: 8,
                scale: 4,
            },
        ],
        min: 0,
    },
    Extent::Count {
        bit_off: 48,
        bit_len: 16,
    },
    8,
)
.nesting(&GROUP_NESTED);

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Icmpv6MlReport2,
    name: "ICMPv6MLReport2",
    fields: FIELDS,
    min_len: 8,
    header_len: crate::proto::header_len_rest,
    next: crate::proto::next_end,
    build_len: 8,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 3810 §5.2 report carrying one CHANGE_TO_EXCLUDE record for ff02::1:ff00:2, no sources.
    fn vector() -> Vec<u8> {
        vec![
            0x8f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x04, 0x00, 0x00, 0x00, 0xff, 0x02,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0xff, 0x00, 0x00, 0x02,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Icmpv6MlReport2);
        let l = p.find_layer(ProtoId::Icmpv6MlReport2).unwrap();
        assert_eq!(p.get(l, "type").unwrap(), FieldValue::Uint(143));
        assert_eq!(p.get(l, "res").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "cksum").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "reserved").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "records_number").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Icmpv6MlReport2);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Icmpv6MlReport2);
        let l = p.find_layer(ProtoId::Icmpv6MlReport2).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Icmpv6MlReport2, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }

    use crate::options::{Item, ItemValue};

    fn fields(it: &Item) -> Vec<(&str, ItemValue)> {
        let ItemValue::Items(v) = &it.value else {
            panic!("not a record")
        };
        v.iter()
            .map(|f| (f.name.as_ref(), f.value.clone()))
            .collect()
    }

    /// RFC 3810 §5.2.4: a record is twenty octets plus sixteen per source, and
    /// the sources are a list of their own.
    #[test]
    fn a_record_carries_its_source_list() {
        let mut data = vector();
        data[11] = 2;
        data[7] = 1;
        data.extend(std::iter::repeat_n(0u8, 32));
        data[28 + 15] = 1;
        data[44 + 15] = 2;
        let p = Packet::dissect(data, ProtoId::Icmpv6MlReport2);
        let l = p.find_layer(ProtoId::Icmpv6MlReport2).unwrap();
        let items = p.options(l).unwrap();
        assert_eq!(items.len(), 1);
        let f = fields(&items[0]);
        assert_eq!(f[0], ("rtype", ItemValue::Uint(4)));
        assert_eq!(f[3].0, "dst");
        let ItemValue::Items(srcs) = &f[4].1 else {
            panic!("no sources")
        };
        assert_eq!(srcs.len(), 2);
        assert_eq!(srcs[0].value, ItemValue::Text("::1".into()));
        assert_eq!(srcs[1].value, ItemValue::Text("::2".into()));
    }

    /// RFC 3810 §5.2.6 counts the auxiliary data in 32-bit words. Reading it as
    /// octets, which scapy 2.7.0 does, puts the next record four octets early
    /// and loses it.
    #[test]
    fn auxiliary_data_is_counted_in_thirty_two_bit_words() {
        let mut data = vector();
        data[7] = 2;
        data[9] = 1;
        data.extend_from_slice(&[0xaa, 0xbb, 0xcc, 0xdd]);
        data.extend(vector()[8..].to_vec());
        let p = Packet::dissect(data, ProtoId::Icmpv6MlReport2);
        let l = p.find_layer(ProtoId::Icmpv6MlReport2).unwrap();
        assert_eq!(p.options(l).unwrap().len(), 2);
    }

    #[test]
    fn records_encode_back_to_the_bytes_they_came_from() {
        let p = Packet::dissect(vector(), ProtoId::Icmpv6MlReport2);
        let l = p.find_layer(ProtoId::Icmpv6MlReport2).unwrap();
        let items = p.options(l).unwrap();
        assert_eq!(
            crate::repeat::encode(&GROUP, &items).unwrap(),
            vector()[8..]
        );
    }
    // protogen:tests end
}
