// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/mobileip.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of MobileIPTunnelData converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/mobileip.py, class MobileIPTunnelData (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/mobileip/mobileiptunneldata.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{Next, ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("nexthdr", 0, 8, 4),
    FieldDesc::uint("res", 8, 16, 0),
];

fn header_len(_: &[u8]) -> usize {
    3
}

fn next(hdr: &[u8]) -> Next {
    if hdr.is_empty() {
        return Next::Raw;
    }
    match crate::field::read_bits(hdr, 0, 8) {
        4 => Next::Proto(ProtoId::Ipv4),
        _ => Next::Raw,
    }
}

fn bind_next(hdr: &mut [u8], p: ProtoId) {
    let v = match p {
        ProtoId::Ipv4 => 4,
        _ => return,
    };
    if hdr.len() >= 1 {
        crate::field::write_bits(hdr, 0, 8, v);
    }
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::MobileIPTunnelData,
    name: "MobileIPTunnelData",
    fields: FIELDS,
    min_len: 3,
    header_len,
    next,
    build_len: 3,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: Some(bind_next),
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
