// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/ms_nrtp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of ArrayInfo converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/ms_nrtp.py, class ArrayInfo (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/ms_nrtp/arrayinfo.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::le_uint("ObjectId", 0, 32, 0),
    FieldDesc::le_uint("Length", 32, 32, 0),
];

fn header_len(_: &[u8]) -> usize {
    8
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::ArrayInfo,
    name: "ArrayInfo",
    fields: FIELDS,
    min_len: 8,
    header_len,
    next: crate::proto::next_raw,
    build_len: 8,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
