// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/ms_nrtp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of NRTPStatusCodeHeader converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/ms_nrtp.py, class NRTPStatusCodeHeader (scapy 2.7.0), converted
//! by dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/ms_nrtp/nrtpstatuscodeheader.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::le_uint("HeaderToken", 0, 16, 2).named(&[
        (0, "End"),
        (1, "Custom"),
        (2, "StatusCode"),
        (3, "StatusPhrase"),
        (4, "RequestUri"),
        (5, "CloseConnection"),
        (6, "ContentType"),
    ]),
    FieldDesc::uint("DataType", 16, 8, 3).named(&[
        (0, "Void"),
        (1, "CountedString"),
        (2, "Byte"),
        (3, "Uint16"),
        (4, "Int32"),
    ]),
    FieldDesc::le_uint("StatusCodeValue", 24, 16, 0),
];

fn header_len(_: &[u8]) -> usize {
    5
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::NRTPStatusCodeHeader,
    name: "NRTPStatusCodeHeader",
    fields: FIELDS,
    min_len: 5,
    header_len,
    next: crate::proto::next_raw,
    build_len: 5,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
