// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/msrpce/mspac.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of PAC_INFO_BUFFER converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/msrpce/mspac.py, class PAC_INFO_BUFFER (scapy 2.7.0), converted
//! by dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/msrpce_mspac/pac_info_buffer.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::le_uint("ulType", 0, 32, 1).named(&[
        (1, "Logon information"),
        (2, "Credentials information"),
        (6, "Server Signature"),
        (7, "KDC Signature"),
        (10, "Client name and ticket information"),
        (11, "Constrained delegation information"),
        (12, "UPN and DNS information"),
        (13, "Client claims information"),
        (14, "Device information"),
        (15, "Device claims information"),
        (16, "Ticket Signature"),
        (17, "PAC Attributes"),
        (18, "PAC Requestor"),
        (19, "Extended KDC Signature"),
    ]),
    FieldDesc::le_uint("cbBufferSize", 32, 32, 0),
    FieldDesc::le_uint("Offset", 64, 64, 0),
];

fn header_len(_: &[u8]) -> usize {
    16
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::PACINFOBUFFER,
    name: "PAC_INFO_BUFFER",
    fields: FIELDS,
    min_len: 16,
    header_len,
    next: crate::proto::next_raw,
    build_len: 16,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
