// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/netbios.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of NBNSNodeStatusResponseService converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/netbios.py, class NBNSNodeStatusResponseService (scapy 2.7.0),
//! converted by dev/protogen/scapy2spec.py from the field objects scapy builds at
//! run time. RFC 1001 is what scapy's docstring cites for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/netbios/nbnsnodestatusresponseservice.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::bytes("NETBIOS_NAME", 0, 120)
        .defaulting_to(&[87, 73, 78, 68, 79, 87, 83, 32, 32, 32, 32, 32, 32, 32, 32]),
    FieldDesc::uint("SUFFIX", 120, 8, 0).named(&[
        (0, "workstation"),
        (3, "messenger service"),
        (27, "domain master browser"),
        (28, "domain controller"),
        (30, "browser election service"),
        (32, "file server service"),
    ]),
    FieldDesc::uint("NAME_FLAGS", 128, 8, 4),
    FieldDesc::uint("UNUSED", 136, 8, 0).named(&[(0, "unused")]),
];

fn header_len(_: &[u8]) -> usize {
    18
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::NBNSNodeStatusResponseService,
    name: "NBNSNodeStatusResponseService",
    fields: FIELDS,
    min_len: 18,
    header_len,
    next: crate::proto::next_raw,
    build_len: 18,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
