//! RFC 3954 §5.1: a 16-bit version (9), a 16-bit count of FlowSets, the 32-bit
//! system uptime in milliseconds, the 32-bit UNIX export time, a 32-bit sequence
//! number and a 32-bit source id. The FlowSets that follow need the template the
//! exporter sent earlier to be read, which is per-session state this dissector
//! does not keep, so they stay in the payload (DEVIATIONS P6).
//!
//! Generated by dev/protogen from dev/protogen/specs/netflow9.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
pub fn looks_like(p: &[u8]) -> bool {
    p.get(0..2) == Some(&[0, 9])
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("version", 0, 16, 9),
    FieldDesc::uint("count", 16, 16, 0),
    FieldDesc::uint("sysUptime", 32, 32, 0),
    FieldDesc::uint("unixSecs", 64, 32, 0),
    FieldDesc::uint("sequenceNumber", 96, 32, 0),
    FieldDesc::uint("SourceID", 128, 32, 0),
];

fn header_len(_: &[u8]) -> usize {
    20
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::NetflowV9,
    name: "NetflowHeaderV9",
    fields: FIELDS,
    min_len: 20,
    header_len,
    next: crate::proto::next_raw,
    build_len: 20,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 3954 §5.1 export header, hand-built: version 9, one FlowSet, uptime 1000 ms.
    fn vector() -> Vec<u8> {
        vec![
            0x00, 0x09, 0x00, 0x01, 0x00, 0x00, 0x03, 0xe8, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::NetflowV9);
        let l = p.find_layer(ProtoId::NetflowV9).unwrap();
        assert_eq!(p.get(l, "version").unwrap(), FieldValue::Uint(9));
        assert_eq!(p.get(l, "count").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "sysUptime").unwrap(), FieldValue::Uint(1000));
        assert_eq!(p.get(l, "unixSecs").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "sequenceNumber").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "SourceID").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::NetflowV9);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::NetflowV9);
        let l = p.find_layer(ProtoId::NetflowV9).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::NetflowV9, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
