// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/netflow.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of NetflowRecordV5 converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/netflow.py, class NetflowRecordV5 (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/netflow/netflowrecordv5.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::ipv4("src", 0, 2130706433),
    FieldDesc::ipv4("dst", 32, 2130706433),
    FieldDesc::ipv4("nexthop", 64, 0),
    FieldDesc::uint("input", 96, 16, 0),
    FieldDesc::uint("output", 112, 16, 0),
    FieldDesc::uint("dpkts", 128, 32, 1),
    FieldDesc::uint("dOctets", 160, 32, 60),
    FieldDesc::uint("first", 192, 32, 0),
    FieldDesc::uint("last", 224, 32, 0),
    FieldDesc::uint("srcport", 256, 16, 0),
    FieldDesc::uint("dstport", 272, 16, 0),
    FieldDesc::uint("pad1", 288, 8, 0),
    FieldDesc::flags(
        "tcpFlags",
        296,
        8,
        &["F", "S", "R", "P", "A", "U", "E", "C"],
    )
    .with_default(2),
    FieldDesc::uint("prot", 304, 8, 6).host_named(crate::names::Host::IpProtos),
    FieldDesc::uint("tos", 312, 8, 0),
    FieldDesc::uint("src_as", 320, 16, 0),
    FieldDesc::uint("dst_as", 336, 16, 0),
    FieldDesc::uint("src_mask", 352, 8, 0),
    FieldDesc::uint("dst_mask", 360, 8, 0),
    FieldDesc::uint("pad2", 368, 16, 0),
];

fn header_len(_: &[u8]) -> usize {
    48
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::NetflowRecordV5,
    name: "NetflowRecordV5",
    fields: FIELDS,
    min_len: 48,
    header_len,
    next: crate::proto::next_raw,
    build_len: 48,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
