// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/ntlm.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of _NTLM_Version converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/ntlm.py, class _NTLM_Version (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/ntlm/ntlm_version.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("ProductMajorVersion", 0, 8, 0),
    FieldDesc::uint("ProductMinorVersion", 8, 8, 0),
    FieldDesc::le_uint("ProductBuild", 16, 16, 0),
    FieldDesc::le_uint("res_ver", 32, 24, 0),
    FieldDesc::uint("NTLMRevisionCurrent", 56, 8, 15).named(&[(15, "v15")]),
];

fn header_len(_: &[u8]) -> usize {
    8
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::NTLMVersion,
    name: "_NTLM_Version",
    fields: FIELDS,
    min_len: 8,
    header_len,
    next: crate::proto::next_raw,
    build_len: 8,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
