// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/ntp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of NTPInfoIfStatsIPv6 converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/ntp.py, class NTPInfoIfStatsIPv6 (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! RFC 5905 is what scapy's docstring cites for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/ntp/ntpinfoifstatsipv6.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::ipv6("unaddr", 0),
    FieldDesc::ipv6("unbcast", 128),
    FieldDesc::ipv6("unmask", 256),
    FieldDesc::uint("v6_flag", 384, 32, 0),
    FieldDesc::bytes("ifname", 416, 256),
    FieldDesc::uint("flags", 672, 32, 0),
    FieldDesc::uint("last_ttl", 704, 32, 0),
    FieldDesc::uint("num_mcast", 736, 32, 0),
    FieldDesc::uint("received", 768, 32, 0),
    FieldDesc::uint("sent", 800, 32, 0),
    FieldDesc::uint("notsent", 832, 32, 0),
    FieldDesc::uint("uptime", 864, 32, 0),
    FieldDesc::uint("scopeid", 896, 32, 0),
    FieldDesc::uint("ifindex", 928, 32, 0),
    FieldDesc::uint("ifnum", 960, 32, 0),
    FieldDesc::uint("peercnt", 992, 32, 0),
    FieldDesc::uint("family", 1024, 16, 0),
    FieldDesc::uint("ignore_packets", 1040, 8, 0),
    FieldDesc::uint("action", 1048, 8, 0),
    FieldDesc::uint("_filler0", 1056, 32, 0),
];

fn header_len(_: &[u8]) -> usize {
    136
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::NTPInfoIfStatsIPv6X,
    name: "NTPInfoIfStatsIPv6",
    fields: FIELDS,
    min_len: 136,
    header_len,
    next: crate::proto::next_raw,
    build_len: 136,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
