// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/ntp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of NTPInfoIOStats converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/ntp.py, class NTPInfoIOStats (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! RFC 5905 is what scapy's docstring cites for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/ntp/ntpinfoiostats.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("timereset", 0, 32, 0),
    FieldDesc::uint("totalrecvbufs", 32, 16, 0),
    FieldDesc::uint("freerecvbufs", 48, 16, 0),
    FieldDesc::uint("fullrecvbufs", 64, 16, 0),
    FieldDesc::uint("lowwater", 80, 16, 0),
    FieldDesc::uint("dropped", 96, 32, 0),
    FieldDesc::uint("ignored", 128, 32, 0),
    FieldDesc::uint("received", 160, 32, 0),
    FieldDesc::uint("sent", 192, 32, 0),
    FieldDesc::uint("notsent", 224, 32, 0),
    FieldDesc::uint("interrupts", 256, 32, 0),
    FieldDesc::uint("int_received", 288, 32, 0),
];

fn header_len(_: &[u8]) -> usize {
    40
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::NTPInfoIOStats,
    name: "NTPInfoIOStats",
    fields: FIELDS,
    min_len: 40,
    header_len,
    next: crate::proto::next_raw,
    build_len: 40,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
