// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/ntp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of NTPClockStatusPacket converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/ntp.py, class NTPClockStatusPacket (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! RFC 5905 is what scapy's docstring cites for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/ntp/ntpclockstatuspacket.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("clock_status", 0, 8, 0).named(&[
        (0, "clock operating within nominals"),
        (1, "reply timeout"),
        (2, "bad reply format"),
        (3, "hardware or software fault"),
        (4, "propagation failure"),
        (5, "bad date format or value"),
        (6, "bad time format or value"),
    ]),
    FieldDesc::uint("code", 8, 8, 0),
];

fn header_len(_: &[u8]) -> usize {
    2
}

fn content_len(_: &[u8]) -> usize {
    2
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::NTPClockStatusPacket,
    name: "NTPClockStatusPacket",
    fields: FIELDS,
    min_len: 2,
    header_len,
    next: crate::proto::next_end,
    build_len: 2,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
