// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/ntp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of NTPConfPeer converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/ntp.py, class NTPConfPeer (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! RFC 5905 is what scapy's docstring cites for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/ntp/ntpconfpeer.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::ipv4("peeraddr", 0, 0),
    FieldDesc::uint("hmode", 32, 8, 0),
    FieldDesc::uint("version", 40, 8, 0),
    FieldDesc::uint("minpoll", 48, 8, 0),
    FieldDesc::uint("maxpoll", 56, 8, 0),
    FieldDesc::flags(
        "flags",
        64,
        8,
        &[
            "CONF_FLAG_AUTHENABLE",
            "CONF_FLAG_PREFER",
            "CONF_FLAG_BURST",
            "CONF_FLAG_IBURST",
            "CONF_FLAG_NOSELECT",
            "CONF_FLAG_SKEY",
        ],
    ),
    FieldDesc::uint("ttl", 72, 8, 0),
    FieldDesc::uint("unused1", 80, 16, 0),
    FieldDesc::uint("keyid", 96, 32, 0),
    FieldDesc::bytes("keystr", 128, 1024),
    FieldDesc::uint("v6_flag", 1152, 32, 0),
    FieldDesc::uint("unused2", 1184, 32, 0),
    FieldDesc::ipv6("peeraddr6", 1216),
];

fn header_len(_: &[u8]) -> usize {
    168
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::NTPConfPeerX,
    name: "NTPConfPeer",
    fields: FIELDS,
    min_len: 168,
    header_len,
    next: crate::proto::next_raw,
    build_len: 168,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
