// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/ntp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of NTPSystemStatusPacket converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/ntp.py, class NTPSystemStatusPacket (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! RFC 5905 is what scapy's docstring cites for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/ntp/ntpsystemstatuspacket.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("leap_indicator", 0, 2, 0).named(&[
        (0, "no warning"),
        (1, "last minute was 61 seconds"),
        (2, "last minute was 59 seconds"),
        (3, "alarm condition (clock not synchronized)"),
    ]),
    FieldDesc::uint("clock_source", 2, 6, 0).named(&[
        (0, "unspecified or unknown"),
        (1, " Calibrated atomic clock"),
        (2, "VLF (band 4) or LF (band 5) radio"),
        (3, "HF (band 7) radio"),
        (4, "UHF (band 9) satellite"),
        (5, "local net"),
        (6, "UDP/NTP"),
        (7, "UDP/TIME"),
        (8, "eyeball-and-wristwatch"),
        (9, "telephone modem"),
    ]),
    FieldDesc::uint("system_event_counter", 8, 4, 0),
    FieldDesc::uint("system_event_code", 12, 4, 0).named(&[
        (0, "unspecified"),
        (1, "system restart"),
        (2, "system or hardware fault"),
        (
            3,
            "system new status word (leap bits or synchronization change)",
        ),
        (
            4,
            "system new synchronization source or stratum (sys.peer or sys.stratum change)",
        ),
        (
            5,
            "system clock reset (offset correction exceeds CLOCK.MAX)",
        ),
        (6, "system invalid time or date"),
        (7, "system clock exception"),
    ]),
];

fn header_len(_: &[u8]) -> usize {
    2
}

fn content_len(_: &[u8]) -> usize {
    2
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::NTPSystemStatusPacketX,
    name: "NTPSystemStatusPacket",
    fields: FIELDS,
    min_len: 2,
    header_len,
    next: crate::proto::next_end,
    build_len: 2,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
