// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/ntp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of NTPInfoTimerStats converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/ntp.py, class NTPInfoTimerStats (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! RFC 5905 is what scapy's docstring cites for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/ntp/ntpinfotimerstats.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("timereset", 0, 32, 0),
    FieldDesc::uint("alarms", 32, 32, 0),
    FieldDesc::uint("overflows", 64, 32, 0),
    FieldDesc::uint("xmtcalls", 96, 32, 0),
];

fn header_len(_: &[u8]) -> usize {
    16
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::NTPInfoTimerStatsX,
    name: "NTPInfoTimerStats",
    fields: FIELDS,
    min_len: 16,
    header_len,
    next: crate::proto::next_raw,
    build_len: 16,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
