// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/ntp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of NTPInfoPeerStats converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/ntp.py, class NTPInfoPeerStats (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! RFC 5905 is what scapy's docstring cites for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/ntp/ntpinfopeerstats.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::ipv4("dstaddr", 0, 0),
    FieldDesc::ipv4("srcaddr", 32, 0),
    FieldDesc::uint("srcport", 64, 16, 0),
    FieldDesc::flags(
        "flags",
        80,
        16,
        &[
            "INFO_FLAG_CONFIG",
            "INFO_FLAG_SYSPEER",
            "INFO_FLAG_BURST",
            "INFO_FLAG_REFCLOCK",
            "INFO_FLAG_PREFER",
            "INFO_FLAG_AUTHENABLE",
            "INFO_FLAG_SEL_CANDIDATE",
            "INFO_FLAG_SHORTLIST",
            "INFO_FLAG_IBURST",
        ],
    ),
    FieldDesc::uint("timereset", 96, 32, 0),
    FieldDesc::uint("timereceived", 128, 32, 0),
    FieldDesc::uint("timetosend", 160, 32, 0),
    FieldDesc::uint("timereachable", 192, 32, 0),
    FieldDesc::uint("sent", 224, 32, 0),
    FieldDesc::uint("unused1", 256, 32, 0),
    FieldDesc::uint("processed", 288, 32, 0),
    FieldDesc::uint("unused2", 320, 32, 0),
    FieldDesc::uint("badauth", 352, 32, 0),
    FieldDesc::uint("bogusorg", 384, 32, 0),
    FieldDesc::uint("oldpkt", 416, 32, 0),
    FieldDesc::uint("unused3", 448, 32, 0),
    FieldDesc::uint("unused4", 480, 32, 0),
    FieldDesc::uint("seldisp", 512, 32, 0),
    FieldDesc::uint("selbroken", 544, 32, 0),
    FieldDesc::uint("unused5", 576, 32, 0),
    FieldDesc::uint("candidate", 608, 8, 0),
    FieldDesc::uint("unused6", 616, 8, 0),
    FieldDesc::uint("unused7", 624, 8, 0),
    FieldDesc::uint("unused8", 632, 8, 0),
    FieldDesc::uint("v6_flag", 640, 32, 0),
    FieldDesc::uint("unused9", 672, 32, 0),
    FieldDesc::ipv6("dstaddr6", 704),
    FieldDesc::ipv6("srcaddr6", 832),
];

fn header_len(_: &[u8]) -> usize {
    120
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::NTPInfoPeerStats,
    name: "NTPInfoPeerStats",
    fields: FIELDS,
    min_len: 120,
    header_len,
    next: crate::proto::next_raw,
    build_len: 120,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
