// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/ntp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of NTPInfoMonitor1 converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/ntp.py, class NTPInfoMonitor1 (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! RFC 5905 is what scapy's docstring cites for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/ntp/ntpinfomonitor1.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("lasttime", 0, 32, 0),
    FieldDesc::uint("firsttime", 32, 32, 0),
    FieldDesc::uint("lastdrop", 64, 32, 0),
    FieldDesc::uint("count", 96, 32, 0),
    FieldDesc::ipv4("addr", 128, 0),
    FieldDesc::ipv4("daddr", 160, 0),
    FieldDesc::uint("flags", 192, 32, 0),
    FieldDesc::uint("port", 224, 16, 0),
    FieldDesc::uint("mode", 240, 8, 0),
    FieldDesc::uint("version", 248, 8, 0),
    FieldDesc::uint("v6_flag", 256, 32, 0),
    FieldDesc::uint("unused1", 288, 32, 0),
    FieldDesc::ipv6("addr6", 320),
    FieldDesc::ipv6("daddr6", 448),
];

fn header_len(_: &[u8]) -> usize {
    72
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::NTPInfoMonitor1X,
    name: "NTPInfoMonitor1",
    fields: FIELDS,
    min_len: 72,
    header_len,
    next: crate::proto::next_raw,
    build_len: 72,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
