// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/contrib/ospf.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-09-18 — OSPF_DBDesc's field table, its dbdescr flag names and its lsaheaders PacketListField transcribed as a repeating group; checked against RFC 2328 §A.3.3 and §A.4.1

//! RFC 2328 §A.3.3, Database Description packet: a 16-bit interface MTU, the
//! one-octet Options field of §A.2, an octet whose low three bits are I, M and MS
//! (MS least significant) and whose remaining bits are reserved, a 32-bit DD
//! sequence number, and then the 20-octet LSA headers of §A.4.1 to the end of the
//! packet — a repeating group (`crates/wiry-core/src/repeat.rs`).
//!
//! RFC 4811 §3 defines bit 3 of that octet as R (OOBResync), which is the fourth
//! flag named here.
//!
//! Generated by dev/protogen from dev/protogen/specs/ospf_dbdesc.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};
use crate::repeat::{ElemLen, Extent, GroupDesc};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("mtu", 0, 16, 1500),
    FieldDesc::flags(
        "options",
        16,
        8,
        &["MT", "E", "MC", "NP", "L", "DC", "O", "DN"],
    ),
    FieldDesc::flags("dbdescr", 24, 8, &["MS", "M", "I", "R", "4", "3", "2", "1"]),
    FieldDesc::uint("ddseq", 32, 32, 1),
    FieldDesc::var_bytes("lsaheaders", 64),
];

pub static GROUP_FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("age", 0, 16, 1),
    FieldDesc::flags(
        "options",
        16,
        8,
        &["MT", "E", "MC", "NP", "L", "DC", "O", "DN"],
    ),
    FieldDesc::uint("type", 24, 8, 1),
    FieldDesc::ipv4("id", 32, 0),
    FieldDesc::ipv4("adrouter", 64, 0),
    FieldDesc::uint("seq", 96, 32, 2147483649),
    FieldDesc::uint("chksum", 128, 16, 0),
    FieldDesc::uint("len", 144, 16, 36),
];

pub static GROUP: GroupDesc = GroupDesc::new(
    "OSPF_LSA_Hdr",
    GROUP_FIELDS,
    ElemLen::Fixed(20),
    Extent::Rest,
    8,
);

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::OspfDbDesc,
    name: "OSPF_DBDesc",
    fields: FIELDS,
    min_len: 8,
    header_len: crate::proto::header_len_rest,
    next: crate::proto::next_end,
    build_len: 8,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 2328 §A.3.3 database description, hand-built: MTU 1500, I+M+MS set, sequence 1, no LSA headers.
    fn vector() -> Vec<u8> {
        vec![0x05, 0xdc, 0x02, 0x07, 0x00, 0x00, 0x00, 0x01]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::OspfDbDesc);
        let l = p.find_layer(ProtoId::OspfDbDesc).unwrap();
        assert_eq!(p.get(l, "mtu").unwrap(), FieldValue::Uint(1500));
        assert_eq!(p.get(l, "ddseq").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::OspfDbDesc);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::OspfDbDesc);
        let l = p.find_layer(ProtoId::OspfDbDesc).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::OspfDbDesc, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
