// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/contrib/ospf.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-09-18 — OSPF_LSA_Hdr's field table and OSPF_LSAck's length_from rule transcribed as a length-driven repeating group; checked against RFC 2328 §A.3.6 and §A.4.1
//   2026-09-18 — the acknowledgement group moved off the header onto an OSPF_LSAck layer, and OSPF_Hdr's crypto authentication fields (reserved, keyid, authdatalen, seq) transcribed from OSPF_Hdr's ConditionalFields; checked against RFC 2328 §D.3

//! RFC 2328 §A.3.1: every OSPF version 2 packet opens with a one-octet version, a
//! one-octet type, a 16-bit packet length, the 32-bit router id, the 32-bit area
//! id, a 16-bit checksum, a 16-bit authentication type and 64 bits of
//! authentication data. §D.3 gives those 64 bits a structure when the
//! authentication type is 2 (Cryptographic): a reserved word, a key id, an
//! authentication data length and a 32-bit cryptographic sequence number, which is
//! why five of the fields here are conditional on `authtype`.
//!
//! The five bodies of §A.3.2 to §A.3.6 are separate layers, reached from `type` as
//! scapy's `bind_layers(OSPF_Hdr, ..., type=n)` reaches them: OSPF_Hello,
//! OSPF_DBDesc, OSPF_LSReq, OSPF_LSUpd and OSPF_LSAck. The packet length bounds
//! them, so each body's repeating group simply runs to the end of what this header
//! admits.
//!
//! Generated by dev/protogen from dev/protogen/specs/ospf.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{Next, ProtoDesc, ProtoId};

// protogen:hand begin
/// RFC 2328 §A.3.1: Packet length covers the header and the body.
fn content_len(hdr: &[u8]) -> usize {
    match hdr.get(2..4) {
        Some(b) => u16::from_be_bytes([b[0], b[1]]) as usize,
        None => 0,
    }
}

/// RFC 2328 §D.3: authentication type 2 gives the 64 authentication bits a
/// structure; every other type leaves them opaque.
fn is_crypto_auth(hdr: &[u8]) -> bool {
    matches!(hdr.get(14..16), Some([0, 2]))
}

fn is_plain_auth(hdr: &[u8]) -> bool {
    !is_crypto_auth(hdr)
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("version", 0, 8, 2),
    FieldDesc::uint("type", 8, 8, 1),
    FieldDesc::uint("len", 16, 16, 24),
    FieldDesc::ipv4("src", 32, 0),
    FieldDesc::ipv4("area", 64, 0),
    FieldDesc::uint("chksum", 96, 16, 0),
    FieldDesc::uint("authtype", 112, 16, 0),
    FieldDesc::bytes("authdata", 128, 64).when(is_plain_auth),
    FieldDesc::uint("reserved", 128, 16, 0).when(is_crypto_auth),
    FieldDesc::uint("keyid", 144, 8, 1).when(is_crypto_auth),
    FieldDesc::uint("authdatalen", 152, 8, 0).when(is_crypto_auth),
    FieldDesc::uint("seq", 160, 32, 0).when(is_crypto_auth),
];

fn header_len(_: &[u8]) -> usize {
    24
}

fn next(hdr: &[u8]) -> Next {
    if hdr.len() < 2 {
        return Next::Raw;
    }
    match crate::field::read_bits(hdr, 8, 8) {
        1 => Next::Proto(ProtoId::OspfHello),
        2 => Next::Proto(ProtoId::OspfDbDesc),
        3 => Next::Proto(ProtoId::OspfLsReq),
        4 => Next::Proto(ProtoId::OspfLsUpd),
        5 => Next::Proto(ProtoId::OspfLsAck),
        _ => Next::Raw,
    }
}

fn bind_next(hdr: &mut [u8], p: ProtoId) {
    let v = match p {
        ProtoId::OspfHello => 1,
        ProtoId::OspfDbDesc => 2,
        ProtoId::OspfLsReq => 3,
        ProtoId::OspfLsUpd => 4,
        ProtoId::OspfLsAck => 5,
        _ => return,
    };
    if hdr.len() >= 2 {
        crate::field::write_bits(hdr, 8, 8, v);
    }
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Ospf,
    name: "OSPF_Hdr",
    fields: FIELDS,
    min_len: 24,
    header_len,
    next,
    build_len: 24,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: Some(bind_next),
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 2328 §A.3.2 hello, hand-built: router 10.0.0.1, area 0.0.0.0, length 24.
    fn vector() -> Vec<u8> {
        vec![
            0x02, 0x01, 0x00, 0x18, 0x0a, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Ospf);
        let l = p.find_layer(ProtoId::Ospf).unwrap();
        assert_eq!(p.get(l, "version").unwrap(), FieldValue::Uint(2));
        assert_eq!(p.get(l, "type").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "len").unwrap(), FieldValue::Uint(24));
        assert_eq!(p.get(l, "chksum").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "authtype").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Ospf);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Ospf);
        let l = p.find_layer(ProtoId::Ospf).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Ospf, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }

    fn hello() -> Vec<u8> {
        let mut v = vector();
        v[3] = 48;
        v.extend_from_slice(&[
            0xff, 0xff, 0xff, 0x00, 0x00, 0x0a, 0x02, 0x01, 0x00, 0x00, 0x00, 0x28, 0x0a, 0x00,
            0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x02,
        ]);
        v
    }

    #[test]
    fn the_type_octet_reaches_the_body_layer() {
        let p = Packet::dissect(hello(), ProtoId::Ospf);
        assert_eq!(
            p.layers().iter().map(|s| s.proto).collect::<Vec<_>>(),
            vec![ProtoId::Ospf, ProtoId::OspfHello]
        );
        let l = p.find_layer(ProtoId::OspfHello).unwrap();
        assert_eq!(p.options(l).unwrap().len(), 1);
    }

    /// RFC 2328 §A.3.1: `len` covers the header and the body, so octets past it
    /// are not part of the hello however well formed they look.
    #[test]
    fn the_packet_length_bounds_the_body() {
        let mut data = hello();
        data.extend_from_slice(&[10, 0, 0, 3]);
        let p = Packet::dissect(data, ProtoId::Ospf);
        let l = p.find_layer(ProtoId::OspfHello).unwrap();
        assert_eq!(p.options(l).unwrap().len(), 1);
        assert!(p.find_layer(ProtoId::Padding).is_some());
    }

    /// RFC 2328 §D.3 gives the 64 authentication bits a structure only when the
    /// type is 2, so reading `keyid` from a null-authenticated packet would be
    /// reading the opaque authentication data.
    #[test]
    fn the_crypto_authentication_fields_appear_only_for_type_two() {
        let p = Packet::dissect(vector(), ProtoId::Ospf);
        let l = p.find_layer(ProtoId::Ospf).unwrap();
        assert!(p.get(l, "keyid").is_none());
        assert!(p.get(l, "authdata").is_some());

        let mut data = vector();
        data[15] = 2;
        data[18] = 7;
        let p = Packet::dissect(data, ProtoId::Ospf);
        let l = p.find_layer(ProtoId::Ospf).unwrap();
        assert_eq!(p.get(l, "keyid").unwrap(), FieldValue::Uint(7));
        assert!(p.get(l, "authdata").is_none());
    }

    #[test]
    fn every_body_type_reaches_its_own_layer() {
        for (ty, want) in [
            (1u8, ProtoId::OspfHello),
            (2, ProtoId::OspfDbDesc),
            (3, ProtoId::OspfLsReq),
            (4, ProtoId::OspfLsUpd),
            (5, ProtoId::OspfLsAck),
        ] {
            let mut data = vector();
            data[1] = ty;
            data[3] = 24 + 24;
            data.extend(std::iter::repeat_n(0u8, 24));
            let p = Packet::dissect(data, ProtoId::Ospf);
            assert!(p.find_layer(want).is_some(), "type {ty}");
        }
    }
    // protogen:tests end
}
