//! RFC 2328 §A.3.1: every OSPF version 2 packet opens with a one-octet version, a
//! one-octet type, a 16-bit packet length, the 32-bit router id, the 32-bit area
//! id, a 16-bit checksum, a 16-bit authentication type and 64 bits of
//! authentication data. The body that follows is per-type (§A.3.2 onwards) and is
//! left opaque, except the one body that is nothing but a repeating group.
//!
//! RFC 2328 §A.3.6: a Link State Acknowledgment (type 5) is a list of 20-octet LSA
//! headers — §A.4.1: a 16-bit age, an options octet, a one-octet LS type, the link
//! state and advertising-router ids, a 32-bit sequence number, a checksum and the
//! LSA's own length — which fill the packet from octet 24 to the `len` the header
//! declares. That is a length-driven repeating group
//! (`crates/wiry-core/src/repeat.rs`); scapy writes the same rule as
//! `length_from=lambda pkt: pkt.underlayer.len - 24`. The other bodies (§A.3.2
//! onwards) stay opaque — see DEVIATIONS E1.
//!
//! Generated by dev/protogen from dev/protogen/specs/ospf.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};
use crate::repeat::{ElemLen, Extent, GroupDesc};

// protogen:hand begin
/// RFC 2328 §A.3.1: Packet length covers the header and the body.
fn content_len(hdr: &[u8]) -> usize {
    match hdr.get(2..4) {
        Some(b) => u16::from_be_bytes([b[0], b[1]]) as usize,
        None => 0,
    }
}

/// RFC 2328 §A.3.1: type 5 is the Link State Acknowledgment, the one body that
/// is nothing but LSA headers.
fn is_ls_ack(hdr: &[u8]) -> bool {
    hdr.get(1) == Some(&5)
}

/// Only the acknowledgment's body belongs to the header; every other type
/// stops at the fixed 24 octets and leaves its body opaque.
fn header_len(hdr: &[u8]) -> usize {
    if !is_ls_ack(hdr) {
        return 24;
    }
    (24 + crate::repeat::region_len(hdr, &GROUP)).min(hdr.len())
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("version", 0, 8, 2),
    FieldDesc::uint("type", 8, 8, 1),
    FieldDesc::uint("len", 16, 16, 24),
    FieldDesc::ipv4("src", 32, 0),
    FieldDesc::ipv4("area", 64, 0),
    FieldDesc::uint("chksum", 96, 16, 0),
    FieldDesc::uint("authtype", 112, 16, 0),
    FieldDesc::bytes("authdata", 128, 64),
    FieldDesc::var_bytes("lsaheaders", 192).when(is_ls_ack),
];

pub static GROUP_FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("age", 0, 16, 1),
    FieldDesc::flags(
        "options",
        16,
        8,
        &["MT", "E", "MC", "NP", "L", "DC", "O", "DN"],
    ),
    FieldDesc::uint("type", 24, 8, 1),
    FieldDesc::ipv4("id", 32, 0),
    FieldDesc::ipv4("adrouter", 64, 0),
    FieldDesc::uint("seq", 96, 32, 2147483649),
    FieldDesc::uint("chksum", 128, 16, 0),
    FieldDesc::uint("len", 144, 16, 36),
];

pub static GROUP: GroupDesc = GroupDesc::new(
    "OSPF_LSA_Hdr",
    GROUP_FIELDS,
    ElemLen::Fixed(20),
    Extent::Length {
        bit_off: 16,
        bit_len: 16,
        scale: 1,
        covers: 24,
    },
    24,
)
.when(is_ls_ack);

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Ospf,
    name: "OSPF_Hdr",
    fields: FIELDS,
    min_len: 24,
    header_len,
    next: crate::proto::next_raw,
    build_len: 24,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 2328 §A.3.2 hello, hand-built: router 10.0.0.1, area 0.0.0.0, length 24.
    fn vector() -> Vec<u8> {
        vec![
            0x02, 0x01, 0x00, 0x18, 0x0a, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Ospf);
        let l = p.find_layer(ProtoId::Ospf).unwrap();
        assert_eq!(p.get(l, "version").unwrap(), FieldValue::Uint(2));
        assert_eq!(p.get(l, "type").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "len").unwrap(), FieldValue::Uint(24));
        assert_eq!(p.get(l, "chksum").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "authtype").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Ospf);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Ospf);
        let l = p.find_layer(ProtoId::Ospf).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Ospf, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
