// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/ppp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of PPP_LCP_Magic_Number_Option converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/ppp.py, class PPP_LCP_Magic_Number_Option (scapy 2.7.0),
//! converted by dev/protogen/scapy2spec.py from the field objects scapy builds at
//! run time. RFC 1661 is what scapy's docstring cites for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/ppp/ppp_lcp_magic_number_option.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("type", 0, 8, 5).named(&[
        (1, "Maximum-Receive-Unit"),
        (2, "Async-Control-Character-Map"),
        (3, "Authentication-protocol"),
        (4, "Quality-protocol"),
        (5, "Magic-number"),
        (7, "Protocol-Field-Compression"),
        (8, "Address-and-Control-Field-Compression"),
        (13, "Callback"),
    ]),
    FieldDesc::uint("len", 8, 8, 6),
    FieldDesc::uint("magic_number", 16, 32, 0),
];

fn header_len(_: &[u8]) -> usize {
    6
}

fn content_len(_: &[u8]) -> usize {
    6
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::PPPLCPMagicNumberOption,
    name: "PPP_LCP_Magic_Number_Option",
    fields: FIELDS,
    min_len: 6,
    header_len,
    next: crate::proto::next_end,
    build_len: 6,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
