// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/ppp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of PPP_LCP_Callback_Option converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/ppp.py, class PPP_LCP_Callback_Option (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! RFC 1661 is what scapy's docstring cites for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/ppp/ppp_lcp_callback_option.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("type", 0, 8, 13).named(&[
        (1, "Maximum-Receive-Unit"),
        (2, "Async-Control-Character-Map"),
        (3, "Authentication-protocol"),
        (4, "Quality-protocol"),
        (5, "Magic-number"),
        (7, "Protocol-Field-Compression"),
        (8, "Address-and-Control-Field-Compression"),
        (13, "Callback"),
    ]),
    FieldDesc::uint("len", 8, 8, 0),
    FieldDesc::uint("operation", 16, 8, 0).named(&[
        (0, "Location determined by user authentication"),
        (1, "Dialing string"),
        (2, "Location identifier"),
        (3, "E.164 number"),
        (4, "Distinguished name"),
    ]),
    FieldDesc::var_bytes("message", 24),
];

fn header_len(hdr: &[u8]) -> usize {
    let v_len = crate::field::decode(hdr, &FIELDS[1]).as_uint().unwrap_or(0) as i64;
    let n: i64 = v_len.wrapping_sub(3i64);
    3 + n.clamp(0, hdr.len() as i64) as usize
}

fn set_hlen(hdr: &mut [u8], hlen: usize) {
    let v_x = hlen.saturating_sub(3) as i64;
    let v: i64 = v_x.wrapping_add(3i64);
    let f = &FIELDS[1];
    if v >= 0 && crate::field::fits(f, v as u64) {
        let w = crate::field::wire_uint(f, v as u64);
        crate::field::write_bits(hdr, f.bit_off, f.bit_len, w);
    }
}

fn content_len(hdr: &[u8]) -> usize {
    header_len(hdr)
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::PPPLCPCallbackOption,
    name: "PPP_LCP_Callback_Option",
    fields: FIELDS,
    min_len: 3,
    header_len,
    next: crate::proto::next_end,
    build_len: 3,
    parse_options: None,
    opt_table: None,
    set_hlen: Some(set_hlen),
    bind_next: None,
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
