// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/radius.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — enumerated names of code transcribed

//! RFC 2865 §3: a one-octet code, a one-octet identifier, a 16-bit length covering
//! the whole packet and a 16-octet authenticator, followed by attributes. §5: an
//! attribute is a one-octet type and a one-octet length that counts the type and
//! length octets themselves. Codes and attribute types from the IANA "RADIUS
//! Types" registry.
//!
//! Generated by dev/protogen from dev/protogen/specs/radius.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
use crate::layers::tlv::{self, TlvFmt};
use crate::options::Item;

/// RFC 2865 §3: Length covers the whole packet and is at least 20.
fn message_len(hdr: &[u8]) -> usize {
    match hdr.get(2..4) {
        Some(b) => (u16::from_be_bytes([b[0], b[1]]) as usize).max(20),
        None => 20,
    }
}

fn header_len(hdr: &[u8]) -> usize {
    message_len(hdr)
}

fn content_len(hdr: &[u8]) -> usize {
    message_len(hdr)
}

/// §5: the length octet counts the type and length octets too.
const ATTRS: TlvFmt = TlvFmt::new(8, 8).covering_header();

fn attr_name(t: u32) -> Option<&'static str> {
    Some(match t {
        1 => "User-Name",
        2 => "User-Password",
        4 => "NAS-IP-Address",
        5 => "NAS-Port",
        6 => "Service-Type",
        7 => "Framed-Protocol",
        8 => "Framed-IP-Address",
        18 => "Reply-Message",
        24 => "State",
        26 => "Vendor-Specific",
        30 => "Called-Station-Id",
        31 => "Calling-Station-Id",
        32 => "NAS-Identifier",
        40 => "Acct-Status-Type",
        44 => "Acct-Session-Id",
        61 => "NAS-Port-Type",
        79 => "EAP-Message",
        80 => "Message-Authenticator",
        _ => return None,
    })
}

fn parse_options(hdr: &[u8]) -> Vec<Item> {
    tlv::items(hdr.get(20..).unwrap_or(&[]), &ATTRS, attr_name)
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("code", 0, 8, 1).named(&[
        (1, "Access-Request"),
        (2, "Access-Accept"),
        (3, "Access-Reject"),
        (4, "Accounting-Request"),
        (5, "Accounting-Response"),
        (6, "Accounting-Status (now Interim Accounting)"),
        (7, "Password-Request"),
        (8, "Password-Ack"),
        (9, "Password-Reject"),
        (10, "Accounting-Message"),
        (11, "Access-Challenge"),
        (12, "Status-Server (experimental)"),
        (13, "Status-Client (experimental)"),
        (21, "Resource-Free-Request"),
        (22, "Resource-Free-Response"),
        (23, "Resource-Query-Request"),
        (24, "Resource-Query-Response"),
        (25, "Alternate-Resource-Reclaim-Request"),
        (26, "NAS-Reboot-Request"),
        (27, "NAS-Reboot-Response"),
        (28, "Reserved"),
        (29, "Next-Passcode"),
        (30, "New-Pin"),
        (31, "Terminate-Session"),
        (32, "Password-Expired"),
        (33, "Event-Request"),
        (34, "Event-Response"),
        (40, "Disconnect-Request"),
        (41, "Disconnect-ACK"),
        (42, "Disconnect-NAK"),
        (43, "CoA-Request"),
        (44, "CoA-ACK"),
        (45, "CoA-NAK"),
        (50, "IP-Address-Allocate"),
        (51, "IP-Address-Release"),
        (52, "Protocol-Error"),
        (250, "Experimental Use"),
        (251, "Experimental Use"),
        (252, "Experimental Use"),
        (253, "Experimental Use"),
        (254, "Reserved"),
        (255, "Reserved"),
    ]),
    FieldDesc::uint("id", 8, 8, 0),
    FieldDesc::uint("len", 16, 16, 20),
    FieldDesc::bytes("authenticator", 32, 128),
    FieldDesc::var_bytes("options", 160),
];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Radius,
    name: "Radius",
    fields: FIELDS,
    min_len: 20,
    header_len,
    next: crate::proto::next_end,
    build_len: 20,
    parse_options: Some(parse_options),
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 2865 §7.1 Access-Request: code 1, id 0, length 26, one User-Name attribute "bob".
    fn vector() -> Vec<u8> {
        vec![
            0x01, 0x00, 0x00, 0x1a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x05, 0x62, 0x6f, 0x62, 0x00,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Radius);
        let l = p.find_layer(ProtoId::Radius).unwrap();
        assert_eq!(p.get(l, "code").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "id").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "len").unwrap(), FieldValue::Uint(26));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Radius);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Radius);
        let l = p.find_layer(ProtoId::Radius).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Radius, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
