//! RFC 3550 §6.1: every RTCP packet opens with a two-bit version, a padding bit, a
//! five-bit item count whose meaning is per packet type, a one-octet packet type
//! (200 SR, 201 RR, 202 SDES, 203 BYE, 204 APP) and a 16-bit length in 32-bit
//! words minus one. The per-type bodies of §6.4 onwards stay opaque. Like RTP, no
//! port is bound by default.
//!
//! Generated by dev/protogen from dev/protogen/specs/rtcp.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
/// RFC 3550 §6.1: length is in 32-bit words and does not count the first one.
fn content_len(hdr: &[u8]) -> usize {
    match hdr.get(2..4) {
        Some(b) => 4 + u16::from_be_bytes([b[0], b[1]]) as usize * 4,
        None => 0,
    }
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("version", 0, 2, 2),
    FieldDesc::uint("padding", 2, 1, 0),
    FieldDesc::uint("count", 3, 5, 0),
    FieldDesc::uint("type", 8, 8, 200),
    FieldDesc::uint("length", 16, 16, 1),
];

fn header_len(_: &[u8]) -> usize {
    4
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Rtcp,
    name: "RTCP",
    fields: FIELDS,
    min_len: 4,
    header_len,
    next: crate::proto::next_raw,
    build_len: 4,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: Some(content_len),
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 3550 §6.4.2 receiver report with no report blocks: version 2, type 201, length 1.
    fn vector() -> Vec<u8> {
        vec![0x80, 0xc9, 0x00, 0x01, 0x11, 0x22, 0x33, 0x44]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Rtcp);
        let l = p.find_layer(ProtoId::Rtcp).unwrap();
        assert_eq!(p.get(l, "version").unwrap(), FieldValue::Uint(2));
        assert_eq!(p.get(l, "padding").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "count").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "type").unwrap(), FieldValue::Uint(201));
        assert_eq!(p.get(l, "length").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Rtcp);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Rtcp);
        let l = p.find_layer(ProtoId::Rtcp).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Rtcp, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
