// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/sctp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of SCTPChunkShutdownComplete converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/sctp.py, class SCTPChunkShutdownComplete (scapy 2.7.0), converted
//! by dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/sctp/sctpchunkshutdowncomplete.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("type", 0, 8, 14).named(&[
        (0, "data"),
        (1, "init"),
        (2, "init-ack"),
        (3, "sack"),
        (4, "heartbeat-req"),
        (5, "heartbeat-ack"),
        (6, "abort"),
        (7, "shutdown"),
        (8, "shutdown-ack"),
        (9, "error"),
        (10, "cookie-echo"),
        (11, "cookie-ack"),
        (14, "shutdown-complete"),
        (15, "authentication"),
        (64, "i-data"),
        (128, "address-configuration-ack"),
        (130, "re-config"),
        (132, "pad"),
        (192, "forward-tsn"),
        (193, "address-configuration"),
        (194, "i-forward-tsn"),
    ]),
    FieldDesc::uint("reserved", 8, 7, 0),
    FieldDesc::uint("TCB", 15, 1, 0),
    FieldDesc::uint("len", 16, 16, 4),
];

fn header_len(_: &[u8]) -> usize {
    4
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::SCTPChunkShutdownComplete,
    name: "SCTPChunkShutdownComplete",
    fields: FIELDS,
    min_len: 4,
    header_len,
    next: crate::proto::next_raw,
    build_len: 4,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
