// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/skinny.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of Skinny converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/skinny.py, class Skinny (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/skinny/skinny.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::le_uint("len", 0, 32, 0),
    FieldDesc::le_uint("res", 32, 32, 0),
    FieldDesc::le_uint("msg", 64, 32, 0).named(&[
        (0, "KeepAliveMessage"),
        (1, "RegisterMessage"),
        (2, "IpPortMessage"),
        (3, "KeypadButtonMessage"),
        (4, "EnblocCallMessage"),
        (5, "StimulusMessage"),
        (6, "OffHookMessage"),
        (7, "OnHookMessage"),
        (8, "HookFlashMessage"),
        (9, "ForwardStatReqMessage"),
        (10, "SpeedDialStatReqMessage"),
        (11, "LineStatReqMessage"),
        (12, "ConfigStatReqMessage"),
        (13, "TimeDateReqMessage"),
        (14, "ButtonTemplateReqMessage"),
        (15, "VersionReqMessage"),
        (16, "CapabilitiesResMessage"),
        (17, "MediaPortListMessage"),
        (18, "ServerReqMessage"),
        (32, "AlarmMessage"),
        (33, "MulticastMediaReceptionAck"),
        (34, "OpenReceiveChannelAck"),
        (35, "ConnectionStatisticsRes"),
        (36, "OffHookWithCgpnMessage"),
        (37, "SoftKeySetReqMessage"),
        (38, "SoftKeyEventMessage"),
        (39, "UnregisterMessage"),
        (40, "SoftKeyTemplateReqMessage"),
        (41, "RegisterTokenReq"),
        (42, "MediaTransmissionFailure"),
        (43, "HeadsetStatusMessage"),
        (44, "MediaResourceNotification"),
        (45, "RegisterAvailableLinesMessage"),
        (46, "DeviceToUserDataMessage"),
        (47, "DeviceToUserDataResponseMessage"),
        (48, "UpdateCapabilitiesMessage"),
        (49, "OpenMultiMediaReceiveChannelAckMessage"),
        (50, "ClearConferenceMessage"),
        (51, "ServiceURLStatReqMessage"),
        (52, "FeatureStatReqMessage"),
        (53, "CreateConferenceResMessage"),
        (54, "DeleteConferenceResMessage"),
        (55, "ModifyConferenceResMessage"),
        (56, "AddParticipantResMessage"),
        (57, "AuditConferenceResMessage"),
        (64, "AuditParticipantResMessage"),
        (65, "DeviceToUserDataVersion1Message"),
        (66, "DeviceToUserDataResponseVersion1Message"),
        (129, "RegisterAckMessage"),
        (130, "StartToneMessage"),
        (131, "StopToneMessage"),
        (133, "SetRingerMessage"),
        (134, "SetLampMessage"),
        (135, "SetHkFDetectMessage"),
        (136, "SetSpeakerModeMessage"),
        (137, "SetMicroModeMessage"),
        (138, "StartMediaTransmission"),
        (139, "StopMediaTransmission"),
        (140, "StartMediaReception"),
        (141, "StopMediaReception"),
        (143, "CallInfoMessage"),
        (144, "ForwardStatMessage"),
        (145, "SpeedDialStatMessage"),
        (146, "LineStatMessage"),
        (147, "ConfigStatMessage"),
        (148, "DefineTimeDate"),
        (149, "StartSessionTransmission"),
        (150, "StopSessionTransmission"),
        (151, "ButtonTemplateMessage"),
        (152, "VersionMessage"),
        (153, "DisplayTextMessage"),
        (154, "ClearDisplay"),
        (155, "CapabilitiesReqMessage"),
        (156, "EnunciatorCommandMessage"),
        (157, "RegisterRejectMessage"),
        (158, "ServerResMessage"),
        (159, "Reset"),
        (256, "KeepAliveAckMessage"),
        (257, "StartMulticastMediaReception"),
        (258, "StartMulticastMediaTransmission"),
        (259, "StopMulticastMediaReception"),
        (260, "StopMulticastMediaTransmission"),
        (261, "OpenReceiveChannel"),
        (262, "CloseReceiveChannel"),
        (263, "ConnectionStatisticsReq"),
        (264, "SoftKeyTemplateResMessage"),
        (265, "SoftKeySetResMessage"),
        (272, "SelectSoftKeysMessage"),
        (273, "CallStateMessage"),
        (274, "DisplayPromptStatusMessage"),
        (275, "ClearPromptStatusMessage"),
        (276, "DisplayNotifyMessage"),
        (277, "ClearNotifyMessage"),
        (278, "ActivateCallPlaneMessage"),
        (279, "DeactivateCallPlaneMessage"),
        (280, "UnregisterAckMessage"),
        (281, "BackSpaceReqMessage"),
        (282, "RegisterTokenAck"),
        (283, "RegisterTokenReject"),
        (284, "StartMediaFailureDetection"),
        (285, "DialedNumberMessage"),
        (286, "UserToDeviceDataMessage"),
        (287, "FeatureStatMessage"),
        (288, "DisplayPriNotifyMessage"),
        (289, "ClearPriNotifyMessage"),
        (290, "StartAnnouncementMessage"),
        (291, "StopAnnouncementMessage"),
        (292, "AnnouncementFinishMessage"),
        (295, "NotifyDtmfToneMessage"),
        (296, "SendDtmfToneMessage"),
        (297, "SubscribeDtmfPayloadReqMessage"),
        (298, "SubscribeDtmfPayloadResMessage"),
        (299, "SubscribeDtmfPayloadErrMessage"),
        (300, "UnSubscribeDtmfPayloadReqMessage"),
        (301, "UnSubscribeDtmfPayloadResMessage"),
        (302, "UnSubscribeDtmfPayloadErrMessage"),
        (303, "ServiceURLStatMessage"),
        (304, "CallSelectStatMessage"),
        (305, "OpenMultiMediaChannelMessage"),
        (306, "StartMultiMediaTransmission"),
        (307, "StopMultiMediaTransmission"),
        (308, "MiscellaneousCommandMessage"),
        (309, "FlowControlCommandMessage"),
        (310, "CloseMultiMediaReceiveChannel"),
        (311, "CreateConferenceReqMessage"),
        (312, "DeleteConferenceReqMessage"),
        (313, "ModifyConferenceReqMessage"),
        (314, "AddParticipantReqMessage"),
        (315, "DropParticipantReqMessage"),
        (316, "AuditConferenceReqMessage"),
        (317, "AuditParticipantReqMessage"),
        (319, "UserToDeviceDataVersion1Message"),
    ]),
];

fn header_len(_: &[u8]) -> usize {
    12
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Skinny,
    name: "Skinny",
    fields: FIELDS,
    min_len: 12,
    header_len,
    next: crate::proto::next_raw,
    build_len: 12,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
