// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/smb2.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of SMB2_Transform_Header converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/smb2.py, class SMB2_Transform_Header (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/smb2/smb2_transform_header.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{Next, ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::bytes("Start", 0, 32).defaulting_to(&[253, 83, 77, 66]),
    FieldDesc::bytes("Signature", 32, 128),
    FieldDesc::bytes("Nonce", 160, 128),
    FieldDesc::le_uint("OriginalMessageSize", 288, 32, 0),
    FieldDesc::le_uint("Reserved", 320, 16, 0),
    FieldDesc::le_uint("Flags", 336, 16, 1).named(&[(1, "ENCRYPTED")]),
    FieldDesc::le_uint("SessionId", 352, 64, 0),
];

fn header_len(_: &[u8]) -> usize {
    52
}

fn next(_: &[u8]) -> Next {
    Next::Proto(ProtoId::Raw)
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::SMB2TransformHeader,
    name: "SMB2_Transform_Header",
    fields: FIELDS,
    min_len: 52,
    header_len,
    next,
    build_len: 52,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
