//! RFC 5321 §4.1: SMTP commands are a verb and optional parameters terminated by
//! CR LF; §4.2 replies are a three-digit code, a space or a hyphen, and text.
//! Line-oriented (DEVIATIONS T1).
//!
//! Generated by dev/protogen from dev/protogen/specs/smtp.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
use crate::layers::text;
use crate::options::Item;

pub fn looks_like(p: &[u8]) -> bool {
    text::looks_like_control(p)
}

fn parse_options(hdr: &[u8]) -> Vec<Item> {
    text::control_items(hdr)
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[FieldDesc::var_bytes_to_end("lines", 0)];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Smtp,
    name: "SMTP",
    fields: FIELDS,
    min_len: 4,
    header_len: crate::proto::header_len_rest,
    next: crate::proto::next_end,
    build_len: 4,
    parse_options: Some(parse_options),
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 5321 §4.2 greeting.
    fn vector() -> Vec<u8> {
        vec![
            0x32, 0x32, 0x30, 0x20, 0x61, 0x2e, 0x69, 0x6f, 0x20, 0x45, 0x53, 0x4d, 0x54, 0x50,
            0x0d, 0x0a,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Smtp);
        assert!(p.find_layer(ProtoId::Smtp).is_some());

        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Smtp);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Smtp);
        let l = p.find_layer(ProtoId::Smtp).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Smtp, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
