//! RFC 1157 §4.1 (SNMPv1) and RFC 3416 §3 (SNMPv2c): an SNMP message is a BER
//! SEQUENCE of a version INTEGER, a community OCTET STRING and a context-tagged
//! PDU, and the PDU is a SEQUENCE of request-id, error-status, error-index and a
//! SEQUENCE of variable bindings, each an OID and its value. Encoding rules are
//! ITU-T X.690 §8. The message has no fixed offsets at all, so there is no field
//! table: the whole message is decoded into a named item list (DEVIATIONS T2).
//!
//! Generated by dev/protogen from dev/protogen/specs/snmp.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
use crate::layers::ber;
use crate::options::{Item, ItemValue};
use std::borrow::Cow;

/// RFC 3416 §3: the PDU is a context-tagged choice.
fn pdu_name(tag: u32) -> &'static str {
    match tag {
        0 => "get_request",
        1 => "get_next_request",
        2 => "response",
        3 => "set_request",
        4 => "trap_v1",
        5 => "get_bulk_request",
        6 => "inform_request",
        7 => "trap_v2",
        8 => "report",
        _ => "pdu",
    }
}

fn parse_options(hdr: &[u8]) -> Vec<Item> {
    let mut out = Vec::new();
    let Some(msg) = ber::read(hdr) else {
        return out;
    };
    let kids = ber::children(msg.value);
    if let Some(v) = kids.first() {
        out.push(Item::uint("version", 0, ber::uint(v.value)));
    }
    if let Some(c) = kids.get(1) {
        out.push(Item::named(
            "community",
            1,
            ItemValue::Text(ber::text(c.value)),
        ));
    }
    let Some(pdu) = kids.get(2) else {
        return out;
    };
    out.push(Item::named(
        "PDU",
        pdu.tag,
        ItemValue::Text(pdu_name(pdu.tag).to_string()),
    ));
    let f = ber::children(pdu.value);
    // RFC 1157 §4.1.6 gives a v1 trap a different set of fields entirely.
    if pdu.tag != 4 {
        for (i, n) in ["request_id", "error_status", "error_index"]
            .iter()
            .enumerate()
        {
            if let Some(x) = f.get(i) {
                out.push(Item::uint(n, i as u32 + 2, ber::uint(x.value)));
            }
        }
    }
    let Some(vb) = f.last().filter(|t| t.constructed) else {
        return out;
    };
    for b in ber::children(vb.value) {
        let kv = ber::children(b.value);
        if let (Some(o), Some(v)) = (kv.first(), kv.get(1)) {
            out.push(Item {
                name: Cow::Owned(ber::oid(o.value)),
                code: 0,
                value: ItemValue::Text(ber::render(v)),
            });
        }
    }
    out
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[FieldDesc::var_bytes_to_end("vars", 0)];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Snmp,
    name: "SNMP",
    fields: FIELDS,
    min_len: 2,
    header_len: crate::proto::header_len_rest,
    next: crate::proto::next_end,
    build_len: 2,
    parse_options: Some(parse_options),
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 1157 §4.1 GetRequest, community "public", request-id 1, one varbind for 1.3.6.1.2.1.1.1.0.
    fn vector() -> Vec<u8> {
        vec![
            0x30, 0x26, 0x02, 0x01, 0x00, 0x04, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0xa0,
            0x19, 0x02, 0x01, 0x01, 0x02, 0x01, 0x00, 0x02, 0x01, 0x00, 0x30, 0x0e, 0x30, 0x0c,
            0x06, 0x08, 0x2b, 0x06, 0x01, 0x02, 0x01, 0x01, 0x01, 0x00, 0x05, 0x00,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Snmp);
        assert!(p.find_layer(ProtoId::Snmp).is_some());

        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Snmp);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Snmp);
        let l = p.find_layer(ProtoId::Snmp).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Snmp, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
