// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/ssh.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of SSHNewKeys converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/ssh.py, class SSHNewKeys (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! RFC 4250 is what scapy's docstring cites for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/ssh/sshnewkeys.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[FieldDesc::uint("type", 0, 8, 21).named(&[
    (1, "SSH_MSG_DISCONNECT"),
    (2, "SSH_MSG_IGNORE"),
    (3, "SSH_MSG_UNIMPLEMENTED"),
    (4, "SSH_MSG_DEBUG"),
    (5, "SSH_MSG_SERVICE_REQUEST"),
    (6, "SSH_MSG_SERVICE_ACCEPT"),
    (7, "SSH_MSG_EXT_INFO"),
    (8, "SSH_MSG_NEWCOMPRESS"),
    (20, "SSH_MSG_KEXINIT"),
    (21, "SSH_MSG_NEWKEYS"),
    (30, "SSH_MSG_KEXDH_INIT"),
    (31, "SSH_MSG_KEXDH_REPLY"),
    (50, "SSH_MSG_USERAUTH_REQUEST"),
    (51, "SSH_MSG_USERAUTH_FAILURE"),
    (52, "SSH_MSG_USERAUTH_SUCCESS"),
    (53, "SSH_MSG_USERAUTH_BANNER"),
    (80, "SSH_MSG_GLOBAL_REQUEST"),
    (81, "SSH_MSG_REQUEST_SUCCESS"),
    (82, "SSH_MSG_REQUEST_FAILURE"),
    (90, "SSH_MSG_CHANNEL_OPEN"),
    (91, "SSH_MSG_CHANNEL_OPEN_CONFIRMATION"),
    (92, "SSH_MSG_CHANNEL_OPEN_FAILURE"),
    (93, "SSH_MSG_CHANNEL_WINDOW_ADJUST"),
    (94, "SSH_MSG_CHANNEL_DATA"),
    (95, "SSH_MSG_CHANNEL_EXTENDED_DATA"),
    (96, "SSH_MSG_CHANNEL_EOF"),
    (97, "SSH_MSG_CHANNEL_CLOSE"),
    (98, "SSH_MSG_CHANNEL_REQUEST"),
    (99, "SSH_MSG_CHANNEL_SUCCESS"),
    (100, "SSH_MSG_CHANNEL_FAILURE"),
])];

fn header_len(_: &[u8]) -> usize {
    1
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::SSHNewKeys,
    name: "SSHNewKeys",
    fields: FIELDS,
    min_len: 1,
    header_len,
    next: crate::proto::next_raw,
    build_len: 1,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
