//! IEEE Std 802.1D-2004 §9.3.1, Configuration BPDU: protocol identifier (0x0000),
//! version, BPDU type, flags, root identifier (a two-octet priority and a
//! six-octet address), root path cost, bridge identifier, port identifier, and the
//! four timer values in 1/256-second units. §9.3.2 gives the four-octet
//! Topology Change Notification BPDU, which is why the minimum length is 4.
//! RSTP is version 2 of the same frame (IEEE 802.1D-2004 §17.2).
//!
//! Generated by dev/protogen from dev/protogen/specs/stp.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("proto", 0, 16, 0),
    FieldDesc::uint("version", 16, 8, 0),
    FieldDesc::uint("bpdutype", 24, 8, 0),
    FieldDesc::uint("bpduflags", 32, 8, 0),
    FieldDesc::uint("rootid", 40, 16, 0),
    FieldDesc::mac("rootmac", 56),
    FieldDesc::uint("pathcost", 104, 32, 0),
    FieldDesc::uint("bridgeid", 136, 16, 0),
    FieldDesc::mac("bridgemac", 152),
    FieldDesc::uint("portid", 200, 16, 0),
    FieldDesc::uint("age", 216, 16, 0),
    FieldDesc::uint("maxage", 232, 16, 5120),
    FieldDesc::uint("hellotime", 248, 16, 512),
    FieldDesc::uint("fwddelay", 264, 16, 3840),
];

fn header_len(_: &[u8]) -> usize {
    35
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Stp,
    name: "STP",
    fields: FIELDS,
    min_len: 4,
    header_len,
    next: crate::proto::next_raw,
    build_len: 35,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// IEEE 802.1D §9.3.1 configuration BPDU, hand-built: priority 0x8000, bridge 00:11:22:33:44:55, path cost 0.
    fn vector() -> Vec<u8> {
        vec![
            0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x00,
            0x00, 0x00, 0x00, 0x80, 0x00, 0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x80, 0x01, 0x00,
            0x00, 0x14, 0x00, 0x02, 0x00, 0x0f, 0x00,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Stp);
        let l = p.find_layer(ProtoId::Stp).unwrap();
        assert_eq!(p.get(l, "proto").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "version").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "bpdutype").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "rootid").unwrap(), FieldValue::Uint(32768));
        assert_eq!(p.get(l, "pathcost").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "portid").unwrap(), FieldValue::Uint(32769));
        assert_eq!(p.get(l, "age").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "maxage").unwrap(), FieldValue::Uint(5120));
        assert_eq!(p.get(l, "hellotime").unwrap(), FieldValue::Uint(512));
        assert_eq!(p.get(l, "fwddelay").unwrap(), FieldValue::Uint(3840));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Stp);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Stp);
        let l = p.find_layer(ProtoId::Stp).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Stp, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
