//! RFC 8446 §5.1 (and RFC 5246 §6.2.1, which is the same shape): a TLS record is a
//! one-octet content type (20 change_cipher_spec, 21 alert, 22 handshake,
//! 23 application_data), a two-octet legacy record version and a two-octet length.
//! §4.1.2 gives the ClientHello inside a handshake record: the legacy version, a
//! 32-octet random, a session id, the cipher suites, the compression methods and
//! the extensions, from which §9.2 and RFC 6066 §3 name the server_name
//! extension. Only that chain is followed, because the server name is the field
//! worth reaching; everything else in the record stays bytes.
//!
//! Generated by dev/protogen from dev/protogen/specs/tls.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
use crate::layers::tlv::{self, TlvFmt};
use crate::options::{Item, ItemValue};

/// RFC 8446 §5.1: a content type in 20..=24 and a legacy record version of
/// 0x03xx. Without this a mid-stream segment on port 443 dissects as a record.
pub fn looks_like(p: &[u8]) -> bool {
    matches!(p.first(), Some(20..=24)) && p.get(1) == Some(&3) && p.get(2).is_some_and(|m| *m <= 4)
}

fn record_len(hdr: &[u8]) -> usize {
    match hdr.get(3..5) {
        Some(b) => 5 + u16::from_be_bytes([b[0], b[1]]) as usize,
        None => 5,
    }
}

/// The whole record is the header, so the handshake inside it is in reach of
/// the parser; a second record in the same segment stays payload.
fn header_len(hdr: &[u8]) -> usize {
    record_len(hdr).min(hdr.len()).max(5)
}

/// RFC 6066 §3: a 16-bit list length, a one-octet name type and a 16-bit host
/// name length.
fn server_name(v: &[u8]) -> Option<String> {
    let n = u16::from_be_bytes([*v.get(3)?, *v.get(4)?]) as usize;
    Some(String::from_utf8_lossy(v.get(5..5 + n)?).into_owned())
}

const EXTENSIONS: TlvFmt = TlvFmt::new(16, 16);

/// RFC 8446 §4.1.2 and §4.1.3: both hellos start with a legacy version and a
/// 32-octet random, then differ only in how the cipher suite and compression
/// fields are sized.
fn hello_extensions(body: &[u8], handshake: u8) -> Option<&[u8]> {
    let mut i = 4 + 2 + 32;
    i += 1 + *body.get(i)? as usize;
    if handshake == 1 {
        let b = body.get(i..i + 2)?;
        i += 2 + u16::from_be_bytes([b[0], b[1]]) as usize;
        i += 1 + *body.get(i)? as usize;
    } else {
        i += 3;
    }
    let b = body.get(i..i + 2)?;
    let n = u16::from_be_bytes([b[0], b[1]]) as usize;
    body.get(i + 2..i + 2 + n)
}

fn parse_options(hdr: &[u8]) -> Vec<Item> {
    let mut out = Vec::new();
    let Some(&ct) = hdr.first() else {
        return out;
    };
    out.push(Item::uint("content_type", 0, ct as u64));
    if ct != 22 {
        return out;
    }
    let body = hdr.get(5..).unwrap_or(&[]);
    let Some(&ht) = body.first() else {
        return out;
    };
    out.push(Item::uint("handshake_type", 1, ht as u64));
    if ht != 1 && ht != 2 {
        return out;
    }
    let Some(exts) = hello_extensions(body, ht) else {
        return out;
    };
    for e in tlv::walk(exts, &EXTENSIONS) {
        match e.tag {
            0 => {
                if let Some(n) = server_name(e.value) {
                    out.push(Item::named("server_name", 0, ItemValue::Text(n)));
                }
            }
            16 => out.push(Item::bytes("alpn", 16, e.value)),
            43 => out.push(Item::bytes("supported_versions", 43, e.value)),
            _ => {}
        }
    }
    out
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("type", 0, 8, 22),
    FieldDesc::uint("version", 8, 16, 771),
    FieldDesc::uint("len", 24, 16, 0),
    FieldDesc::var_bytes("options", 40),
];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Tls,
    name: "TLS",
    fields: FIELDS,
    min_len: 5,
    header_len,
    next: crate::proto::next_raw,
    build_len: 5,
    parse_options: Some(parse_options),
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 8446 §4.1.2 ClientHello for "a.io" in one handshake record, hand-built to the minimum the extension needs.
    fn vector() -> Vec<u8> {
        vec![
            0x16, 0x03, 0x01, 0x00, 0x40, 0x01, 0x00, 0x00, 0x3c, 0x03, 0x03, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x02, 0x13, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, 0x00, 0x00, 0x0d,
            0x00, 0x0b, 0x00, 0x00, 0x08, 0x61, 0x2e, 0x69, 0x6f, 0x2e, 0x63, 0x6f, 0x6d,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Tls);
        let l = p.find_layer(ProtoId::Tls).unwrap();
        assert_eq!(p.get(l, "type").unwrap(), FieldValue::Uint(22));
        assert_eq!(p.get(l, "version").unwrap(), FieldValue::Uint(769));
        assert_eq!(p.get(l, "len").unwrap(), FieldValue::Uint(64));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Tls);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Tls);
        let l = p.find_layer(ProtoId::Tls).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Tls, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
