// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/tls/tools.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of TLSPlaintext converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/tls/tools.py, class TLSPlaintext (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/tls_tools/tlsplaintext.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("type", 0, 8, 0).named(&[
        (20, "change_cipher_spec"),
        (21, "alert"),
        (22, "handshake"),
        (23, "application_data"),
    ]),
    FieldDesc::uint("version", 8, 16, 0).named(&[
        (2, "SSLv2"),
        (512, "SSLv2"),
        (768, "SSLv3"),
        (769, "TLS 1.0"),
        (770, "TLS 1.1"),
        (771, "TLS 1.2"),
        (772, "TLS 1.3"),
        (32530, "TLS 1.3-d18"),
        (32531, "TLS 1.3-d19"),
    ]),
    FieldDesc::uint("len", 24, 16, 0),
    FieldDesc::var_bytes("data", 40),
];

fn header_len(hdr: &[u8]) -> usize {
    let v_len = crate::field::decode(hdr, &FIELDS[2]).as_uint().unwrap_or(0) as i64;
    let n: i64 = v_len;
    5 + n.clamp(0, hdr.len() as i64) as usize
}

fn set_hlen(hdr: &mut [u8], hlen: usize) {
    let v_x = hlen.saturating_sub(5) as i64;
    let v: i64 = v_x;
    let f = &FIELDS[2];
    if v >= 0 && crate::field::fits(f, v as u64) {
        let w = crate::field::wire_uint(f, v as u64);
        crate::field::write_bits(hdr, f.bit_off, f.bit_len, w);
    }
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::TLSPlaintext,
    name: "TLSPlaintext",
    fields: FIELDS,
    min_len: 5,
    header_len,
    next: crate::proto::next_raw,
    build_len: 5,
    parse_options: None,
    opt_table: None,
    set_hlen: Some(set_hlen),
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
