// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/tuntap.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of DarwinUtunPacketInfo converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/tuntap.py, class DarwinUtunPacketInfo (scapy 2.7.0), converted by
//! dev/protogen/scapy2spec.py from the field objects scapy builds at run time.
//! scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/tuntap/darwinutunpacketinfo.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{Next, ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[FieldDesc::uint("addr_family", 0, 32, 2)];

fn header_len(_: &[u8]) -> usize {
    4
}

fn next(hdr: &[u8]) -> Next {
    if hdr.len() < 4 {
        return Next::Raw;
    }
    match crate::field::read_bits(hdr, 0, 32) {
        2 => Next::Proto(ProtoId::Ipv4),
        30 => Next::Proto(ProtoId::Ipv6),
        _ => Next::Raw,
    }
}

fn bind_next(hdr: &mut [u8], p: ProtoId) {
    let v = match p {
        ProtoId::Ipv4 => 2,
        ProtoId::Ipv6 => 30,
        _ => return,
    };
    if hdr.len() >= 4 {
        crate::field::write_bits(hdr, 0, 32, v);
    }
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::DarwinUtunPacketInfo,
    name: "DarwinUtunPacketInfo",
    fields: FIELDS,
    min_len: 4,
    header_len,
    next,
    build_len: 4,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: Some(bind_next),
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
