// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/vrrp.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-09-18 — VRRP's addrlist FieldListField transcribed as a count-driven repeating group; checked against RFC 3768 §5.1

//! RFC 3768 §5.1: a four-bit version, a four-bit type, a one-octet virtual router
//! id, a one-octet priority, a one-octet count of IP addresses, a one-octet
//! authentication type, a one-octet advertisement interval in seconds and a 16-bit
//! checksum, followed by that many addresses — a count-driven repeating group
//! (`crates/wiry-core/src/repeat.rs`). RFC 5798 §5.1 keeps the layout for version
//! 3 but reads the two authentication octets as a reserved field and a 12-bit
//! advertisement interval in centiseconds.
//!
//! RFC 3768 §5.3.10 puts eight octets of authentication data after the address
//! list. They sit at an offset the address count decides, which the flat table
//! cannot place, so they stay in the payload (DEVIATIONS E1); scapy declares them
//! as `auth1` and `auth2`.
//!
//! Generated by dev/protogen from dev/protogen/specs/vrrp.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};
use crate::repeat::{ElemLen, Extent, GroupDesc};

// protogen:hand begin
/// RFC 3768 §5.3.10: the eight octets of authentication data that follow the
/// address list are outside the header, so the header ends where the list does.
fn header_len(hdr: &[u8]) -> usize {
    (8 + crate::repeat::region_len(hdr, &GROUP)).min(hdr.len())
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("version", 0, 4, 2),
    FieldDesc::uint("type", 4, 4, 1),
    FieldDesc::uint("vrid", 8, 8, 1),
    FieldDesc::uint("priority", 16, 8, 100),
    FieldDesc::uint("ipcount", 24, 8, 0),
    FieldDesc::uint("authtype", 32, 8, 0),
    FieldDesc::uint("adv", 40, 8, 1),
    FieldDesc::uint("chksum", 48, 16, 0),
    FieldDesc::var_bytes("addrlist", 64),
];

pub static GROUP_FIELDS: &[FieldDesc] = &[FieldDesc::ipv4("addr", 0, 0)];

pub static GROUP: GroupDesc = GroupDesc::new(
    "addrlist",
    GROUP_FIELDS,
    ElemLen::Fixed(4),
    Extent::Count {
        bit_off: 24,
        bit_len: 8,
    },
    8,
);

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::Vrrp,
    name: "VRRP",
    fields: FIELDS,
    min_len: 8,
    header_len,
    next: crate::proto::next_raw,
    build_len: 8,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// RFC 3768 §5.1 advertisement: VRID 1, priority 100, one address 10.0.0.1.
    fn vector() -> Vec<u8> {
        vec![
            0x21, 0x01, 0x64, 0x01, 0x00, 0x01, 0xba, 0x52, 0x0a, 0x00, 0x00, 0x01,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::Vrrp);
        let l = p.find_layer(ProtoId::Vrrp).unwrap();
        assert_eq!(p.get(l, "version").unwrap(), FieldValue::Uint(2));
        assert_eq!(p.get(l, "type").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "vrid").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "priority").unwrap(), FieldValue::Uint(100));
        assert_eq!(p.get(l, "ipcount").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "authtype").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "adv").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "chksum").unwrap(), FieldValue::Uint(47698));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::Vrrp);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::Vrrp);
        let l = p.find_layer(ProtoId::Vrrp).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::Vrrp, false, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }

    use crate::options::ItemValue;

    #[test]
    fn the_address_list_reads_as_a_scalar_list() {
        let mut data = vector();
        data[3] = 2;
        data.extend_from_slice(&[10, 0, 0, 2]);
        let p = Packet::dissect(data, ProtoId::Vrrp);
        let l = p.find_layer(ProtoId::Vrrp).unwrap();
        let items = p.options(l).unwrap();
        assert_eq!(items.len(), 2);
        assert_eq!(items[0].value, ItemValue::Text("10.0.0.1".into()));
        assert_eq!(items[1].value, ItemValue::Text("10.0.0.2".into()));
    }

    /// RFC 3768 §5.3.10: the authentication data after the list is outside the
    /// header, so `ipcount` and not the datagram end decides where it stops.
    #[test]
    fn octets_past_the_count_are_not_addresses() {
        let mut data = vector();
        data.extend(std::iter::repeat_n(0u8, 8));
        let p = Packet::dissect(data, ProtoId::Vrrp);
        let l = p.find_layer(ProtoId::Vrrp).unwrap();
        assert_eq!(p.options(l).unwrap().len(), 1);
        assert!(p.find_layer(ProtoId::Raw).is_some());
    }
    // protogen:tests end
}
