//! J. A. Donenfeld, "WireGuard: Next Generation Kernel Network Tunnel" (2017)
//! §5.4: every message is a one-octet type and three reserved octets. Type 1
//! (handshake initiation) carries a little-endian sender index, a 32-octet
//! ephemeral public key, a 48-octet encrypted static key, a 28-octet encrypted
//! timestamp and two 16-octet MACs. Type 2 (handshake response) carries sender and
//! receiver indices, an ephemeral key, a 16-octet encrypted empty field and the
//! two MACs. Type 3 is a cookie reply and type 4 a transport data message with a
//! receiver index and a 64-bit little-endian counter. The encrypted parts stay
//! opaque.
//!
//! Generated by dev/protogen from dev/protogen/specs/wireguard.toml. Field layouts
//! come from the RFC cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
fn msg(hdr: &[u8]) -> u8 {
    hdr.first().copied().unwrap_or(0)
}

fn has_sender(hdr: &[u8]) -> bool {
    matches!(msg(hdr), 1 | 2)
}

fn has_receiver_first(hdr: &[u8]) -> bool {
    matches!(msg(hdr), 3 | 4)
}

fn is_transport(hdr: &[u8]) -> bool {
    msg(hdr) == 4
}

/// §5.4.2 to §5.4.6 fix every message size but the transport payload's.
fn header_len(hdr: &[u8]) -> usize {
    match msg(hdr) {
        1 => 148,
        2 => 92,
        3 => 64,
        4 => 16,
        _ => 4,
    }
}
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("message_type", 0, 8, 1),
    FieldDesc::uint("reserved_zero", 8, 24, 0),
    FieldDesc::le_uint("sender_index", 32, 32, 0).when(has_sender),
    FieldDesc::le_uint("receiver_index", 32, 32, 0).when(has_receiver_first),
    FieldDesc::le_uint("counter", 64, 64, 0).when(is_transport),
];

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::WireGuard,
    name: "WireGuard",
    fields: FIELDS,
    min_len: 4,
    header_len,
    next: crate::proto::next_raw,
    build_len: 4,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    /// WireGuard whitepaper §5.4.6 transport data message: type 4, receiver index 1, counter 0.
    fn vector() -> Vec<u8> {
        vec![
            0x04, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0xaa, 0xbb,
        ]
    }

    #[test]
    fn dissects_the_rfc_vector() {
        let p = Packet::dissect(vector(), ProtoId::WireGuard);
        let l = p.find_layer(ProtoId::WireGuard).unwrap();
        assert_eq!(p.get(l, "message_type").unwrap(), FieldValue::Uint(4));
        assert_eq!(p.get(l, "reserved_zero").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.get(l, "receiver_index").unwrap(), FieldValue::Uint(1));
        assert_eq!(p.get(l, "counter").unwrap(), FieldValue::Uint(0));
        assert_eq!(p.raw_bytes(), &vector()[..]);
    }

    #[test]
    fn truncation_does_not_panic() {
        for n in 0..vector().len() {
            let p = Packet::dissect(vector()[..n].to_vec(), ProtoId::WireGuard);
            assert_eq!(p.raw_bytes(), &vector()[..n]);
        }
    }

    #[test]
    fn writes_survive_a_rebuild() {
        let mut p = Packet::dissect(vector(), ProtoId::WireGuard);
        let l = p.find_layer(ProtoId::WireGuard).unwrap();
        let n = p.raw_bytes().len();
        for f in crate::proto::active_fields(ProtoId::WireGuard, p.header(l))
            .filter(|f| f.kind == crate::field::FieldKind::Uint && f.bit_len <= 32)
            .map(|f| f.name)
            .collect::<Vec<_>>()
        {
            p.set_uint(l, f, 1);
        }
        assert_eq!(p.to_bytes().len(), n);
    }
    // protogen:tests end
}
