// SPDX-License-Identifier: GPL-2.0-only
//
// Derived from scapy: scapy/layers/zigbee.py
//   scapy 2.7.0
//   Copyright (C) Philippe Biondi and the scapy contributors
//
// Changed by the wiry authors:
//   2026-10-03 — field table, defaults, enum names and bindings of ZCLGeneralDefaultResponse converted mechanically from the field objects by dev/protogen/scapy2spec.py

//! scapy/layers/zigbee.py, class ZCLGeneralDefaultResponse (scapy 2.7.0),
//! converted by dev/protogen/scapy2spec.py from the field objects scapy builds at
//! run time. scapy's docstring cites no RFC for it.
//!
//! Generated by dev/protogen from dev/protogen/specs/scapy/zigbee/zclgeneraldefaultresponse.toml. Field layouts
//! come from the sources cited above; edit the spec, not this file.

use crate::field::FieldDesc;
use crate::proto::{ProtoDesc, ProtoId};

// protogen:hand begin
// protogen:hand end

pub static FIELDS: &[FieldDesc] = &[
    FieldDesc::uint("response_command_identifier", 0, 8, 0),
    FieldDesc::uint("status", 8, 8, 0).named(&[
        (0, "SUCCESS"),
        (1, "FAILURE"),
        (126, "NOT_AUTHORIZED"),
        (127, "RESERVED_FIELD_NOT_ZERO"),
        (128, "MALFORMED_COMMAND"),
        (129, "UNSUP_CLUSTER_COMMAND"),
        (130, "UNSUP_GENERAL_COMMAND"),
        (131, "UNSUP_MANUF_CLUSTER_COMMAND"),
        (132, "UNSUP_MANUF_GENERAL_COMMAND"),
        (133, "INVALID_FIELD"),
        (134, "UNSUPPORTED_ATTRIBUTE"),
        (135, "INVALID_VALUE"),
        (136, "READ_ONLY"),
        (137, "INSUFFICIENT_SPACE"),
        (138, "DUPLICATE_EXISTS"),
        (139, "NOT_FOUND"),
        (140, "UNREPORTABLE_ATTRIBUTE"),
        (141, "INVALID_DATA_TYPE"),
        (142, "INVALID_SELECTOR"),
        (143, "WRITE_ONLY"),
        (144, "INCONSISTENT_STARTUP_STATE"),
        (145, "DEFINED_OUT_OF_BAND"),
        (146, "INCONSISTENT"),
        (147, "ACTION_DENIED"),
        (148, "TIMEOUT"),
        (149, "ABORT"),
        (150, "INVALID_IMAGE"),
        (151, "WAIT_FOR_DATA"),
        (152, "NO_IMAGE_AVAILABLE"),
        (153, "REQUIRE_MORE_IMAGE"),
        (154, "NOTIFICATION_PENDING"),
        (192, "HARDWARE_FAILURE"),
        (193, "SOFTWARE_FAILURE"),
        (194, "CALIBRATION_ERROR"),
        (195, "UNSUPPORTED_CLUSTER"),
    ]),
];

fn header_len(_: &[u8]) -> usize {
    2
}

pub static DESC: ProtoDesc = ProtoDesc {
    id: ProtoId::ZCLGeneralDefaultResponse,
    name: "ZCLGeneralDefaultResponse",
    fields: FIELDS,
    min_len: 2,
    header_len,
    next: crate::proto::next_raw,
    build_len: 2,
    parse_options: None,
    opt_table: None,
    set_hlen: None,
    bind_next: None,
    bind_next_bytes: None,
    content_len: None,
};

#[cfg(test)]
mod tests {
    #![allow(unused_imports)]
    use super::*;
    use crate::field::FieldValue;
    use crate::packet::Packet;

    // protogen:tests begin
    // protogen:tests end
}
