[package]
name = "packetry-core"
description = "Fast, clean-room packet dissection and construction engine"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
smallvec.workspace = true

[dev-dependencies]
